import {expect,test,type Page} from '@playwright/test';
import {readFile,writeFile} from 'node:fs/promises';
import {unzipSync,strFromU8} from 'fflate';
import sharp from 'sharp';
import {initializeApp as adminApp,deleteApp as deleteAdmin} from 'firebase-admin/app';
import {getFirestore as adminDb} from 'firebase-admin/firestore';
import {workbook} from '../fixtures/workbooks.mjs';
test.use({reducedMotion:'reduce'});
async function fixture(page:Page,large=false,tiny=false){
 await page.goto('/register?returnTo=%2Fpacks%2Fnew');await page.getByLabel('Email',{exact:true}).fill('r6-'+crypto.randomUUID()+'@example.test');await page.getByLabel('Password',{exact:true}).fill('Evertrace-test-2026!');await page.getByLabel('Confirm password',{exact:true}).fill('Evertrace-test-2026!');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.getByRole('heading',{name:'Create a skill pack',exact:true})).toBeVisible();
 const title='Synthetic R6 / export '+Date.now(),notes='Synthetic notes 原文 <b>plain text</b>',points=Array.from({length:large?50000:41},(_,i)=>[(i*2.5+Math.floor(i/8))*(tiny?1e-9:1),i===0?-100:i===40?800:large?Math.sin(i/8)*100:i]),excel=Buffer.from(await workbook([['timestamp_ms','value'],...points])),other=Buffer.from(await workbook([['timestamp_ms','value'],...points.map(([time,value])=>[time,-value])])),text=Buffer.from('\ufeffOriginal TXT 一'),text2=Buffer.from('Original TXT 二'),image=await sharp({create:{width:24,height:16,channels:3,background:'#756'}}).png().toBuffer();
 await page.getByLabel('Title',{exact:true}).fill(title);await page.getByLabel('New category',{exact:true}).fill('R6 '+Date.now());await page.getByRole('button',{name:'Add category',exact:true}).click();await expect(page.getByText('Category created and selected.',{exact:true})).toBeVisible();await page.getByLabel('Notes',{exact:true}).fill(notes);await page.getByLabel('Text file',{exact:true}).setInputFiles([{name:'same.txt',mimeType:'text/plain',buffer:text},{name:'same.txt',mimeType:'text/plain',buffer:text2}]);await page.getByLabel('Images',{exact:true}).setInputFiles({name:'image.png',mimeType:'image/png',buffer:image});await page.getByLabel('EEG Excel',{exact:true}).setInputFiles([{name:'same.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:excel},{name:'same.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:other}]);await expect(page.getByRole('img',{name:'EEG preview'})).toHaveCount(2);await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
 const selected=page.locator('.stored-material').filter({hasText:'Raw values · -100 … 800'});await selected.scrollIntoViewIfNeeded();await expect(selected.getByRole('img',{name:'EEG preview',exact:true})).toBeVisible();const index=await selected.evaluate(element=>Array.from(document.querySelectorAll('.stored-material')).indexOf(element));expect(index).toBeGreaterThanOrEqual(0);const first=page.locator('.stored-material').nth(index);return {title,notes,points,excel,other,text,text2,image,first};
}
async function downloaded(page:Page,action:()=>Promise<unknown>){const pending=page.waitForEvent('download');await action();const download=await pending;return {name:download.suggestedFilename(),bytes:await readFile((await download.path())!)};}
test('waveform reads original samples; ZIP and PNG retain full range after zoom and duplicate originals',async({page})=>{
 const f=await fixture(page),range=f.first.getByLabel('Visible time range',{exact:true});await expect(range).toContainText('105 ms');const plot=f.first.getByRole('img',{name:'EEG preview',exact:true}),box=(await plot.boundingBox())!;await page.mouse.move(box.x+box.width*(40+26/105*710)/790,box.y+box.height/2);await expect(f.first.getByLabel('EEG sample',{exact:true})).toHaveText('26 ms · 10');await f.first.getByRole('button',{name:'Zoom in',exact:true}).click();await expect(range).not.toContainText('0 – 105 ms');const priorStart=Number(await f.first.getByLabel('Window start (ms)',{exact:true}).inputValue());const dragBox=(await plot.boundingBox())!;await page.mouse.move(dragBox.x+dragBox.width*.5,dragBox.y+dragBox.height*.5);await page.mouse.down();await page.mouse.move(dragBox.x+dragBox.width*.6,dragBox.y+dragBox.height*.5,{steps:4});await page.mouse.up();await expect.poll(async()=>Number(await f.first.getByLabel('Window start (ms)',{exact:true}).inputValue())).toBeLessThan(priorStart);await page.mouse.wheel(0,-100);await expect.poll(async()=>Number(await f.first.getByLabel('Window end (ms)',{exact:true}).inputValue())-Number(await f.first.getByLabel('Window start (ms)',{exact:true}).inputValue())).toBeLessThan(52.5);await f.first.getByLabel('Window start (ms)',{exact:true}).fill('25');await f.first.getByLabel('Window end (ms)',{exact:true}).fill('50');await expect(range).toHaveText('25 – 50 ms');
 const png=await downloaded(page,()=>f.first.getByRole('button',{name:'Download PNG',exact:true}).click());const metadata=await sharp(png.bytes).metadata();expect(metadata.width).toBe(2400);expect(metadata.height).toBe(1000);const crop=await sharp(png.bytes).extract({left:2275,top:155,width:10,height:10}).removeAlpha().raw().toBuffer();expect([...crop].filter(v=>v<60).length).toBeGreaterThan(5);
 const original=await downloaded(page,()=>f.first.getByRole('button',{name:'Download original',exact:true}).click());expect(original.name).toBe('same.xlsx');expect(original.bytes).toEqual(f.excel);
 const archive=await downloaded(page,()=>page.getByRole('button',{name:'Download ZIP',exact:true}).click());expect(archive.name).not.toMatch(/[/\\]/);const entries=unzipSync(archive.bytes),manifest=JSON.parse(strFromU8(entries['manifest.json']));expect(manifest.version).toBe(1);expect(manifest.files).toHaveLength(5);expect(manifest.waveforms).toHaveLength(2);expect(Object.keys(entries)).toHaveLength(10);expect(strFromU8(entries['text/content.txt'])).toBe(f.notes);expect(strFromU8(entries['README.md'])).toContain('EEG raw value');for(const w of manifest.waveforms){expect(w).toMatchObject({start:0,end:105,sampleCount:41,width:2400,height:1000});expect((await sharp(entries[w.path]).metadata()).width).toBe(2400);}const originals=manifest.files.map((file:{path:string})=>Buffer.from(entries[file.path]));for(const buffer of [f.excel,f.other,f.text,f.text2,f.image])expect(originals.some((original:Buffer)=>original.equals(buffer))).toBe(true);expect(new Set(manifest.files.map((file:{path:string})=>file.path)).size).toBe(5);await page.screenshot({path:'outputs/R6/detail-desktop.png',fullPage:true});
});
test('missing original stops ZIP with no partial download and retry succeeds',async({page})=>{await fixture(page);let downloads=0;page.on('download',()=>downloads++);await page.route('**/v0/b/**',route=>route.request().method()==='GET'&&route.request().url().includes('packs%2F')?route.abort():route.continue());await page.getByRole('button',{name:'Download ZIP',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Could not export'})).toBeVisible({timeout:20000});expect(downloads).toBe(0);await page.unroute('**/v0/b/**');const archive=await downloaded(page,()=>page.getByRole('button',{name:'Retry export',exact:true}).click());expect(Object.keys(unzipSync(archive.bytes))).toHaveLength(10);});
test('a concurrent version change stops download and requires reloading',async({page})=>{await fixture(page);const id=page.url().split('/').pop();if(!process.env.FIRESTORE_EMULATOR_HOST)throw new Error('Isolated emulator required');const app=adminApp({projectId:'demo-evertrace-test'},'r6-version-'+Date.now());let changed=false,downloads=0;page.on('download',()=>downloads++);try{await page.route('**/v0/b/**',async route=>{if(!changed&&route.request().method()==='GET'&&route.request().url().includes('packs%2F')){changed=true;const response=await route.fetch();await adminDb(app).doc('packs/'+id).update({version:2,textContent:'Concurrent version'});await route.fulfill({response});}else await route.continue();});await page.getByRole('button',{name:'Download ZIP',exact:true}).click();await expect(page.getByRole('alert')).toContainText('changed during export');expect(downloads).toBe(0);await page.unroute('**/v0/b/**');await page.getByRole('button',{name:'Reload skill pack',exact:true}).click();await expect(page.getByText('Concurrent version',{exact:true})).toBeVisible();const result=await downloaded(page,()=>page.getByRole('button',{name:'Download ZIP',exact:true}).click());expect(JSON.parse(strFromU8(unzipSync(result.bytes)['manifest.json'])).version).toBe(2);}finally{await deleteAdmin(app);}});
test('PNG encoder failure cannot deliver an incomplete ZIP',async({page})=>{await fixture(page);let downloads=0;page.on('download',()=>downloads++);await page.evaluate(()=>{HTMLCanvasElement.prototype.toBlob=function(callback){callback(null);};});await page.getByRole('button',{name:'Download ZIP',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Could not export');expect(downloads).toBe(0);});
test('Chinese mobile supports touch zoom, pan, reset and localized archive metadata',async({page})=>{await page.setViewportSize({width:390,height:844});const f=await fixture(page);await page.getByRole('button',{name:'中文',exact:true}).click();const plot=f.first.getByRole('img',{name:'脑电预览',exact:true});await plot.scrollIntoViewIfNeeded();const box=(await plot.boundingBox())!,y=box.y+box.height/2;await plot.dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch',clientX:box.x+box.width*.3,clientY:y});await plot.dispatchEvent('pointerdown',{pointerId:2,pointerType:'touch',clientX:box.x+box.width*.7,clientY:y});await plot.dispatchEvent('pointermove',{pointerId:2,pointerType:'touch',clientX:box.x+box.width*.9,clientY:y});await plot.dispatchEvent('pointerup',{pointerId:2,pointerType:'touch'});await plot.dispatchEvent('pointerup',{pointerId:1,pointerType:'touch'});await expect(f.first.getByLabel('可见时间范围',{exact:true})).not.toHaveText('0 – 105 ms');await f.first.getByRole('button',{name:'向右平移',exact:true}).click();await f.first.getByRole('button',{name:'恢复全图',exact:true}).click();await expect(f.first.getByLabel('可见时间范围',{exact:true})).toHaveText('0 – 105 ms');const archive=await downloaded(page,()=>page.getByRole('button',{name:'下载 ZIP',exact:true}).click());const files=unzipSync(archive.bytes);expect(strFromU8(files['README.md'])).toContain('脑电原始值');expect(strFromU8(files['text/content.txt'])).toBe(f.notes);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'outputs/R6/detail-mobile.png',fullPage:true});});

test('large synthetic series parses and exports without blocking the page',async({page})=>{test.setTimeout(45000);await page.addInitScript(()=>{const probe={ticks:0,maxGap:0,last:performance.now()};(window as unknown as {r6Probe:typeof probe}).r6Probe=probe;setInterval(()=>{const now=performance.now();probe.maxGap=Math.max(probe.maxGap,now-probe.last);probe.last=now;probe.ticks++;},32);});await fixture(page,true);const before=await page.evaluate(()=>(window as unknown as {r6Probe:{ticks:number}}).r6Probe.ticks),started=Date.now(),archive=await downloaded(page,()=>page.getByRole('button',{name:'Download ZIP',exact:true}).click()),elapsedMs=Date.now()-started,probe=await page.evaluate(()=>(window as unknown as {r6Probe:{ticks:number;maxGap:number}}).r6Probe);expect(probe.ticks).toBeGreaterThan(before);expect(probe.maxGap).toBeLessThan(1500);const manifest=JSON.parse(strFromU8(unzipSync(archive.bytes)['manifest.json']));expect(manifest.waveforms).toHaveLength(2);expect(manifest.waveforms.every((w:{sampleCount:number})=>w.sampleCount===50000)).toBe(true);await writeFile('outputs/R6/browser-performance.json',JSON.stringify({synthetic:true,excelFiles:2,samplesEach:50000,archiveBytes:archive.bytes.length,exportMs:elapsedMs,maxMainThreadGapMs:probe.maxGap,ticksDuringExport:probe.ticks-before},null,2));});
test('another registered member downloads the complete pack through protected reads',async({page,browser})=>{const f=await fixture(page),url=page.url(),context=await browser.newContext(),other=await context.newPage();try{await other.goto(new URL('/register?returnTo=%2Fpacks',url).href);await other.getByLabel('Email',{exact:true}).fill('r6-other-'+crypto.randomUUID()+'@example.test');await other.getByLabel('Password',{exact:true}).fill('Evertrace-test-2026!');await other.getByLabel('Confirm password',{exact:true}).fill('Evertrace-test-2026!');await other.getByRole('button',{name:'Create account',exact:true}).click();await expect(other.getByRole('heading',{name:'Browse skill packs',exact:true})).toBeVisible();await other.goto(url);await expect(other.getByRole('heading',{name:f.title,exact:true})).toBeVisible();await expect(other.getByRole('link',{name:'Edit skill pack',exact:true})).toHaveCount(0);const archive=await downloaded(other,()=>other.getByRole('button',{name:'Download ZIP',exact:true}).click());const entries=unzipSync(archive.bytes);expect(Object.keys(entries)).toHaveLength(10);expect(strFromU8(entries['text/content.txt'])).toBe(f.notes);}finally{await context.close();}});
test('cancel while waiting for an original stops promptly and a fresh retry is complete',async({page})=>{await fixture(page);let downloads=0,waiting=false,release:()=>void=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;});page.on('download',()=>downloads++);await page.route('**/v0/b/**',async route=>{if(route.request().method()==='GET'&&route.request().url().includes('packs%2F')){waiting=true;await gate;}await route.continue();});try{await page.getByRole('button',{name:'Download ZIP',exact:true}).click();await expect.poll(()=>waiting).toBe(true);await page.getByRole('button',{name:'Cancel export',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Export cancelled.');expect(downloads).toBe(0);}finally{release();await page.unrouteAll({behavior:'wait'});}const archive=await downloaded(page,()=>page.getByRole('button',{name:'Retry export',exact:true}).click());expect(Object.keys(unzipSync(archive.bytes))).toHaveLength(10);});

test('tiny time values retain a nonzero continuous range',async({page})=>{const f=await fixture(page,false,true);await expect(f.first.getByLabel('Visible time range',{exact:true})).toHaveText('0 – '+String(f.points.at(-1)![0])+' ms');await f.first.getByRole('button',{name:'Zoom in',exact:true}).click();const start=Number(await f.first.getByLabel('Window start (ms)',{exact:true}).inputValue()),end=Number(await f.first.getByLabel('Window end (ms)',{exact:true}).inputValue());expect(end).toBeGreaterThan(start);expect(end-start).toBeLessThan(1.05e-7);});
