import { expect, test, type Page } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';
test.use({reducedMotion:'reduce'});
async function register(page:Page,admin=false){const email=randomUUID()+'@example.test';await page.goto('/register');await page.getByLabel('Name',{exact:true}).fill('R8 '+email.slice(0,8));await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('Evertrace-test-2026!');await page.getByLabel('Confirm password',{exact:true}).fill('Evertrace-test-2026!');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.getByRole('heading',{name:'Browse skill packs',exact:true})).toBeVisible();if(admin){const app=initializeApp({projectId:'demo-evertrace-test'},randomUUID());try{const user=await getAuth(app).getUserByEmail(email);await getFirestore(app).doc('users/'+user.uid).update({role:'admin'});await expect(page.getByText('Administrator',{exact:true})).toBeVisible();}finally{await deleteApp(app);}}return email;}
const row=(page:Page,email:string)=>page.getByRole('article').filter({has:page.getByText(email,{exact:true})});
test('admin promotes and demotes with confirmation; both accounts update access immediately',async({page,browser})=>{const emailAdmin=await register(page,true),context=await browser.newContext(),target=await context.newPage();try{const email=await register(target);await target.goto('/admin/members');await expect(target.getByRole('heading',{name:'Access denied',exact:true})).toBeVisible();await page.goto('/packs');await page.getByRole('link',{name:'Team members',exact:true}).click();await expect(page.getByRole('heading',{name:'Team members',exact:true})).toBeVisible();await row(page,email).getByRole('button',{name:'Make administrator',exact:true}).click();await expect(page.getByRole('dialog').getByRole('button',{name:'Confirm role change',exact:true})).toBeDisabled();await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();await expect(row(page,email).getByText('Member',{exact:true})).toBeVisible();await row(page,email).getByRole('button',{name:'Make administrator',exact:true}).click();await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('dialog').getByRole('button',{name:'Confirm role change',exact:true}).click();await expect(row(page,email).getByText('Administrator',{exact:true})).toBeVisible();await expect(target.getByRole('heading',{name:'Team members',exact:true})).toBeVisible();await row(page,email).getByRole('button',{name:'Remove administrator',exact:true}).click();await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('dialog').getByRole('button',{name:'Confirm role change',exact:true}).click();await expect(row(page,email).getByText('Member',{exact:true})).toBeVisible();await expect(target.getByRole('heading',{name:'Access denied',exact:true})).toBeVisible();await expect(row(page,emailAdmin).getByText('Administrator',{exact:true})).toBeVisible();}finally{await context.close();}});
test('member list remains denied to ordinary accounts after reload',async({page})=>{await register(page);await expect(page.getByRole('link',{name:'Team members',exact:true})).toHaveCount(0);await page.goto('/admin/members');await expect(page.getByRole('heading',{name:'Access denied',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Access denied',exact:true})).toBeVisible();});
test('failed role request retries without false success; mobile Chinese shows role controls',async({page,browser})=>{await register(page,true);const context=await browser.newContext(),target=await context.newPage();try{const email=await register(target);await page.goto('/admin/members');await row(page,email).getByRole('button',{name:'Make administrator',exact:true}).click();await page.getByRole('dialog').getByRole('checkbox').check();await page.route('**/setMemberRole',route=>route.abort());await page.getByRole('dialog').getByRole('button',{name:'Confirm role change',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();await page.unroute('**/setMemberRole');await page.getByRole('dialog').getByRole('button',{name:'Confirm role change',exact:true}).click();await expect(row(page,email).getByText('Administrator',{exact:true})).toBeVisible();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'中文',exact:true}).click();await expect(page.getByRole('heading',{name:'团队成员',exact:true})).toBeVisible();await row(page,email).getByRole('button',{name:'取消管理员',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('普通成员');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'outputs/R8/members-mobile.png'});await page.getByRole('dialog').getByRole('checkbox').check();await page.getByRole('dialog').getByRole('button',{name:'确认角色变更',exact:true}).click();await expect(row(page,email).getByText('普通成员',{exact:true})).toBeVisible();}finally{await context.close();}});
test('the only administrator sees last-admin protection and cannot remove their role',async({page})=>{const email=await register(page,true),app=initializeApp({projectId:'demo-evertrace-test'},randomUUID()),db=getFirestore(app),user=await getAuth(app).getUserByEmail(email),others=(await db.collection('users').where('role','==','admin').get()).docs.filter(d=>d.id!==user.uid);try{const b=db.batch();for(const d of others)b.update(d.ref,{role:'member'});b.set(db.doc('system/team'),{adminCount:1});await b.commit();await page.goto('/admin/members');await expect(row(page,email).getByText('Last administrator',{exact:true})).toBeVisible();await expect(row(page,email).getByRole('button',{name:'Remove administrator',exact:true})).toBeDisabled();}finally{const b=db.batch();for(const d of others)b.update(d.ref,{role:'admin'});b.set(db.doc('system/team'),{adminCount:others.length+1});await b.commit();await deleteApp(app);}});
