import { expect, test, type Page } from '@playwright/test';
import { workbook } from '../fixtures/workbooks.mjs';
test.use({reducedMotion:'reduce'});
const password='Evertrace-test-2026!';
async function register(page:Page){await page.goto('/register?returnTo=%2Fpacks%2Fnew');await page.getByLabel('Name',{exact:true}).fill('R3 researcher');const email=`r3-${Date.now()}-${Math.random()}@example.test`;await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByLabel('Confirm password',{exact:true}).fill(password);await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.getByRole('heading',{name:'Create a skill pack',exact:true})).toBeVisible();return email;}
async function fill(page:Page,source:'notes'|'txt'|'both'='notes'){const title=`R3 practice ${Date.now()}`;await page.getByLabel('Title',{exact:true}).fill(title);await page.getByLabel('New category',{exact:true}).fill('R3 category '+Date.now());await page.getByRole('button',{name:'Add category',exact:true}).click();await expect(page.getByText('Category created and selected.',{exact:true})).toBeVisible();if(source!=='txt')await page.getByLabel('Notes',{exact:true}).fill('Synthetic direct notes <script>alert(1)</script>');if(source!=='notes')await page.getByLabel('Text file',{exact:true}).setInputFiles({name:'notes.txt',mimeType:'text/plain',buffer:Buffer.from('\ufeff合成 TXT <b>plain text</b>')});await page.getByLabel('EEG Excel',{exact:true}).setInputFiles({name:'synthetic.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(await workbook())});await expect(page.getByRole('img',{name:'EEG preview'})).toBeVisible();return title;}
test('notes-only save, refresh, listing and a second member read the complete pack',async({page,browser})=>{await register(page);const title=await fill(page);await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page).toHaveURL(/\/packs\/[a-f0-9]{64}$/);const url=page.url();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();await expect(page.getByText('Synthetic direct notes <script>alert(1)</script>',{exact:true})).toBeVisible();await expect(page.getByRole('img',{name:'EEG preview'})).toBeVisible();await page.reload();await expect(page.getByRole('img',{name:'EEG preview'})).toBeVisible();await page.getByRole('link',{name:'Browse skill packs',exact:true}).click();await expect(page.getByRole('link',{name:title,exact:true})).toBeVisible();const context=await browser.newContext(),other=await context.newPage();try{await register(other);await other.goto(url);await expect(other.getByRole('heading',{name:title,exact:true})).toBeVisible();await expect(other.getByRole('img',{name:'EEG preview'})).toBeVisible();await other.getByRole('button',{name:'Sign out',exact:true}).click();await expect(other).toHaveURL(/\/login/);}finally{await context.close();}});
test('TXT alone satisfies save and file contents are plain text in detail',async({page})=>{await register(page);const title=await fill(page,'txt');await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();await expect(page.getByText('合成 TXT <b>plain text</b>',{exact:true})).toBeVisible();await expect(page.getByRole('img',{name:'EEG preview'})).toBeVisible();});
test('both text sources remain visible and Chinese mobile detail fits',async({page})=>{await page.setViewportSize({width:390,height:844});await register(page);const title=await fill(page,'both');await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();await page.getByRole('button',{name:'中文',exact:true}).click();await expect(page.getByText('合成 TXT <b>plain text</b>',{exact:true})).toBeVisible();await expect(page.getByRole('img',{name:'脑电预览'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'outputs/R3/detail-mobile.png',fullPage:true});});
test('save failure retains the form and successful uploads can be retried',async({page})=>{await register(page);const title=await fill(page,'both');await page.route('**/savePack',route=>route.abort());await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Could not save');await expect(page.getByLabel('Title',{exact:true})).toHaveValue(title);await expect(page.getByRole('img',{name:'EEG preview'})).toBeVisible();expect(await page.locator('#pack-text').evaluate((input:HTMLInputElement)=>input.files?.[0]?.name)).toBe('notes.txt');await page.unroute('**/savePack');await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();});
test('upload network failure never publishes and retry keeps selected files',async({page})=>{await register(page);const title=await fill(page);await page.route('**/v0/b/**',route=>route.request().method()==='POST'?route.abort():route.continue());await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Could not upload',{timeout:15000});await expect(page.getByLabel('Title',{exact:true})).toHaveValue(title);await page.unroute('**/v0/b/**');await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();});
test('missing detail has an explicit state without fabricated data',async({page})=>{await register(page);await page.goto('/packs/missing-r3');await expect(page.getByRole('heading',{name:'Skill pack not found',exact:true})).toBeVisible();await expect(page.getByRole('img',{name:'EEG preview'})).toHaveCount(0);});

test('a committed save with a lost response is recovered without reupload or duplicate listing',async({page})=>{await register(page);const title=await fill(page);await page.route('**/savePack',async route=>{await route.fetch();await route.abort();});await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Could not save');await page.unroute('**/savePack');await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();await page.getByRole('link',{name:'Browse skill packs',exact:true}).click();await expect(page.getByRole('link',{name:title,exact:true})).toHaveCount(1);});
test('original file network failure shows retry and recovers the waveform',async({page})=>{await register(page);const title=await fill(page);await page.route('**/v0/b/**',route=>route.request().method()==='GET'&&route.request().url().includes('packs%2F')?route.abort():route.continue());await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();await expect(page.getByRole('alert')).toContainText('Could not load this file',{timeout:15000});await page.unroute('**/v0/b/**');await page.getByRole('button',{name:'Retry file',exact:true}).click();await expect(page.getByRole('img',{name:'EEG preview'})).toBeVisible();});
test('save locks inputs and double clicks send only one save request',async({page})=>{await register(page);const title=await fill(page);let calls=0;await page.route('**/savePack',async route=>{calls++;await expect(page.getByLabel('Title',{exact:true})).toBeDisabled();await route.continue();});await page.getByRole('button',{name:'Save skill pack',exact:true}).dblclick();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();expect(calls).toBe(1);await expect(page.getByRole('img',{name:'EEG preview'})).toBeVisible();await page.screenshot({path:'outputs/R3/detail-desktop.png',fullPage:true});});

test('signed-out detail link returns to that pack after sign-in',async({page})=>{const email=await register(page),title=await fill(page);await page.getByRole('button',{name:'Save skill pack',exact:true}).click();await expect(page).toHaveURL(/\/packs\/[a-f0-9]{64}$/);const url=page.url();await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.goto(url);await expect(page.getByRole('heading',{name:'Sign in',exact:true})).toBeVisible();await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(url);await expect(page.getByRole('img',{name:'EEG preview'})).toBeVisible();});
