import {expect,test,type Page} from '@playwright/test';
import {initializeApp as adminApp,deleteApp as deleteAdmin} from 'firebase-admin/app';
import {getAuth as adminAuth} from 'firebase-admin/auth';
import {getFirestore as adminDb,Timestamp} from 'firebase-admin/firestore';
import {randomUUID} from 'node:crypto';
test.use({reducedMotion:'reduce'});
async function fixture(page:Page){await page.goto('/register?returnTo=%2Fpacks');const email='r5-'+randomUUID()+'@example.test';await page.getByLabel('Name',{exact:true}).fill('R5 member');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('Evertrace-test-2026!');await page.getByLabel('Confirm password',{exact:true}).fill('Evertrace-test-2026!');await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page.getByRole('heading',{name:'Browse skill packs',exact:true})).toBeVisible();if(!process.env.FIRESTORE_EMULATOR_HOST||!process.env.FIREBASE_AUTH_EMULATOR_HOST)throw new Error('Isolated emulator required');const app=adminApp({projectId:'demo-evertrace-test'},randomUUID());try{const db=adminDb(app),user=await adminAuth(app).getUserByEmail(email),tag='R5 '+randomUUID().slice(0,8),categories=[randomUUID(),randomUUID()],batch=db.batch();for(let i=0;i<2;i++)batch.set(db.doc('categories/'+categories[i]),{name:tag+' '+(i?'Craft':'Focus'),status:'active',packCount:0});for(let i=0;i<43;i++){const title=tag+' '+String(i).padStart(2,'0');batch.set(db.doc('packs/'+randomUUID()),{title,titleSearch:title.toLowerCase(),ownerId:i%2?user.uid:'synthetic-other',ownerName:i%2?'R5 member':'Other synthetic member',categoryId:categories[i%3?0:1],createdAt:Timestamp.fromMillis(1700000000000+i*1000),status:'ready',version:1,textContent:'Synthetic list fixture'});}await batch.commit();await page.reload();return {tag,categories,email};}finally{await deleteAdmin(app);}}
async function search(page:Page,value:string){await page.getByLabel('Title prefix',{exact:true}).fill(value);await page.getByRole('button',{name:'Search',exact:true}).click();await expect.poll(()=>new URL(page.url()).searchParams.get('q')).toBe(value.trim());}
test('prefix, category and my packs combine; URL refresh and clear preserve correct results',async({page})=>{const f=await fixture(page);await search(page,f.tag.toUpperCase());await expect(page.locator('.pack-list li')).toHaveCount(20);await expect(page.locator('.pack-list li').first()).toContainText(f.tag+' 00');await page.getByLabel('Filter category',{exact:true}).selectOption(f.categories[0]);await page.getByLabel('Show',{exact:true}).selectOption('mine');await expect(page.locator('.pack-list li')).toHaveCount(14);for(const row of await page.locator('.pack-list li').allTextContents()){expect(row).toContain(f.tag+' Focus');expect(row).toContain('R5 member');expect(row).not.toContain('Other synthetic member');}await page.reload();await expect(page.getByLabel('Show',{exact:true})).toHaveValue('mine');await expect(page.locator('.pack-list li')).toHaveCount(14);await page.getByRole('button',{name:'Clear filters',exact:true}).click();await expect(page.getByLabel('Title prefix',{exact:true})).toHaveValue('');await expect(page.getByLabel('Show',{exact:true})).toHaveValue('all');await expect(page.locator('.pack-list li').first()).not.toContainText(f.tag+' 00');});
test('three pages append without duplicates; changing scope resets the cursor and rows',async({page})=>{const f=await fixture(page);await search(page,f.tag);await expect(page.locator('.pack-list li')).toHaveCount(20);await page.getByRole('button',{name:'Load more',exact:true}).dblclick();await expect(page.locator('.pack-list li')).toHaveCount(40);await page.getByRole('button',{name:'Load more',exact:true}).click();await expect(page.locator('.pack-list li')).toHaveCount(43);await expect(page.getByRole('button',{name:'Load more',exact:true})).toHaveCount(0);const names=await page.locator('.pack-list li>a').allTextContents();expect(new Set(names).size).toBe(43);await page.getByLabel('Show',{exact:true}).selectOption('mine');await expect(page.locator('.pack-list li')).toHaveCount(20);await page.getByRole('button',{name:'Load more',exact:true}).click();await expect(page.locator('.pack-list li')).toHaveCount(21);await expect(page.getByRole('button',{name:'Load more',exact:true})).toHaveCount(0);});
test('rapid filter change never mixes old pages; explicit no matches can be cleared',async({page})=>{const f=await fixture(page);await search(page,f.tag);await expect(page.locator('.pack-list li')).toHaveCount(20);await page.getByRole('button',{name:'Load more',exact:true}).click();await page.getByLabel('Filter category',{exact:true}).selectOption(f.categories[1]);await expect(page.locator('.pack-list li')).toHaveCount(15);for(const row of await page.locator('.pack-list li').allTextContents())expect(row).toContain(f.tag+' Craft');await search(page,'does-not-exist-'+randomUUID());await expect(page.getByText('No skill packs match these filters.',{exact:true})).toBeVisible();await expect(page.locator('.pack-list li')).toHaveCount(0);await page.getByRole('button',{name:'Clear filters',exact:true}).click();await expect(page.locator('.pack-list li')).toHaveCount(20);});
test('Chinese mobile filters fit and title prefix stays in its original language',async({page})=>{await page.setViewportSize({width:390,height:844});const f=await fixture(page);await page.getByRole('button',{name:'中文',exact:true}).click();await page.getByLabel('标题前缀',{exact:true}).fill(f.tag);await page.getByRole('button',{name:'搜索',exact:true}).click();await page.getByLabel('显示范围',{exact:true}).selectOption('mine');await expect(page.locator('.pack-list li')).toHaveCount(20);await expect(page.getByLabel('标题前缀',{exact:true})).toHaveValue(f.tag);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'outputs/R5/list-mobile.png',fullPage:true});});
test('network failure while paging keeps loaded rows and retry appends once',async({page,context})=>{test.setTimeout(45000);const f=await fixture(page);await search(page,f.tag);await expect(page.locator('.pack-list li')).toHaveCount(20);await expect(page.locator('.pack-list li').first()).toContainText(f.tag+' 00');await expect(page.getByRole('button',{name:'Load more',exact:true})).toBeEnabled();await context.setOffline(true);await page.getByRole('button',{name:'Load more',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Could not load skill packs',{timeout:20000});await expect(page.locator('.pack-list li')).toHaveCount(20);await context.setOffline(false);await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.locator('.pack-list li')).toHaveCount(40);expect(new Set(await page.locator('.pack-list li>a').allTextContents()).size).toBe(40);});

test('filtered list survives a sign-out and sign-in redirect',async({page})=>{const f=await fixture(page),target='/packs?q='+encodeURIComponent(f.tag)+'&category='+f.categories[0]+'&scope=mine';await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.goto(target);await expect.poll(()=>new URL(page.url()).searchParams.get('returnTo')).toBe(target);await page.getByLabel('Email',{exact:true}).fill(f.email);await page.getByLabel('Password',{exact:true}).fill('Evertrace-test-2026!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByLabel('Title prefix',{exact:true})).toHaveValue(f.tag);await expect(page.getByLabel('Filter category',{exact:true})).toHaveValue(f.categories[0]);await expect(page.getByLabel('Show',{exact:true})).toHaveValue('mine');await expect(page.locator('.pack-list li')).toHaveCount(14);});
