import {getDocFromServer,doc} from 'firebase/firestore';
import {getBytes,ref} from 'firebase/storage';
import {db,storage} from '../app/legacy-firebase';
import {EXPORT_LIMITS,type ExportDependencies,type ExportPack} from './export-pack';
import {parseEegInWorker} from './eeg-worker';
import {displayEnvelope} from './waveform';
import type {EegResult} from '@evertrace/shared';
export const digestBytes=async(bytes:Uint8Array)=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes.slice().buffer))].map(b=>b.toString(16).padStart(2,'0')).join('');
export function renderFullPng(result:EegResult,name:string,language:string,signal:AbortSignal):Promise<Uint8Array>{
 signal.throwIfAborted();if(!result.ok||!result.points||!result.summary)throw new Error('exportInvalid');const {summary,points}=result,canvas=document.createElement('canvas');canvas.width=EXPORT_LIMITS.width;canvas.height=EXPORT_LIMITS.height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('exportFailed');
 const zh=language.startsWith('zh'),left=120,right=2280,top=160,bottom=840,span=summary.max-summary.min||1;ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#111';ctx.font='32px sans-serif';ctx.fillText(name,left,55,right-left);ctx.font='25px sans-serif';ctx.fillText(zh?'单通道 · 脑电原始值（设备原始数值，无物理单位）':'Channel 1 · EEG raw value (device raw values, without a physical unit)',left,105);
 ctx.strokeStyle='#ddd';ctx.lineWidth=1;for(let i=0;i<=4;i++){const y=top+(bottom-top)*i/4;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillStyle='#555';ctx.font='20px sans-serif';ctx.fillText((summary.max-(summary.max-summary.min)*i/4).toPrecision(5),5,y+7);}
 ctx.strokeStyle='#111';ctx.lineWidth=3;ctx.beginPath();for(const [i,p] of displayEnvelope(points,{start:summary.start,end:summary.end},EXPORT_LIMITS.width).entries()){const x=left+(p.time-summary.start)/(summary.end-summary.start)*(right-left),y=bottom-(p.value-summary.min)/span*(bottom-top);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);}ctx.stroke();ctx.fillStyle='#111';ctx.font='25px sans-serif';ctx.textAlign='left';ctx.fillText(summary.start+' ms',left,890);ctx.textAlign='right';ctx.fillText(summary.end+' ms',right,890);ctx.textAlign='center';ctx.fillText(zh?'时间（ms） · 完整时间范围':'Time (ms) · Full time range',1200,930);ctx.font='20px sans-serif';ctx.fillText(zh?'保留极值的显示抽样；精确数据以原 Excel 为准。':'Peak-preserving display sampling; exact data is in the original Excel.',1200,970);
 return new Promise((resolve,reject)=>{const timer=setTimeout(()=>finish(undefined,new Error('exportFailed')),EXPORT_LIMITS.pngMs);function finish(bytes?:Uint8Array,error?:unknown){clearTimeout(timer);signal.removeEventListener('abort',abort);canvas.width=0;canvas.height=0;if(error)reject(error);else resolve(bytes!);}function abort(){finish(undefined,signal.reason??new Error('exportCancelled'));}signal.addEventListener('abort',abort,{once:true});canvas.toBlob(blob=>{if(signal.aborted)return;if(!blob){finish(undefined,new Error('exportFailed'));return;}void blob.arrayBuffer().then(buffer=>finish(new Uint8Array(buffer)),error=>finish(undefined,error));},'image/png');});
}
function zipInWorker(entries:Record<string,Uint8Array>,signal:AbortSignal):Promise<Uint8Array>{signal.throwIfAborted();return new Promise((resolve,reject)=>{const worker=new Worker(new URL('../workers/archive.worker.ts',import.meta.url),{type:'module'}),timer=setTimeout(()=>finish(undefined,new Error('exportFailed')),EXPORT_LIMITS.zipMs);function finish(bytes?:Uint8Array,error?:unknown){clearTimeout(timer);signal.removeEventListener('abort',abort);worker.terminate();if(error)reject(error);else resolve(bytes!);}function abort(){finish(undefined,signal.reason??new Error('exportCancelled'));}signal.addEventListener('abort',abort,{once:true});worker.onmessage=(event:MessageEvent<{bytes?:Uint8Array;error?:string}>)=>finish(event.data.bytes,event.data.error?new Error(event.data.error):undefined);worker.onerror=()=>finish(undefined,new Error('exportFailed'));worker.postMessage(entries,Object.values(entries).map(bytes=>bytes.buffer));});}
export function browserExportDependencies(pack:ExportPack):ExportDependencies{return {readVersion:async()=>{const saved=await getDocFromServer(doc(db,'packs',pack.id));return saved.exists()?{version:saved.get('version'),status:saved.get('status')}:null;},readFile:async file=>new Uint8Array(await getBytes(ref(storage,file.storagePath),file.size)),digest:digestBytes,parseEeg:parseEegInWorker,renderPng:renderFullPng,zip:zipInWorker};}
export function deliverDownload(bytes:Uint8Array,name:string,type:string){const url=URL.createObjectURL(new Blob([bytes.slice().buffer],{type})),anchor=document.createElement('a');anchor.href=url;anchor.download=name;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
