import {ATTACHMENT_LIMITS,type EegResult,type StoredFile} from '@evertrace/shared';
export const EXPORT_LIMITS={width:2400,height:1000,bytes:64*1024*1024,zipMs:30000,pngMs:10000};
export type ExportPack={id:string;title:string;category:string;ownerName:string;ownerId:string;textContent:string;createdAt:string;version:number;status:string};
export type ExportProgress={phase:'reading'|'waveforms'|'packing';name?:string;done:number;total:number};
export type ExportDependencies={readVersion:()=>Promise<{version:number;status:string}|null>;readFile:(file:StoredFile)=>Promise<Uint8Array>;digest:(bytes:Uint8Array)=>Promise<string>;parseEeg:(bytes:Uint8Array,name:string,signal:AbortSignal)=>Promise<EegResult>;renderPng:(result:EegResult,name:string,language:string,signal:AbortSignal)=>Promise<Uint8Array>;zip:(entries:Record<string,Uint8Array>,signal:AbortSignal)=>Promise<Uint8Array>};
export function safeDownloadName(value:string,maxBytes=255){
 const cleaned=Array.from(value).filter(c=>c.charCodeAt(0)>=32&&c.charCodeAt(0)!==127).join('').replace(/[<>:"/\\|?*]/g,'_').replace(/\.\./g,'_').replace(/^[ .]+|[ .]+$/g,'')||'file';
 const name=/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/i.test(cleaned)?'_'+cleaned:cleaned,match=name.match(/\.[A-Za-z0-9]{1,12}$/),extension=match?.[0]??'',stem=extension?name.slice(0,-extension.length):name,encoder=new TextEncoder();let used=0,result='';
 for(const char of stem){const bytes=encoder.encode(char).length;if(used+bytes>maxBytes-encoder.encode(extension).length)break;used+=bytes;result+=char;}return (result.replace(/[ .]+$/g,'')||'file')+extension;
}
// SDK reads may keep retrying after cancellation; stop the export immediately and ignore their eventual result.
export function abortable<T>(promise:Promise<T>,signal:AbortSignal):Promise<T>{signal.throwIfAborted();return new Promise((resolve,reject)=>{const abort=()=>{signal.removeEventListener('abort',abort);reject(signal.reason??new Error('exportCancelled'));};signal.addEventListener('abort',abort,{once:true});promise.then(value=>{signal.removeEventListener('abort',abort);resolve(value);},error=>{signal.removeEventListener('abort',abort);reject(error);});});}
export async function assertExportVersion(pack:ExportPack,readVersion:ExportDependencies['readVersion'],signal:AbortSignal){signal.throwIfAborted();const live=await abortable(readVersion(),signal);signal.throwIfAborted();if(pack.status!=='ready'||!live||live.status!=='ready'||live.version!==pack.version)throw new Error('exportChanged');}
export async function verifiedOriginal(file:StoredFile,deps:Pick<ExportDependencies,'readFile'|'digest'>,signal:AbortSignal){signal.throwIfAborted();const bytes=await abortable(deps.readFile(file),signal);signal.throwIfAborted();if(bytes.length!==file.size||await deps.digest(bytes)!==file.sha256)throw new Error('exportIntegrity');signal.throwIfAborted();return bytes;}
function withId(name:string,id:string){const safe=safeDownloadName(name,240-id.length-2),dot=safe.lastIndexOf('.');return dot>0?safe.slice(0,dot)+'__'+id+safe.slice(dot):safe+'__'+id;}
export async function assemblePackExport(pack:ExportPack,files:StoredFile[],language:string,deps:ExportDependencies,signal:AbortSignal,progress:(value:ExportProgress)=>void){
 if(!/^[A-Za-z0-9_-]{1,100}$/.test(pack.id)||!files.length||files.length>ATTACHMENT_LIMITS.count||files.some(f=>!f.active||!['text','image','eeg'].includes(f.kind)||!Number.isSafeInteger(f.size)||f.size<=0||!/^[A-Za-z0-9_-]{1,100}$/.test(f.id))||new Set(files.map(f=>f.id)).size!==files.length||!files.some(f=>f.kind==='eeg'))throw new Error('exportInvalid');
 if(files.reduce((n,f)=>n+f.size,0)>ATTACHMENT_LIMITS.totalBytes)throw new Error('exportBudget');
 await assertExportVersion(pack,deps.readVersion,signal);const entries:Record<string,Uint8Array>={},manifestFiles:Record<string,unknown>[]=[],waveforms:Record<string,unknown>[]=[],encoder=new TextEncoder();let totalBytes=0;
 function add(path:string,bytes:Uint8Array){totalBytes+=bytes.length;if(totalBytes>EXPORT_LIMITS.bytes)throw new Error('exportBudget');entries[path]=bytes;}
 for(const [i,file] of files.entries()){
  progress({phase:'reading',name:file.originalName,done:i,total:files.length});const bytes=await verifiedOriginal(file,deps,signal),folder=file.kind==='text'?'text':file.kind==='image'?'images':'eeg',path=folder+'/'+withId(file.originalName,file.id);add(path,bytes);manifestFiles.push({id:file.id,kind:file.kind,originalName:file.originalName,path,size:bytes.length,sha256:file.sha256,mediaType:file.mediaType});
  if(file.kind==='eeg'){
   progress({phase:'waveforms',name:file.originalName,done:i,total:files.length});const result=await deps.parseEeg(bytes,file.originalName,signal);signal.throwIfAborted();if(!result.ok||!result.points||!result.summary)throw new Error('exportInvalid');const png=await deps.renderPng(result,file.originalName,language,signal);signal.throwIfAborted();const pngPath='waveforms/'+withId(file.originalName.replace(/\.xlsx$/i,''),file.id)+'.png';add(pngPath,png);waveforms.push({fileId:file.id,path:pngPath,sha256:await deps.digest(png),start:result.summary.start,end:result.summary.end,sampleCount:result.summary.count,width:EXPORT_LIMITS.width,height:EXPORT_LIMITS.height,channel:'Channel 1',timeUnit:'ms',valueUnit:'unitless device raw value',displaySampling:'temporal min/max envelope; original Excel is authoritative'});
  }
 }
 if(!pack.textContent.trim()&&!files.some(f=>f.kind==='text'))throw new Error('exportInvalid');if(pack.textContent.trim())add('text/content.txt',encoder.encode(pack.textContent));
 const exportedAt=new Date().toISOString(),chinese=language.startsWith('zh');const readme=chinese?`技能包：${pack.title}\n分类：${pack.category}\n创建者：${pack.ownerName}\n创建时间：${pack.createdAt}\n技能包 ID：${pack.id}\n版本：${pack.version}\n导出时间：${exportedAt}\n\n单通道；时间（ms）；脑电原始值（设备原始数值，无物理单位）。\n每份 PNG 包含完整时间范围，与页面缩放无关。采用保留极值的显示抽样；有限分辨率图像不是逐点数据替代，精确数据以原 Excel 为准。\n原件和正文保留原文；文件 ID 后缀避免重名覆盖。校验值和文件对应见 manifest.json。\n`:`Skill pack: ${pack.title}\nCategory: ${pack.category}\nCreator: ${pack.ownerName}\nCreated: ${pack.createdAt}\nPack ID: ${pack.id}\nVersion: ${pack.version}\nExported: ${exportedAt}\n\nChannel 1; Time (ms); EEG raw value (device raw values, without a physical unit).\nEvery PNG covers the full time range, independent of page zoom. Peak-preserving display sampling is used; finite-resolution images do not replace exact samples in the original Excel.\nOriginals and notes retain their original language. File ID suffixes prevent name collisions. See manifest.json for checksums and file correspondence.\n`;
 add('README.md',encoder.encode(readme));add('manifest.json',encoder.encode(JSON.stringify({packId:pack.id,title:pack.title,category:pack.category,ownerName:pack.ownerName,ownerId:pack.ownerId,createdAt:pack.createdAt,version:pack.version,exportedAt,language,files:manifestFiles,waveforms},null,2)));
 await assertExportVersion(pack,deps.readVersion,signal);progress({phase:'packing',done:files.length,total:files.length});const bytes=await deps.zip(entries,signal);await assertExportVersion(pack,deps.readVersion,signal);return {name:safeDownloadName(pack.title,249-pack.id.length-6)+'__'+pack.id+'.zip',bytes};
}
