import {useEffect,useId,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {useTranslation} from 'react-i18next';
import type {EegResult} from '@evertrace/shared';
import {clampWindow,zoomWindow,panWindow,nearestSample,displayEnvelope,type Sample} from '../services/waveform';
export function EegPreview({result}:{result:EegResult}){if(!result.ok||!result.points||!result.summary)return null;return <Waveform points={result.points} summary={result.summary}/>;}
function Waveform({points,summary}:{points:Sample[];summary:NonNullable<EegResult['summary']>}){
 const {t}=useTranslation(),full={start:summary.start,end:summary.end},[window,setWindow]=useState(full),[sample,setSample]=useState<Sample|null>(null),[visible,setVisible]=useState(false),figure=useRef<HTMLElement|null>(null),svg=useRef<SVGSVGElement|null>(null),pointers=useRef(new Map<number,{x:number;y:number}>()),clip=useId().replace(/[^a-zA-Z0-9_-]/g,'');
 useEffect(()=>{setWindow({start:summary.start,end:summary.end});setSample(null);},[points,summary.start,summary.end]);
 useEffect(()=>{if(!figure.current)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setVisible(true);observer.disconnect();}},{rootMargin:'200px'});observer.observe(figure.current);return()=>observer.disconnect();},[]);
 useEffect(()=>{const element=svg.current;if(!element)return;function wheel(event:WheelEvent){event.preventDefault();const box=element!.getBoundingClientRect(),anchor=Math.max(0,Math.min(1,((event.clientX-box.x)/box.width*790-40)/710));setWindow(previous=>zoomWindow(previous,{start:summary.start,end:summary.end},event.deltaY<0?.8:1.25,anchor));}element.addEventListener('wheel',wheel,{passive:false});return()=>element.removeEventListener('wheel',wheel);},[summary.start,summary.end]);
 const path=useMemo(()=>{const span=summary.max-summary.min||1;return (visible?displayEnvelope(points,window,800):[]).map((p,i)=>`${i?'L':'M'}${40+(p.time-window.start)/(window.end-window.start)*710},${200-(p.value-summary.min)/span*170}`).join(' ');},[points,summary.min,summary.max,window,visible]);
 function fraction(x:number){const box=svg.current!.getBoundingClientRect();return Math.max(0,Math.min(1,((x-box.x)/box.width*790-40)/710));}
 function down(event:ReactPointerEvent<SVGSVGElement>){if(event.pointerType==='mouse'&&event.button!==0)return;pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});try{event.currentTarget.setPointerCapture(event.pointerId);}catch{/* Synthetic events need no capture. */}setSample(nearestSample(points,window.start+fraction(event.clientX)*(window.end-window.start)));}
 function move(event:ReactPointerEvent<SVGSVGElement>){const map=pointers.current,prior=map.get(event.pointerId);if(prior){const before=[...map.values()];map.set(event.pointerId,{x:event.clientX,y:event.clientY});if(map.size===1){const pixels=svg.current!.getBoundingClientRect().width*710/790;setWindow(previous=>panWindow(previous,full,(prior.x-event.clientX)/pixels*(previous.end-previous.start)));}else if(map.size===2){const after=[...map.values()],distance=(p:{x:number;y:number}[])=>Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),oldDistance=distance(before),newDistance=distance(after);if(oldDistance&&newDistance)setWindow(previous=>zoomWindow(previous,full,oldDistance/newDistance,fraction((after[0].x+after[1].x)/2)));}}setSample(nearestSample(points,window.start+fraction(event.clientX)*(window.end-window.start)));}
 const shown=(n:number)=>String(n);
 return <figure className="eeg-preview" ref={figure}><figcaption><strong>{t('form.preview')}</strong><span>{t('form.samples',{count:summary.count})}</span></figcaption><svg ref={svg} className="eeg-interactive" viewBox="0 0 790 245" role="img" aria-label={t('form.preview')} onPointerDown={down} onPointerMove={move} onPointerUp={event=>pointers.current.delete(event.pointerId)} onPointerCancel={event=>pointers.current.delete(event.pointerId)} onLostPointerCapture={event=>pointers.current.delete(event.pointerId)}><defs><clipPath id={'wave-'+clip}><rect x="40" y="25" width="710" height="185"/></clipPath></defs><line x1="40" y1="210" x2="750" y2="210" stroke="#aaa"/><path d={path} clipPath={'url(#wave-'+clip+')'} fill="none" stroke="currentColor" strokeWidth="1.4"/><text x="40" y="233">{shown(window.start)} ms</text><text x="750" y="233" textAnchor="end">{shown(window.end)} ms</text><text x="40" y="18">{t('form.rawValues')} · {summary.min} … {summary.max}</text></svg>
 <div className="wave-controls"><button className="button" type="button" onClick={()=>setWindow(zoomWindow(window,full,.5))}>{t('wave.zoomIn')}</button><button className="button" type="button" onClick={()=>setWindow(zoomWindow(window,full,2))}>{t('wave.zoomOut')}</button><button className="button" type="button" onClick={()=>setWindow(panWindow(window,full,-(window.end-window.start)/4))}>{t('wave.panLeft')}</button><button className="button" type="button" onClick={()=>setWindow(panWindow(window,full,(window.end-window.start)/4))}>{t('wave.panRight')}</button><button className="button" type="button" onClick={()=>{setWindow(full);setSample(null);}}>{t('wave.reset')}</button></div>
 <div className="wave-bounds"><label>{t('wave.start')}<input type="number" step="any" min={full.start} max={full.end} value={shown(window.start)} onChange={event=>{const start=Number(event.target.value);if(Number.isFinite(start))setWindow(clampWindow({...window,start},full));}}/></label><label>{t('wave.end')}<input type="number" step="any" min={full.start} max={full.end} value={shown(window.end)} onChange={event=>{const end=Number(event.target.value);if(Number.isFinite(end))setWindow(clampWindow({...window,end},full));}}/></label></div>
 <div className="wave-readouts"><output aria-label={t('wave.range')}>{shown(window.start)} – {shown(window.end)} ms</output><output aria-label={t('wave.sample')}>{sample?String(sample.time)+' ms · '+String(sample.value):t('wave.readHint')}</output></div><p className="field-note">{t('wave.gestures')}</p>{points.length>800&&<p className="field-note">{t('wave.sampling')}</p>}<p>{t('form.previewNote')}</p></figure>;
}
