import { getAuth } from 'firebase-admin/auth';
import { FieldValue, Timestamp, getFirestore, type Transaction, type DocumentSnapshot } from 'firebase-admin/firestore';
import { getStorage } from 'firebase-admin/storage';
import { onCall, HttpsError } from 'firebase-functions/v2/https';
import { createHash, randomUUID } from 'node:crypto';
import sharp from 'sharp';
import { PREVIEW_LIMITS, ATTACHMENT_LIMITS, UPLOAD_POLICY, attachmentMediaType, imageFormat, checkImageHeader, readFunctionsRegion, validateEeg, validateText, validatePackInput, type BeginUploadInput, type PlannedFile, type StoredFile, type UploadSession } from '@evertrace/shared';
const region=readFunctionsRegion(process.env);
const db=()=>getFirestore(),bucket=()=>getStorage().bucket(process.env.EVERTRACE_STORAGE_BUCKET||undefined);
const sha=(bytes:Uint8Array|string)=>createHash('sha256').update(bytes).digest('hex');
type Session=UploadSession&BeginUploadInput&{actorId:string;ownerName:string;fingerprint:string;status:string;expiresAt:Timestamp;leaseUntil?:Timestamp;attempt?:string;cleanupPending?:boolean;retained:StoredFile[];cleanupPaths?:string[]};
function error(code:string,details:Record<string,unknown>={}){return new HttpsError('failed-precondition',code,{code,...details});}
function conflict(){return new HttpsError('aborted','The pack changed since it was opened.',{code:'versionConflict'});}
function id(value:unknown):string{if(typeof value!=='string'||! /^[A-Za-z0-9_-]{1,100}$/.test(value))throw new HttpsError('invalid-argument','Invalid identifier.');return value;}
async function account(uid:string|undefined){if(!uid)throw new HttpsError('unauthenticated','Sign in.');const user=await getAuth().getUser(uid);if(user.disabled)throw new HttpsError('permission-denied','Account unavailable.');return user;}
async function member(tx:Transaction,uid:string){const profile=await tx.get(db().doc('users/'+uid));if(!profile.exists||!['member','admin'].includes(profile.get('role')))throw new HttpsError('permission-denied','A member profile is required.');return profile;}
function editable(pack:DocumentSnapshot,profile:DocumentSnapshot,uid:string,version:number){if(!pack.exists||pack.get('status')!=='ready')throw error('packUnavailable');if(pack.get('ownerId')!==uid&&profile.get('role')!=='admin')throw new HttpsError('permission-denied','Only the creator or an administrator may edit.');if(pack.get('version')!==version)throw conflict();}
function parse(value:unknown):BeginUploadInput{
  const data=value as Partial<BeginUploadInput>;
  if(!data||typeof data!=='object'||Array.isArray(data)||typeof data.title!=='string'||typeof data.textContent!=='string'||!Array.isArray(data.filePlan)||data.filePlan.length>ATTACHMENT_LIMITS.count)throw new HttpsError('invalid-argument','Invalid upload plan.');
  const requestId=id(data.requestId),categoryId=id(data.categoryId),title=data.title.trim(),textContent=data.textContent;
  const filePlan=data.filePlan.map(file=>{
    const ext=file?.kind==='text'?/\.txt$/i:file?.kind==='eeg'?/\.xlsx$/i:/\.(jpg|jpeg|png|webp)$/i;
    const max=file?.kind==='text'?PREVIEW_LIMITS.textBytes:file?.kind==='eeg'?PREVIEW_LIMITS.excelBytes:ATTACHMENT_LIMITS.imageBytes;
    if(!file||!['text','eeg','image'].includes(file.kind)||typeof file.name!=='string'||file.name.length>160||!file.name.trim()||/[\\/:]/.test(file.name)||[...file.name].some(c=>c.charCodeAt(0)<32||c.charCodeAt(0)===127)||!ext.test(file.name)||!Number.isSafeInteger(file.size)||file.size<=0||file.size>max||typeof file.sha256!=='string'||!/^[a-f0-9]{64}$/.test(file.sha256))throw new HttpsError('invalid-argument','Invalid attachment.');
    return {kind:file.kind,name:file.name,size:file.size,sha256:file.sha256};
  });
  const base={requestId,title,categoryId,textContent,filePlan};
  if(data.packId!==undefined){const packId=id(data.packId);if(!Number.isSafeInteger(data.expectedVersion)||data.expectedVersion!<1||!Array.isArray(data.retainedFileIds)||data.retainedFileIds.length>ATTACHMENT_LIMITS.count)throw new HttpsError('invalid-argument','Invalid edit version or retained files.');const retainedFileIds=data.retainedFileIds.map(id);if(new Set(retainedFileIds).size!==retainedFileIds.length)throw new HttpsError('invalid-argument','Duplicate retained file.');return {...base,packId,expectedVersion:data.expectedVersion,retainedFileIds};}
  if(data.expectedVersion!==undefined||data.retainedFileIds?.length)throw new HttpsError('invalid-argument','An edit needs a pack.');
  validateMaterials(base,[]);return base;
}
function validateMaterials(input:BeginUploadInput,retained:StoredFile[]){const files=[...input.filePlan,...retained];if(files.length>ATTACHMENT_LIMITS.count||files.reduce((n,f)=>n+f.size,0)>ATTACHMENT_LIMITS.totalBytes)throw new HttpsError('invalid-argument','Attachment budget exceeded.',{code:'attachmentLimit'});const issues=validatePackInput({title:input.title,categoryId:input.categoryId,text:input.textContent,textFileValid:files.some(f=>f.kind==='text'),eegValid:files.some(f=>f.kind==='eeg')});if(issues.length)throw new HttpsError('invalid-argument','Required material is missing or too long.',{code:'validationFailed',issues});}
function response(s:Session):UploadSession{return {sessionId:s.sessionId,packId:s.packId,files:s.files,status:s.status,...(s.status==='committed'?{result:{packId:s.packId,cleanupPending:Boolean(s.cleanupPending)}}:{})};}
export const beginUpload=onCall({region},async request=>{
  const user=await account(request.auth?.uid),input=parse(request.data),fingerprint=sha(JSON.stringify(input)),sessionId=sha(user.uid+':'+input.requestId),packId=input.packId??sessionId,sessionRef=db().doc('uploadSessions/'+sessionId);
  return db().runTransaction(async tx=>{
    const [profile,saved,category]=await Promise.all([member(tx,user.uid),tx.get(sessionRef),tx.get(db().doc('categories/'+input.categoryId))]);
    if(saved.exists){const s=saved.data() as Session;if(s.actorId!==user.uid)throw new HttpsError('permission-denied','Upload owner mismatch.');if(s.fingerprint!==fingerprint)throw new HttpsError('already-exists','This request key has a different plan.',{code:'requestChanged'});if(['cancelled','expired'].includes(s.status)||s.expiresAt.toMillis()<=Date.now()&&s.status!=='committed')throw error('sessionExpired');if(s.expectedVersion&&s.status!=='committed')editable(await tx.get(db().doc('packs/'+packId)),profile,user.uid,s.expectedVersion);return response(s);}
    if(!category.exists||category.get('status')!=='active')throw error('categoryUnavailable');
    const retained:StoredFile[]=[];
    if(input.expectedVersion){const pack=await tx.get(db().doc('packs/'+packId));editable(pack,profile,user.uid,input.expectedVersion);for(const fileId of input.retainedFileIds!){const file=await tx.get(db().doc(`packs/${packId}/files/${fileId}`));if(!file.exists||file.get('active')!==true||pack.get('fileAccess')?.[fileId]?.active!==true)throw new HttpsError('invalid-argument','Invalid retained attachment.');retained.push({id:fileId,...file.data()} as StoredFile);}validateMaterials(input,retained);}
    const files=input.filePlan.map(file=>{const fileId=randomUUID(),ext=file.name.split('.').pop()!.toLowerCase();return {...file,id:fileId,mediaType:attachmentMediaType(file.kind,file.name),stagingPath:`staging/${user.uid}/${sessionId}/${fileId}.${ext}`,storagePath:`packs/${packId}/files/${fileId}.${ext}`};});
    const fileMap=Object.fromEntries(files.map(f=>[f.stagingPath.split('/').pop(),{size:f.size,mediaType:f.mediaType}]));
    const session:Session={...input,sessionId,packId,files,retained,fingerprint,actorId:user.uid,ownerName:profile.get('displayName')||user.email||'',status:'accepting',expiresAt:Timestamp.fromMillis(Date.now()+UPLOAD_POLICY.lifetimeMs)};
    tx.create(sessionRef,{...session,fileMap,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});return response(session);
  });
});
async function removePaths(sessionId:string,paths:string[]){let failed=false;for(const path of paths){try{const object=bucket().file(path);const [m]=await object.getMetadata();await object.delete({ifGenerationMatch:m.generation});}catch(e){if((e as {code?:number}).code!==404)failed=true;}}const job=db().doc('cleanupJobs/'+sessionId);if(failed)await job.set({sessionId,paths,status:'pending',lastError:'storageCleanup',updatedAt:FieldValue.serverTimestamp()},{merge:true});else await job.delete();return failed;}
async function cleanCommitted(session:Session){const pending=await removePaths(session.sessionId,session.cleanupPaths??session.files.map(f=>f.stagingPath));await db().runTransaction(async tx=>{const ref=db().doc('packs/'+session.packId),pack=await tx.get(ref);tx.update(db().doc('uploadSessions/'+session.sessionId),{cleanupPending:pending});if(pack.exists){const sessions={...(pack.get('cleanupSessions')??{})};if(pending)sessions[session.sessionId]=true;else delete sessions[session.sessionId];tx.update(ref,{cleanupSessions:sessions,cleanupPending:Object.keys(sessions).length>0});}});return {packId:session.packId,cleanupPending:pending};}
async function readOriginal(file:PlannedFile){const object=bucket().file(file.stagingPath);let metadata;try{[metadata]=await object.getMetadata();}catch(e){if((e as {code?:number}).code===404)throw error('uploadIncomplete',{file:file.name});throw e;}if(Number(metadata.size)!==file.size||metadata.contentType!==file.mediaType||metadata.contentEncoding&&metadata.contentEncoding!=='identity'||!metadata.generation)throw new HttpsError('invalid-argument','Uploaded file differs from plan.',{code:'fileChanged',file:file.name});const [bytes]=await bucket().file(file.stagingPath,{generation:metadata.generation}).download({start:0,end:file.size,decompress:false});if(bytes.length!==file.size||sha(bytes)!==file.sha256)throw new HttpsError('invalid-argument','Uploaded bytes differ from plan.',{code:'fileChanged',file:file.name});return {bytes,generation:metadata.generation};}
async function retainedIntact(files:StoredFile[]){for(const file of files){try{const [m]=await bucket().file(file.storagePath).getMetadata();if(String(m.generation)!==file.generation||Number(m.size)!==file.size||m.contentType!==file.mediaType||m.contentEncoding&&m.contentEncoding!=='identity')throw error('fileChanged',{file:file.originalName});}catch(e){if(e instanceof HttpsError)throw e;throw error('fileChanged',{file:file.originalName});}}}
async function checkImage(bytes:Buffer,name:string){const issues=checkImageHeader(bytes,name);if(issues.length)throw new HttpsError('invalid-argument','Invalid image.',{code:'validationFailed',issues});try{const image=sharp(bytes,{failOn:'warning',limitInputPixels:ATTACHMENT_LIMITS.imagePixels,animated:true}),m=await image.metadata();if(m.format!==imageFormat(name)||!m.width||!m.height||m.width*m.height>ATTACHMENT_LIMITS.imagePixels)throw new Error('format');await image.timeout({seconds:5}).raw().toBuffer();return {width:m.width,height:m.height,format:m.format};}catch{throw new HttpsError('invalid-argument','Image could not be decoded within limits.',{code:'validationFailed',issues:[{code:'imageInvalid',file:name}]});}}
export const savePack=onCall({region,memory:'1GiB',timeoutSeconds:120,concurrency:4},async request=>{
  const user=await account(request.auth?.uid),sessionId=id(request.data?.sessionId),sessionRef=db().doc('uploadSessions/'+sessionId),attempt=randomUUID();
  const session=await db().runTransaction(async tx=>{const profile=await member(tx,user.uid),saved=await tx.get(sessionRef);if(!saved.exists)throw error('sessionExpired');const s=saved.data() as Session;if(s.actorId!==user.uid)throw new HttpsError('permission-denied','Only the upload owner can save.');if(s.status==='committed')return s;if(['cancelled','expired'].includes(s.status)||s.expiresAt.toMillis()<=Date.now())throw error('sessionExpired');if(s.expectedVersion)editable(await tx.get(db().doc('packs/'+s.packId)),profile,user.uid,s.expectedVersion);const category=await tx.get(db().doc('categories/'+s.categoryId));if(!category.exists||category.get('status')!=='active')throw error('categoryUnavailable');if(s.status==='validating'&&(s.leaseUntil?.toMillis()??0)>Date.now())throw new HttpsError('aborted','Save in progress.',{code:'saveBusy'});if(!['accepting','validating'].includes(s.status))throw error('sessionExpired');tx.update(sessionRef,{status:'validating',attempt,leaseUntil:Timestamp.fromMillis(Date.now()+UPLOAD_POLICY.leaseMs),updatedAt:FieldValue.serverTimestamp()});return {...s,status:'validating',attempt};});
  if(session.status==='committed')return cleanCommitted(session);
  let committed:Session=session;
  try{
    const retained=session.retained??[];await retainedIntact(retained);validateMaterials(session,retained);
    const originals=[];
    for(const file of session.files){const original=await readOriginal(file);let extra:Partial<StoredFile>={};if(file.kind==='image')extra={imageSummary:await checkImage(original.bytes,file.name)};else{const result=file.kind==='eeg'?await validateEeg(original.bytes,file.name):validateText(original.bytes,file.name);if(!result.ok)throw new HttpsError('invalid-argument','File validation failed.',{code:'validationFailed',issues:result.issues});if(file.kind==='eeg'&&'summary' in result)extra={eegSummary:result.summary};}originals.push({file,...original,extra});}
    const added:StoredFile[]=[];
    for(const original of originals){const {file,bytes,generation,extra}=original,object=bucket().file(file.storagePath),[exists]=await object.exists();if(exists){const [existing]=await object.download();if(existing.length!==file.size||sha(existing)!==file.sha256)throw error('copyFailed',{file:file.name});}try{if(!exists)await object.save(bytes,{resumable:false,preconditionOpts:{ifGenerationMatch:0},metadata:{contentType:file.mediaType,metadata:{sha256:file.sha256,sourceGeneration:generation,sessionId,firebaseStorageDownloadTokens:''}}});}catch(e){if((e as {code?:number}).code!==412)throw e;const [existing]=await object.download();if(existing.length!==file.size||sha(existing)!==file.sha256)throw error('copyFailed',{file:file.name});}const [m]=await object.getMetadata();if(Number(m.size)!==file.size||m.contentType!==file.mediaType||m.metadata?.firebaseStorageDownloadTokens)throw error('copyFailed',{file:file.name});added.push({id:file.id,kind:file.kind,originalName:file.name,storagePath:file.storagePath,mediaType:file.mediaType,size:file.size,sha256:file.sha256,generation:String(m.generation),active:true,...extra});}
    for(const original of originals){const [m]=await bucket().file(original.file.stagingPath).getMetadata();if(m.generation!==original.generation)throw error('fileChanged',{file:original.file.name});}await retainedIntact(retained);await account(user.uid);
    const cleanupPaths=await db().runTransaction(async tx=>{
      const [profile,current,category]=await Promise.all([member(tx,user.uid),tx.get(sessionRef),tx.get(db().doc('categories/'+session.categoryId))]);if(current.get('status')!=='validating'||current.get('attempt')!==attempt||current.get('expiresAt').toMillis()<=Date.now())throw error('sessionExpired');if(!category.exists||category.get('status')!=='active')throw error('categoryUnavailable');
      const packRef=db().doc('packs/'+session.packId),old=session.expectedVersion?await tx.get(packRef):null;const removed:StoredFile[]=[];
      if(old){editable(old,profile,user.uid,session.expectedVersion!);const all=await tx.get(db().collection(`packs/${session.packId}/files`).where('active','==',true));for(const f of retained){const live=all.docs.find(d=>d.id===f.id);if(!live||live.get('generation')!==f.generation||live.get('sha256')!==f.sha256||old.get('fileAccess')?.[f.id]?.active!==true)throw conflict();}removed.push(...all.docs.filter(d=>!retained.some(f=>f.id===d.id)).map(d=>({id:d.id,...d.data()} as StoredFile)));if(old.get('categoryId')!==session.categoryId){const previous=await tx.get(db().doc('categories/'+old.get('categoryId')));if(!previous.exists||previous.get('status')!=='active')throw error('categoryUnavailable');}}
      const stamp=FieldValue.serverTimestamp(),stored=[...retained,...added],paths=[...session.files.map(f=>f.stagingPath),...removed.map(f=>f.storagePath)];
      const data={title:session.title,titleSearch:session.title.normalize('NFKC').toLowerCase(),categoryId:session.categoryId,textContent:session.textContent,status:'ready',version:(old?.get('version')??0)+1,uploadSessionId:sessionId,cleanupPending:true,cleanupSessions:{...(old?.get('cleanupSessions')??{}),[sessionId]:true},fileAccess:Object.fromEntries(stored.map(f=>[f.id,{active:true,storagePath:f.storagePath,size:f.size,mediaType:f.mediaType}])),textFileCount:stored.filter(f=>f.kind==='text').length,eegCount:stored.filter(f=>f.kind==='eeg').length,imageCount:stored.filter(f=>f.kind==='image').length,totalBytes:stored.reduce((n,f)=>n+f.size,0),updatedAt:stamp,updatedBy:user.uid};
      if(old)tx.update(packRef,data);else tx.create(packRef,{...data,ownerId:user.uid,ownerName:profile.get('displayName')||user.email||'',createdAt:stamp});for(const f of added)tx.create(db().doc(`packs/${session.packId}/files/${f.id}`),{...f,createdAt:stamp});for(const f of removed)tx.update(db().doc(`packs/${session.packId}/files/${f.id}`),{active:false,removedAt:stamp});if(!old||old.get('categoryId')!==session.categoryId){tx.update(db().doc('categories/'+session.categoryId),{packCount:FieldValue.increment(1),updatedAt:stamp});if(old)tx.update(db().doc('categories/'+old.get('categoryId')),{packCount:FieldValue.increment(-1),updatedAt:stamp});}tx.update(sessionRef,{status:'committed',result:{packId:session.packId},cleanupPaths:paths,cleanupPending:true,updatedAt:stamp});return paths;
    });committed={...session,cleanupPaths};
  }catch(e){await db().runTransaction(async tx=>{const current=await tx.get(sessionRef);if(current.get('status')==='validating'&&current.get('attempt')===attempt)tx.update(sessionRef,{status:'accepting',lastError:e instanceof HttpsError?e.details:{code:'saveFailed'},updatedAt:FieldValue.serverTimestamp()});});if(e instanceof HttpsError)throw e;throw new HttpsError('unavailable','Could not save.',{code:'saveFailed'});}
  try{return await cleanCommitted(committed);}catch{return {packId:session.packId,cleanupPending:true};}
});
async function closeSession(sessionId:string,actorId?:string){const session=await db().runTransaction(async tx=>{const current=await tx.get(db().doc('uploadSessions/'+sessionId));if(!current.exists)return null;const s=current.data() as Session;if(actorId&&s.actorId!==actorId)throw new HttpsError('permission-denied','Only the upload owner can cancel.');if(s.status==='committed')return s;if(s.status==='validating'&&(s.leaseUntil?.toMillis()??0)>Date.now())throw new HttpsError('aborted','Save in progress.',{code:'saveBusy'});tx.update(current.ref,{status:actorId?'cancelled':'expired',updatedAt:FieldValue.serverTimestamp()});return s;});if(!session)return {cleanupPending:false};if(session.status==='committed')return cleanCommitted(session);return {cleanupPending:await removePaths(sessionId,session.files.flatMap(f=>[f.stagingPath,f.storagePath]))};}
export const cancelUpload=onCall({region},async request=>{const user=await account(request.auth?.uid);await db().runTransaction(tx=>member(tx,user.uid));return closeSession(id(request.data?.sessionId),user.uid);});
export async function cleanExpiredUploads(){let cleaned=0,pending=0;const expired=await db().collection('uploadSessions').where('status','in',['accepting','validating','cancelled','expired']).where('expiresAt','<=',Timestamp.now()).limit(100).get();for(const s of expired.docs){try{const result=await closeSession(s.id);if(result.cleanupPending)pending++;else{await s.ref.delete();cleaned++;}}catch{pending++;}}const committed=await db().collection('uploadSessions').where('cleanupPending','==',true).limit(100).get();for(const s of committed.docs){if(s.get('status')!=='committed')continue;try{if((await cleanCommitted(s.data() as Session)).cleanupPending)pending++;}catch{pending++;}}const jobs=await db().collection('cleanupJobs').limit(100).get();for(const job of jobs.docs){if(await removePaths(job.id,job.get('paths') as string[]))pending++;}return {cleaned,pending};}
export const cleanupUploads=onCall({region,timeoutSeconds:120},async request=>{const user=await account(request.auth?.uid);await db().runTransaction(async tx=>{if((await member(tx,user.uid)).get('role')!=='admin')throw new HttpsError('permission-denied','Administrator required.');});return cleanExpiredUploads();});
