import { afterAll, expect, test } from 'vitest';
import { initializeApp, deleteApp, type FirebaseApp } from 'firebase/app';
import { getAuth, connectAuthEmulator, createUserWithEmailAndPassword } from 'firebase/auth';
import { getFunctions, connectFunctionsEmulator, httpsCallable } from 'firebase/functions';
import { getFirestore, connectFirestoreEmulator, doc, getDoc, getDocs, collection, setDoc, deleteDoc } from 'firebase/firestore';
import { initializeApp as adminApp, deleteApp as deleteAdmin } from 'firebase-admin/app';
import { getFirestore as adminDb } from 'firebase-admin/firestore';
const projectId = 'demo-evertrace-test', apps: FirebaseApp[] = [];
const trusted = adminApp({ projectId }, 'R2-categories'), db = adminDb(trusted);
function client() { const app = initializeApp({ projectId, apiKey: 'local-emulator-key' }, `r2-${Math.random()}`); apps.push(app); const auth = getAuth(app); connectAuthEmulator(auth, 'http://127.0.0.1:10099', { disableWarnings: true }); const functions = getFunctions(app); connectFunctionsEmulator(functions, '127.0.0.1', 15001); const firestore = getFirestore(app); connectFirestoreEmulator(firestore, '127.0.0.1', 18080); return { auth, firestore, profile: httpsCallable(functions, 'ensureProfile'), create: httpsCallable<Record<string, unknown>, { id: string; name: string; created: boolean }>(functions, 'createCategory') }; }
async function member() { const c = client(); await createUserWithEmailAndPassword(c.auth, `cat-${Date.now()}-${Math.random()}@example.test`, 'Evertrace-test-2026!'); await c.profile({}); return c; }
afterAll(async () => { await Promise.all(apps.map(deleteApp)); await deleteAdmin(trusted); });
test('anonymous category creation and reads are denied', async () => { const c = client(); await expect(c.create({ name: 'Anonymous' })).rejects.toMatchObject({ code: 'functions/unauthenticated' }); await expect(getDocs(collection(c.firestore, 'categories'))).rejects.toMatchObject({ code: 'permission-denied' }); });
test('an authenticated user without a member profile cannot create categories', async () => { const c = client(); await createUserWithEmailAndPassword(c.auth, `no-profile-${Date.now()}@example.test`, 'Evertrace-test-2026!'); await expect(c.create({ name: 'Missing profile' })).rejects.toMatchObject({ code: 'functions/permission-denied' }); });
test('two members share one category and owner comes from verified identity', async () => { const a = await member(), b = await member(); const result = await a.create({ name: `Practice ${Date.now()}`, createdBy: 'forged' }); const saved = await getDoc(doc(b.firestore, 'categories', result.data.id)); expect(saved.data()).toMatchObject({ createdBy: a.auth.currentUser!.uid, status: 'active', packCount: 0, name: result.data.name }); });
test('concurrent normalized duplicate names create exactly one stable category', async () => { const a = await member(), b = await member(), suffix = Date.now(); const results = await Promise.all([a.create({ name: `  ＦＯＣＵＳ ${suffix}  ` }), b.create({ name: `focus\u3000${suffix}` }), a.create({ name: `FOCUS ${suffix}` })]); expect(new Set(results.map(x => x.data.id)).size).toBe(1); expect(results.filter(x => x.data.created)).toHaveLength(1); const docs = await db.collection('categories').where('normalizedName', '==', `focus ${suffix}`).get(); expect(docs.size).toBe(1); });
test('invalid, nested and multi-category creation is rejected without a partial category', async () => { const c = await member(); for (const data of [{ name: '' }, { name: 'a'.repeat(61) }, { name: 'Nested', parentId: 'parent' }, { name: 'Multiple', categoryIds: ['a', 'b'] }]) await expect(c.create(data)).rejects.toMatchObject({ code: 'functions/invalid-argument' }); });
test('members cannot directly create, rename, delete or access the category name index', async () => { const c = await member(), result = await c.create({ name: `Protected ${Date.now()}` }); const ref = doc(c.firestore, 'categories', result.data.id); await expect(setDoc(ref, { name: 'Renamed' }, { merge: true })).rejects.toMatchObject({ code: 'permission-denied' }); await expect(deleteDoc(ref)).rejects.toMatchObject({ code: 'permission-denied' }); await expect(setDoc(doc(c.firestore, 'categories', 'injected'), { name: 'Injected' })).rejects.toMatchObject({ code: 'permission-denied' }); await expect(getDocs(collection(c.firestore, 'categoryNames'))).rejects.toMatchObject({ code: 'permission-denied' }); });
test('creation cannot resurrect a category locked for migration', async () => { const c = await member(), name = `Locked ${Date.now()}`, result = await c.create({ name }); await db.doc(`categories/${result.data.id}`).update({ status: 'migrating' }); await expect(c.create({ name })).rejects.toMatchObject({ code: 'functions/failed-precondition' }); });
