import { afterAll, expect, test } from 'vitest';
import { createHash, randomUUID } from 'node:crypto';
import sharp from 'sharp';
import { initializeApp, deleteApp, type FirebaseApp } from 'firebase/app';
import { getAuth, connectAuthEmulator, createUserWithEmailAndPassword } from 'firebase/auth';
import { getFunctions, connectFunctionsEmulator, httpsCallable } from 'firebase/functions';
import { getFirestore, connectFirestoreEmulator, doc, getDoc } from 'firebase/firestore';
import { getStorage, connectStorageEmulator, ref, uploadBytes, getBytes } from 'firebase/storage';
import { initializeApp as adminApp, deleteApp as deleteAdmin } from 'firebase-admin/app';
import { getFirestore as adminDb } from 'firebase-admin/firestore';
import { getStorage as adminStorage } from 'firebase-admin/storage';
import { workbook } from '../fixtures/workbooks.mjs';
const projectId='demo-evertrace-test',bucketName=projectId+'.appspot.com',apps:FirebaseApp[]=[];
const trusted=adminApp({projectId,storageBucket:bucketName},'r4-packs'),db=adminDb(trusted),bucket=adminStorage(trusted).bucket();
type Part={kind:'text'|'eeg'|'image';name:string;bytes:Uint8Array};
type Session={sessionId:string;packId:string;files:{id:string;mediaType:string;stagingPath:string;storagePath:string}[]};
function client(){const app=initializeApp({projectId,apiKey:'local-emulator-key',storageBucket:bucketName},randomUUID());apps.push(app);const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:10099',{disableWarnings:true});const functions=getFunctions(app);connectFunctionsEmulator(functions,'127.0.0.1',15001);const firestore=getFirestore(app);connectFirestoreEmulator(firestore,'127.0.0.1',18080);const storage=getStorage(app);connectStorageEmulator(storage,'127.0.0.1',19199);return {auth,firestore,storage,profile:httpsCallable(functions,'ensureProfile'),category:httpsCallable<{name:string},{id:string}>(functions,'createCategory'),begin:httpsCallable<Record<string,unknown>,Session>(functions,'beginUpload'),save:httpsCallable<{sessionId:string},{packId:string;cleanupPending:boolean}>(functions,'savePack'),cleanup:httpsCallable(functions,'cleanupUploads')};}
async function member(admin=false){const c=client();await createUserWithEmailAndPassword(c.auth,randomUUID()+'@example.test','Evertrace-test-2026!');await c.profile({});if(admin)await db.doc('users/'+c.auth.currentUser!.uid).update({role:'admin'});return c;}
async function image(format:'png'|'jpeg'|'webp'='png'){return sharp({create:{width:16,height:12,channels:3,background:'#a1b2c3'}}).toFormat(format).toBuffer();}
function plan(p:Part){return {kind:p.kind,name:p.name,size:p.bytes.length,sha256:createHash('sha256').update(p.bytes).digest('hex')};}
async function input(c:ReturnType<typeof client>,parts?:Part[]){const categoryId=(await c.category({name:'R4 '+randomUUID()})).data.id;const files=parts??[{kind:'eeg' as const,name:'synthetic.xlsx',bytes:await workbook()}];return {requestId:randomUUID(),title:'Synthetic R4',categoryId,textContent:'Synthetic notes',filePlan:files.map(plan),parts:files};}
async function begin(c:ReturnType<typeof client>,body:Record<string,unknown>){return (await c.begin(body)).data;}
async function upload(c:ReturnType<typeof client>,s:Session,parts:Part[]){for(let i=0;i<s.files.length;i++)await uploadBytes(ref(c.storage,s.files[i].stagingPath),parts[i].bytes,{contentType:s.files[i].mediaType});}
async function create(c:ReturnType<typeof client>,parts?:Part[]){const p=await input(c,parts),s=await begin(c,p);await upload(c,s,p.parts);await c.save({sessionId:s.sessionId});return {p,s};}
function edit(p:Awaited<ReturnType<typeof input>>,s:Session,changes:Record<string,unknown>={}){return {...p,requestId:randomUUID(),packId:s.packId,expectedVersion:1,retainedFileIds:s.files.map(f=>f.id),filePlan:[],title:'Edited R4',...changes};}
afterAll(async()=>{await Promise.all(apps.map(deleteApp));await deleteAdmin(trusted);});
test('multiple text, images and Excel publish intact originals for another member',async()=>{const c=await member(),other=await member(),parts:Part[]=[{kind:'eeg',name:'first.xlsx',bytes:await workbook()},{kind:'eeg',name:'second.xlsx',bytes:await workbook()},{kind:'text',name:'one.txt',bytes:Buffer.from('one')},{kind:'text',name:'two.txt',bytes:Buffer.from('二')},...await Promise.all((['png','jpeg','webp'] as const).map(async f=>({kind:'image' as const,name:'synthetic.'+f,bytes:await image(f)})))];const {s}=await create(c,parts);expect((await getDoc(doc(other.firestore,'packs',s.packId))).data()).toMatchObject({version:1,eegCount:2,textFileCount:2,imageCount:3});for(let i=0;i<s.files.length;i++)expect(Buffer.from(await getBytes(ref(other.storage,s.files[i].storagePath)))).toEqual(Buffer.from(parts[i].bytes));});
test('spoofed image type and truncated real image are rejected by server without publishing',async()=>{const c=await member();for(const bytes of [Buffer.from('<svg><script>bad</script></svg>'),await image('jpeg'),(await image()).subarray(0,40)]){const p=await input(c,[{kind:'eeg',name:'eeg.xlsx',bytes:await workbook()},{kind:'image',name:'spoof.png',bytes}]),s=await begin(c,p);await upload(c,s,p.parts);await expect(c.save({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/invalid-argument',details:{code:'validationFailed'}});expect((await db.doc('packs/'+s.packId).get()).exists).toBe(false);}});
test('creator changes title, notes and category with immutable ownership and atomic counters',async()=>{const c=await member(),{p,s}=await create(c),before=(await db.doc('packs/'+s.packId).get()).data()!,categoryId=(await c.category({name:'R4 destination '+randomUUID()})).data.id;const e=await begin(c,edit(p,s,{categoryId,textContent:'Changed notes',ownerId:'forged'}));await c.save({sessionId:e.sessionId});const after=(await db.doc('packs/'+s.packId).get()).data()!;expect(after).toMatchObject({title:'Edited R4',textContent:'Changed notes',categoryId,version:2,ownerId:c.auth.currentUser!.uid,ownerName:before.ownerName});expect(after.createdAt).toEqual(before.createdAt);expect((await db.doc('categories/'+p.categoryId).get()).get('packCount')).toBe(0);expect((await db.doc('categories/'+categoryId).get()).get('packCount')).toBe(1);await c.save({sessionId:e.sessionId});expect((await db.doc('packs/'+s.packId).get()).get('version')).toBe(2);});
test('other member cannot edit; admin may edit without changing owner and demotion is rechecked',async()=>{const owner=await member(),other=await member(),admin=await member(true),{p,s}=await create(owner);await expect(other.begin(edit(p,s))).rejects.toMatchObject({code:'functions/permission-denied'});const e=await begin(admin,edit(p,s));await db.doc('users/'+admin.auth.currentUser!.uid).update({role:'member'});await expect(admin.save({sessionId:e.sessionId})).rejects.toMatchObject({code:'functions/permission-denied'});expect((await db.doc('packs/'+s.packId).get()).get('version')).toBe(1);await db.doc('users/'+admin.auth.currentUser!.uid).update({role:'admin'});await admin.save({sessionId:e.sessionId});expect((await db.doc('packs/'+s.packId).get()).data()).toMatchObject({version:2,ownerId:owner.auth.currentUser!.uid,updatedBy:admin.auth.currentUser!.uid});});
test('cannot remove final Excel or final text, reuse foreign/inactive files or exceed attachment budget',async()=>{const c=await member(),{p,s}=await create(c,[{kind:'eeg',name:'eeg.xlsx',bytes:await workbook()},{kind:'text',name:'notes.txt',bytes:Buffer.from('notes')}]);for(const change of [{retainedFileIds:[],textContent:'notes'},{retainedFileIds:[s.files[0].id],textContent:''},{retainedFileIds:['foreign']},{expectedVersion:0},{retainedFileIds:[s.files[0].id,s.files[0].id]}])await expect(c.begin(edit(p,s,change))).rejects.toMatchObject({code:'functions/invalid-argument'});const tooMany=Array.from({length:13},()=>p.filePlan[0]);await expect(c.begin({...p,requestId:randomUUID(),filePlan:tooMany})).rejects.toMatchObject({code:'functions/invalid-argument'});});
test('replacement stays private until commit; failed validation leaves old version readable',async()=>{const c=await member(),other=await member(),{p,s}=await create(c),bad:Part={kind:'eeg',name:'bad.xlsx',bytes:Buffer.from('not excel')},e=await begin(c,edit(p,s,{retainedFileIds:[],filePlan:[plan(bad)]}));await upload(c,e,[bad]);expect(Buffer.from(await getBytes(ref(other.storage,s.files[0].storagePath)))).toEqual(Buffer.from(p.parts[0].bytes));await expect(getBytes(ref(other.storage,e.files[0].stagingPath))).rejects.toMatchObject({code:'storage/unauthorized'});await expect(c.save({sessionId:e.sessionId})).rejects.toMatchObject({code:'functions/invalid-argument'});expect((await db.doc('packs/'+s.packId).get()).data()).toMatchObject({version:1,title:p.title});expect((await db.doc(`packs/${s.packId}/files/${s.files[0].id}`).get()).get('active')).toBe(true);});
test('successful replacement uses a new file ID and revokes old reads; cleanup retry preserves new version',async()=>{const c=await member(),{p,s}=await create(c),part:Part={kind:'eeg',name:'replacement.xlsx',bytes:await workbook()},e=await begin(c,edit(p,s,{retainedFileIds:[],filePlan:[plan(part)]}));await upload(c,e,[part]);await c.save({sessionId:e.sessionId});expect(e.files[0].id).not.toBe(s.files[0].id);expect((await db.doc(`packs/${s.packId}/files/${s.files[0].id}`).get()).get('active')).toBe(false);await expect(getBytes(ref(c.storage,s.files[0].storagePath))).rejects.toMatchObject({code:'storage/unauthorized'});expect(Buffer.from(await getBytes(ref(c.storage,e.files[0].storagePath)))).toEqual(Buffer.from(part.bytes));await c.save({sessionId:s.sessionId});expect((await db.doc('packs/'+s.packId).get()).get('version')).toBe(2);expect((await bucket.file(e.files[0].storagePath).exists())[0]).toBe(true);});
test('parallel editors yield one new version and a clear conflict rather than overwrite',async()=>{const c=await member(),{p,s}=await create(c),a=await begin(c,edit(p,s,{title:'First'})),b=await begin(c,edit(p,s,{title:'Second'}));const results=await Promise.allSettled([c.save({sessionId:a.sessionId}),c.save({sessionId:b.sessionId})]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.find(r=>r.status==='rejected')).toMatchObject({reason:{code:'functions/aborted',details:{code:'versionConflict'}}});expect((await db.doc('packs/'+s.packId).get()).get('version')).toBe(2);expect((await db.doc('categories/'+p.categoryId).get()).get('packCount')).toBe(1);});
test('reused original generation and current category are verified before committing',async()=>{const c=await member(),{p,s}=await create(c),e=await begin(c,edit(p,s));await bucket.file(s.files[0].storagePath).save('tampered',{resumable:false});await expect(c.save({sessionId:e.sessionId})).rejects.toMatchObject({code:'functions/failed-precondition',details:{code:'fileChanged'}});expect((await db.doc('packs/'+s.packId).get()).get('version')).toBe(1);const second=await create(c),f=await begin(c,edit(second.p,second.s));await db.doc('categories/'+second.p.categoryId).update({status:'migrating'});await expect(c.save({sessionId:f.sessionId})).rejects.toMatchObject({code:'functions/failed-precondition'});expect((await db.doc('packs/'+second.s.packId).get()).get('version')).toBe(1);});

test('cleanup failure stays visible after commit; admin retry clears it without removing active originals',async()=>{const c=await member(),{p,s}=await create(c),e=await begin(c,edit(p,s));await c.save({sessionId:e.sessionId});const session=db.doc('uploadSessions/'+e.sessionId);const originalPaths=(await session.get()).get('cleanupPaths');await session.update({cleanupPaths:[''],cleanupPending:true});expect((await c.save({sessionId:e.sessionId})).data.cleanupPending).toBe(true);expect((await db.doc('packs/'+s.packId).get()).data()).toMatchObject({status:'ready',version:2,cleanupPending:true});await session.update({cleanupPaths:originalPaths});await db.doc('users/'+c.auth.currentUser!.uid).update({role:'admin'});await c.cleanup({});expect((await db.doc('packs/'+s.packId).get()).get('cleanupPending')).toBe(false);expect(Buffer.from(await getBytes(ref(c.storage,s.files[0].storagePath)))).toEqual(Buffer.from(p.parts[0].bytes));});
test('removed files cannot be retained again; deleting pack status and stale version reject new edit sessions',async()=>{const c=await member(),{p,s}=await create(c,[{kind:'eeg',name:'one.xlsx',bytes:await workbook()},{kind:'eeg',name:'two.xlsx',bytes:await workbook()}]),e=await begin(c,edit(p,s,{retainedFileIds:[s.files[0].id]}));await c.save({sessionId:e.sessionId});await expect(c.begin(edit(p,s))).rejects.toMatchObject({code:'functions/aborted',details:{code:'versionConflict'}});await expect(c.begin(edit(p,s,{expectedVersion:2}))).rejects.toMatchObject({code:'functions/invalid-argument'});await db.doc('packs/'+s.packId).update({status:'deleting'});await expect(c.begin(edit(p,s,{expectedVersion:2,retainedFileIds:[s.files[0].id]}))).rejects.toMatchObject({code:'functions/failed-precondition',details:{code:'packUnavailable'}});});
test('image dimensions and total retained plus new byte budget are enforced on the server',async()=>{const c=await member(),large=await sharp({create:{width:5000,height:4000,channels:3,background:'#678'}}).png().toBuffer(),p=await input(c,[{kind:'eeg',name:'eeg.xlsx',bytes:await workbook()},{kind:'image',name:'too-large.png',bytes:large}]),s=await begin(c,p);await upload(c,s,p.parts);await expect(c.save({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/invalid-argument',details:{code:'validationFailed'}});const tooBig=Array.from({length:7},()=>({...p.filePlan[0],size:5*1024*1024}));await expect(c.begin({...p,requestId:randomUUID(),filePlan:tooBig})).rejects.toMatchObject({code:'functions/invalid-argument',details:{code:'attachmentLimit'}});expect((await db.doc('packs/'+s.packId).get()).exists).toBe(false);});
