import { afterAll, expect, test } from 'vitest';
import { createHash, randomUUID } from 'node:crypto';
import { initializeApp, deleteApp, type FirebaseApp } from 'firebase/app';
import { getAuth, connectAuthEmulator, createUserWithEmailAndPassword } from 'firebase/auth';
import { getFunctions, connectFunctionsEmulator, httpsCallable } from 'firebase/functions';
import { getFirestore, connectFirestoreEmulator, doc, getDoc, getDocs, collection, query, where, deleteDoc, setDoc } from 'firebase/firestore';
import { getStorage, connectStorageEmulator, ref, uploadBytes, getBytes } from 'firebase/storage';
import { initializeApp as adminApp, deleteApp as deleteAdmin } from 'firebase-admin/app';
import { getFirestore as adminDb, Timestamp } from 'firebase-admin/firestore';
import { getStorage as adminStorage } from 'firebase-admin/storage';
import { workbook } from '../fixtures/workbooks.mjs';
const projectId='demo-evertrace-test',storageBucket=projectId+'.appspot.com',apps:FirebaseApp[]=[];
const trusted=adminApp({projectId,storageBucket},'r7-management'),db=adminDb(trusted),bucket=adminStorage(trusted).bucket();
type Session={sessionId:string;packId:string;files:{id:string;mediaType:string;stagingPath:string;storagePath:string}[]};
type Result={operationId:string;status:'done'|'pending';moved?:number};
function client(){const app=initializeApp({projectId,apiKey:'local-emulator-key',storageBucket},randomUUID());apps.push(app);const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:10099',{disableWarnings:true});const functions=getFunctions(app);connectFunctionsEmulator(functions,'127.0.0.1',15001);const firestore=getFirestore(app);connectFirestoreEmulator(firestore,'127.0.0.1',18080);const storage=getStorage(app);connectStorageEmulator(storage,'127.0.0.1',19199);return {auth,firestore,storage,profile:httpsCallable(functions,'ensureProfile'),category:httpsCallable<{name:string},{id:string}>(functions,'createCategory'),begin:httpsCallable<Record<string,unknown>,Session>(functions,'beginUpload'),save:httpsCallable(functions,'savePack'),remove:httpsCallable<Record<string,unknown>,Result>(functions,'deletePack'),rename:httpsCallable<Record<string,unknown>,{id:string;name:string}>(functions,'renameCategory'),migrate:httpsCallable<Record<string,unknown>,Result>(functions,'deleteCategory'),retry:httpsCallable<Record<string,unknown>,Result>(functions,'retryCleanup')};}
async function member(admin=false){const c=client();await createUserWithEmailAndPassword(c.auth,randomUUID()+'@example.test','Evertrace-test-2026!');await c.profile({});if(admin)await db.doc('users/'+c.auth.currentUser!.uid).update({role:'admin'});return c;}
async function category(c:ReturnType<typeof client>){return (await c.category({name:'R7 '+randomUUID()})).data.id;}
async function plan(c:ReturnType<typeof client>,categoryId=undefined as string|undefined){const bytes=await workbook(),input={requestId:randomUUID(),title:'Synthetic R7',categoryId:categoryId??await category(c),textContent:'Synthetic preserved notes',filePlan:[{kind:'eeg',name:'synthetic.xlsx',size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')}]};return {input,bytes};}
async function create(c:ReturnType<typeof client>,categoryId?:string){const p=await plan(c,categoryId),s=(await c.begin(p.input)).data;await uploadBytes(ref(c.storage,s.files[0].stagingPath),p.bytes,{contentType:s.files[0].mediaType});await c.save({sessionId:s.sessionId});return {...p,s};}
function deletion(s:Session){return {packId:s.packId,expectedVersion:1,operationId:randomUUID(),confirmation:s.packId};}
afterAll(async()=>{await Promise.all(apps.map(deleteApp));await deleteAdmin(trusted);});
test('anonymous and ordinary member cannot administer categories or retry unknown operations',async()=>{for(const c of [client(),await member()]){const code=c.auth.currentUser?'functions/permission-denied':'functions/unauthenticated';for(const call of c.auth.currentUser?[c.rename,c.migrate,c.retry]:[c.remove,c.rename,c.migrate,c.retry])await expect(call({operationId:'unknown-operation'})).rejects.toMatchObject({code});}});
test('administrator deletes all originals, orphan copies, staging, sessions and subdocuments exactly once',async()=>{const owner=await member(),admin=await member(true),other=await member(),p=await create(owner),s=p.s,body=deletion(s);const pending=(await owner.begin({...p.input,requestId:randomUUID(),packId:s.packId,expectedVersion:1,retainedFileIds:s.files.map(f=>f.id)})).data;await uploadBytes(ref(owner.storage,pending.files[0].stagingPath),p.bytes,{contentType:pending.files[0].mediaType});await bucket.file('packs/'+s.packId+'/files/orphan.xlsx').save('orphan');await db.doc('cleanupJobs/'+pending.sessionId).set({sessionId:pending.sessionId,paths:[pending.files[0].stagingPath],status:'pending'});await db.doc(`packs/${s.packId}/files/inactive`).set({active:false,storagePath:'packs/'+s.packId+'/files/old.txt'});expect((await admin.remove(body)).data.status).toBe('done');expect((await admin.remove(body)).data.status).toBe('done');expect((await db.doc('packs/'+s.packId).get()).exists).toBe(false);expect((await db.collection(`packs/${s.packId}/files`).get()).empty).toBe(true);expect((await db.collection('uploadSessions').where('packId','==',s.packId).get()).empty).toBe(true);expect((await db.doc('cleanupJobs/'+pending.sessionId).get()).exists).toBe(false);expect((await bucket.getFiles({prefix:'packs/'+s.packId+'/'}))[0]).toHaveLength(0);expect((await bucket.getFiles({prefix:`staging/${owner.auth.currentUser!.uid}/${pending.sessionId}/`}))[0]).toHaveLength(0);expect((await db.doc('categories/'+p.input.categoryId).get()).get('packCount')).toBe(0);await expect(getBytes(ref(other.storage,s.files[0].storagePath))).rejects.toMatchObject({code:'storage/unauthorized'});await expect(owner.save({sessionId:pending.sessionId})).rejects.toMatchObject({code:'functions/failed-precondition'});});
test('confirmation and version are checked before deletion; an operation key cannot target another pack',async()=>{const admin=await member(true),p=await create(admin),body=deletion(p.s);await expect(admin.remove({...body,confirmation:'wrong'})).rejects.toMatchObject({code:'functions/invalid-argument'});await expect(admin.remove({...body,expectedVersion:2})).rejects.toMatchObject({code:'functions/aborted',details:{code:'versionConflict'}});expect((await db.doc('packs/'+p.s.packId).get()).get('status')).toBe('ready');await admin.remove(body);const other=await create(admin);await expect(admin.remove({...deletion(other.s),operationId:body.operationId})).rejects.toMatchObject({code:'functions/already-exists'});expect((await db.doc('packs/'+other.s.packId).get()).exists).toBe(true);});
test('live save lease blocks deleting before any original is removed',async()=>{const admin=await member(true),p=await create(admin),s=(await admin.begin({...p.input,packId:p.s.packId,expectedVersion:1,retainedFileIds:p.s.files.map(f=>f.id),requestId:randomUUID(),filePlan:[]})).data;await db.doc('uploadSessions/'+s.sessionId).update({status:'validating',leaseUntil:Timestamp.fromMillis(Date.now()+60000)});await expect(admin.remove(deletion(p.s))).rejects.toMatchObject({code:'functions/aborted',details:{code:'saveBusy'}});expect((await bucket.file(p.s.files[0].storagePath).exists())[0]).toBe(true);expect((await db.doc('packs/'+p.s.packId).get()).get('status')).toBe('ready');});
test('two deletion requests converge without a negative category count',async()=>{const admin=await member(true),p=await create(admin),body=deletion(p.s);await Promise.allSettled([admin.remove(body),admin.remove(body)]);expect((await admin.remove(body)).data.status).toBe('done');expect((await db.doc('categories/'+p.input.categoryId).get()).get('packCount')).toBe(0);});
test('administrator renames atomically, rejects normalized collisions and releases the old name',async()=>{const admin=await member(true),id=await category(admin),old=(await db.doc('categories/'+id).get()).get('name'),other=await category(admin),name=(await db.doc('categories/'+other).get()).get('name');await expect(admin.rename({categoryId:id,name})).rejects.toMatchObject({code:'functions/already-exists'});const renamed='Renamed '+randomUUID();await admin.rename({categoryId:id,name:renamed});expect((await db.doc('categories/'+id).get()).get('name')).toBe(renamed);expect((await admin.category({name:renamed.toUpperCase()})).data.id).toBe(id);expect((await admin.category({name:old})).data.id).not.toBe(id);const result=await Promise.allSettled([admin.rename({categoryId:id,name:'Concurrent '+id}),admin.rename({categoryId:other,name:'Concurrent '+id})]);expect(result.filter(r=>r.status==='fulfilled')).toHaveLength(1);});
test('used category requires a valid distinct target, empty category deletes directly and idempotently',async()=>{const admin=await member(true),p=await create(admin);for(const targetId of [undefined,p.input.categoryId,'missing'])await expect(admin.migrate({sourceId:p.input.categoryId,targetId,operationId:randomUUID(),confirmation:p.input.categoryId})).rejects.toMatchObject({code:targetId===p.input.categoryId?'functions/invalid-argument':'functions/failed-precondition'});expect((await db.doc('categories/'+p.input.categoryId).get()).get('status')).toBe('active');const id=await category(admin),body={sourceId:id,operationId:randomUUID(),confirmation:id};expect((await admin.migrate(body)).data.status).toBe('done');expect((await admin.migrate(body)).data.status).toBe('done');expect((await db.doc('categories/'+id).get()).exists).toBe(false);});
test('category migration preserves all materials and ownership, increments versions and keeps exact counters',async()=>{const owner=await member(),admin=await member(true),p=await create(owner),q=await create(owner,p.input.categoryId),targetId=await category(admin),existing=await create(owner,targetId),before=(await db.doc('packs/'+p.s.packId).get()).data()!,body={sourceId:p.input.categoryId,targetId,operationId:randomUUID(),confirmation:p.input.categoryId};expect((await admin.migrate(body)).data).toMatchObject({status:'done',moved:2});expect((await admin.migrate(body)).data.moved).toBe(2);for(const item of [p,q])expect((await db.doc('packs/'+item.s.packId).get()).data()).toMatchObject({categoryId:targetId,version:2,ownerId:owner.auth.currentUser!.uid,textContent:item.input.textContent});expect((await db.doc('packs/'+p.s.packId).get()).get('fileAccess')).toEqual(before.fileAccess);expect(Buffer.from(await getBytes(ref(owner.storage,p.s.files[0].storagePath)))).toEqual(Buffer.from(p.bytes));expect((await db.doc('categories/'+targetId).get()).get('packCount')).toBe(3);expect((await db.doc('categories/'+p.input.categoryId).get()).exists).toBe(false);expect((await db.collection('packs').where('categoryId','==',p.input.categoryId).get()).empty).toBe(true);expect((await db.doc('packs/'+existing.s.packId).get()).get('version')).toBe(1);const key=createHash('sha256').update((await db.doc('adminOperations/'+body.operationId).get()).get('sourceNormalizedName')).digest('hex');expect((await db.doc('categoryNames/'+key).get()).exists).toBe(false);});
test('large migration crosses transaction batches and resumes without duplicate moves',async()=>{const admin=await member(true),sourceId=await category(admin),targetId=await category(admin),batch=db.batch();for(let i=0;i<205;i++)batch.set(db.doc('packs/'+randomUUID()),{status:'ready',categoryId:sourceId,version:1,ownerId:'synthetic',ownerName:'Synthetic R7',title:'Synthetic R7 migration '+i,titleSearch:'synthetic r7 migration '+i,createdAt:Timestamp.now(),textContent:'unchanged'});batch.update(db.doc('categories/'+sourceId),{packCount:205});await batch.commit();const body={sourceId,targetId,operationId:randomUUID(),confirmation:sourceId};let result=(await admin.migrate(body)).data;for(let i=0;i<10&&result.status==='pending';i++)result=(await admin.retry({operationId:body.operationId})).data;expect(result).toMatchObject({status:'done',moved:205});expect((await db.doc('categories/'+targetId).get()).get('packCount')).toBe(205);expect((await db.collection('packs').where('categoryId','==',sourceId).get()).empty).toBe(true);const synthetic=await db.collection('packs').where('categoryId','==',targetId).get(),cleanup=db.batch();for(const item of synthetic.docs)cleanup.delete(item.ref);cleanup.update(db.doc('categories/'+targetId),{packCount:0});await cleanup.commit();});
test('saved upload cannot write back into a category after migration',async()=>{const owner=await member(),admin=await member(true),p=await create(owner),pending=(await owner.begin({...p.input,requestId:randomUUID(),title:'Pending upload'})).data;await uploadBytes(ref(owner.storage,pending.files[0].stagingPath),p.bytes,{contentType:pending.files[0].mediaType});await admin.migrate({sourceId:p.input.categoryId,targetId:await category(admin),operationId:randomUUID(),confirmation:p.input.categoryId});await expect(owner.save({sessionId:pending.sessionId})).rejects.toMatchObject({code:'functions/failed-precondition',details:{code:'categoryUnavailable'}});expect((await db.doc('packs/'+pending.packId).get()).exists).toBe(false);});
test('members cannot read pending operations or deleting packs and direct admin deletes stay denied',async()=>{const admin=await member(true),other=await member(),p=await create(admin);await db.doc('packs/'+p.s.packId).update({status:'deleting'});await db.doc('adminOperations/'+p.s.packId).set({status:'pending',kind:'deletePack',packId:p.s.packId});await expect(getDoc(doc(other.firestore,'packs',p.s.packId))).rejects.toMatchObject({code:'permission-denied'});await expect(getDocs(query(collection(other.firestore,'adminOperations'),where('status','==','pending')))).rejects.toMatchObject({code:'permission-denied'});expect((await getDocs(query(collection(admin.firestore,'adminOperations'),where('status','==','pending')))).docs.some(d=>d.id===p.s.packId)).toBe(true);await expect(getBytes(ref(admin.storage,p.s.files[0].storagePath))).rejects.toMatchObject({code:'storage/unauthorized'});await expect(deleteDoc(doc(admin.firestore,'packs',p.s.packId))).rejects.toMatchObject({code:'permission-denied'});});

test('storage cleanup failure stays inaccessible and an administrator retry completes the same operation',async()=>{const {startPackDeletion,advanceOperation}=await import('../../functions/src/management');const owner=await member(),admin=await member(true),p=await create(owner),operationId=randomUUID(),uid=admin.auth.currentUser!.uid;await startPackDeletion(uid,{...deletion(p.s),operationId},{db,bucket});const failed=await advanceOperation(uid,operationId,{db,bucket,deleteObject:async()=>{throw new Error('Injected storage outage');}});expect(failed.status).toBe('pending');expect((await db.doc('packs/'+p.s.packId).get()).get('status')).toBe('deleting');expect((await db.doc('categories/'+p.input.categoryId).get()).get('packCount')).toBe(1);await expect(getDoc(doc(owner.firestore,'packs',p.s.packId))).rejects.toMatchObject({code:'permission-denied'});await expect(getBytes(ref(owner.storage,p.s.files[0].storagePath))).rejects.toMatchObject({code:'storage/unauthorized'});expect((await admin.retry({operationId})).data.status).toBe('done');expect((await db.doc('packs/'+p.s.packId).get()).exists).toBe(false);expect((await bucket.file(p.s.files[0].storagePath).exists())[0]).toBe(false);});
test('migration failure preserves locks and retries; role and target state are rechecked',async()=>{const {startCategoryDeletion,advanceOperation}=await import('../../functions/src/management');const admin=await member(true),p=await create(admin),targetId=await category(admin),uid=admin.auth.currentUser!.uid,operationId=randomUUID();await startCategoryDeletion(uid,{sourceId:p.input.categoryId,targetId,operationId,confirmation:p.input.categoryId},{db,bucket});await expect(admin.rename({categoryId:p.input.categoryId,name:'Forbidden'})).rejects.toMatchObject({code:'functions/failed-precondition'});await expect(admin.migrate({sourceId:targetId,operationId:randomUUID(),confirmation:targetId})).rejects.toMatchObject({code:'functions/failed-precondition'});await db.doc('users/'+uid).update({role:'member'});await expect(advanceOperation(uid,operationId,{db,bucket})).rejects.toMatchObject({code:'permission-denied'});await db.doc('users/'+uid).update({role:'admin'});await db.doc('categories/'+targetId).update({status:'migrating'});expect((await advanceOperation(uid,operationId,{db,bucket})).status).toBe('pending');expect((await db.doc('packs/'+p.s.packId).get()).get('categoryId')).toBe(p.input.categoryId);await db.doc('categories/'+targetId).update({status:'active'});expect((await admin.retry({operationId})).data).toMatchObject({status:'done',moved:1});});

test('administrator retries a committed upload cleanup without changing its live originals',async()=>{const owner=await member(),admin=await member(true),p=await create(owner);await db.doc('uploadSessions/'+p.s.sessionId).update({cleanupPending:true});await db.doc('packs/'+p.s.packId).update({cleanupPending:true,cleanupSessions:{[p.s.sessionId]:true}});await bucket.file(p.s.files[0].stagingPath).save(p.bytes,{resumable:false});await db.doc('cleanupJobs/'+p.s.sessionId).set({sessionId:p.s.sessionId,paths:[p.s.files[0].stagingPath],status:'pending'});await expect(owner.retry({operationId:p.s.sessionId})).rejects.toMatchObject({code:'functions/permission-denied'});expect((await admin.retry({operationId:p.s.sessionId})).data.status).toBe('done');expect((await bucket.file(p.s.files[0].stagingPath).exists())[0]).toBe(false);expect((await db.doc('packs/'+p.s.packId).get()).get('cleanupPending')).toBe(false);expect(Buffer.from(await getBytes(ref(owner.storage,p.s.files[0].storagePath)))).toEqual(Buffer.from(p.bytes));});
test('deleted pack cannot be recreated by replaying its original upload request',async()=>{const owner=await member(),admin=await member(true),p=await create(owner);await admin.remove(deletion(p.s));await expect(owner.begin(p.input)).rejects.toMatchObject({code:'functions/failed-precondition',details:{code:'packUnavailable'}});expect((await db.doc('packs/'+p.s.packId).get()).exists).toBe(false);});
test('a save racing category migration never leaves a reference to the removed category',async()=>{const owner=await member(),admin=await member(true),p=await create(owner),s=(await owner.begin({...p.input,requestId:randomUUID()})).data;await uploadBytes(ref(owner.storage,s.files[0].stagingPath),p.bytes,{contentType:s.files[0].mediaType});const targetId=await category(admin),operationId=randomUUID(),results=await Promise.allSettled([owner.save({sessionId:s.sessionId}),admin.migrate({sourceId:p.input.categoryId,targetId,operationId,confirmation:p.input.categoryId})]);expect(results[1].status).toBe('fulfilled');expect((await db.collection('packs').where('categoryId','==',p.input.categoryId).get()).empty).toBe(true);expect((await db.doc('categories/'+p.input.categoryId).get()).exists).toBe(false);const saved=(await db.doc('packs/'+s.packId).get());if(results[0].status==='fulfilled')expect(saved.get('categoryId')).toBe(targetId);else expect(saved.exists).toBe(false);const count=(await db.collection('packs').where('categoryId','==',targetId).get()).size;expect((await db.doc('categories/'+targetId).get()).get('packCount')).toBe(count);});
test('deletion freezes and removes more than one batch of related upload sessions',async()=>{const admin=await member(true),p=await create(admin),batch=db.batch(),uid=admin.auth.currentUser!.uid;for(let i=0;i<205;i++)batch.set(db.doc('uploadSessions/'+randomUUID()),{actorId:uid,packId:p.s.packId,status:'accepting',files:[],expiresAt:Timestamp.fromMillis(Date.now()+60000)});await batch.commit();const body=deletion(p.s);let result=(await admin.remove(body)).data;for(let i=0;i<10&&result.status==='pending';i++)result=(await admin.retry({operationId:body.operationId})).data;expect(result.status).toBe('done');expect((await db.collection('uploadSessions').where('packId','==',p.s.packId).get()).empty).toBe(true);expect((await db.doc('packs/'+p.s.packId).get()).exists).toBe(false);expect((await db.doc('categories/'+p.input.categoryId).get()).get('packCount')).toBe(0);});

test('owner deletion removes originals and denies other members even when request claims ownership',async()=>{
 const owner=await member(),other=await member(),p=await create(owner),body=deletion(p.s);
 await expect(other.remove({...body,ownerId:other.auth.currentUser!.uid})).rejects.toMatchObject({code:'functions/permission-denied'});
 expect((await bucket.file(p.s.files[0].storagePath).exists())[0]).toBe(true);
 expect((await owner.remove(body)).data.status).toBe('done');
 expect((await owner.remove(body)).data.status).toBe('done');
 expect((await db.doc('packs/'+p.s.packId).get()).exists).toBe(false);
 expect((await bucket.getFiles({prefix:'packs/'+p.s.packId+'/'}))[0]).toHaveLength(0);
 expect((await db.doc('categories/'+p.input.categoryId).get()).get('packCount')).toBe(0);
 await expect(other.retry({operationId:body.operationId})).rejects.toMatchObject({code:'functions/permission-denied'});
 expect((await owner.retry({operationId:body.operationId})).data.status).toBe('done');
});
test('owner can read only scoped cleanup receipts and retry own failed deletion',async()=>{
 const {startPackDeletion,advanceOperation}=await import('../../functions/src/management');
 const owner=await member(),other=await member(),admin=await member(true),p=await create(owner),operationId=randomUUID(),uid=owner.auth.currentUser!.uid;
 await startPackDeletion(uid,{...deletion(p.s),operationId},{db,bucket});
 expect((await advanceOperation(uid,operationId,{db,bucket,deleteObject:async()=>{throw new Error('Storage outage');}})).status).toBe('pending');
 expect((await getDoc(doc(owner.firestore,'adminOperations',operationId))).get('ownerId')).toBe(uid);
 await expect(getDoc(doc(other.firestore,'adminOperations',operationId))).rejects.toMatchObject({code:'permission-denied'});
 await expect(getDocs(query(collection(owner.firestore,'adminOperations'),where('status','==','pending')))).rejects.toMatchObject({code:'permission-denied'});
 const own=await getDocs(query(collection(owner.firestore,'adminOperations'),where('status','==','pending'),where('ownerId','==',uid),where('kind','==','deletePack')));
 expect(own.docs.map(d=>d.id)).toContain(operationId);
 expect((await getDoc(doc(admin.firestore,'adminOperations',operationId))).exists()).toBe(true);
 await expect(setDoc(doc(owner.firestore,'adminOperations',operationId),{ownerId:uid},{merge:true})).rejects.toMatchObject({code:'permission-denied'});
 await expect(other.retry({operationId})).rejects.toMatchObject({code:'functions/permission-denied'});
 expect((await owner.retry({operationId})).data.status).toBe('done');
});
test('owner retry rechecks membership and an administrator can finish owner cleanup',async()=>{
 const {startPackDeletion,advanceOperation}=await import('../../functions/src/management');
 const owner=await member(),admin=await member(true),p=await create(owner),uid=owner.auth.currentUser!.uid,operationId=randomUUID();
 await startPackDeletion(uid,{...deletion(p.s),operationId},{db,bucket});
 await db.doc('users/'+uid).update({role:'blocked'});
 await expect(owner.retry({operationId})).rejects.toMatchObject({code:'functions/permission-denied'});
 expect((await bucket.file(p.s.files[0].storagePath).exists())[0]).toBe(true);
 await db.doc('users/'+uid).update({role:'member'});
 await expect(advanceOperation(uid,operationId,{db,bucket,deleteObject:async(path,generation)=>{await bucket.file(path).delete({ifGenerationMatch:generation});await db.doc('users/'+uid).update({role:'blocked'});}})).rejects.toMatchObject({code:'permission-denied'});
 expect((await db.doc('packs/'+p.s.packId).get()).get('status')).toBe('deleting');
 expect((await admin.retry({operationId})).data.status).toBe('done');
});
test('member cannot acquire deletion using another persons operation key',async()=>{
 const owner=await member(),other=await member(),admin=await member(true),p=await create(owner),body=deletion(p.s);
 const {startPackDeletion}=await import('../../functions/src/management');await startPackDeletion(admin.auth.currentUser!.uid,body,{db,bucket});
 await expect(other.remove(body)).rejects.toMatchObject({code:'functions/permission-denied'});
 expect((await owner.remove(body)).data.status).toBe('done');
});
