import { afterAll, afterEach, beforeEach, expect, test } from 'vitest';
import { createHash, randomUUID } from 'node:crypto';
import { initializeApp, deleteApp, type FirebaseApp } from 'firebase/app';
import { getAuth, connectAuthEmulator, createUserWithEmailAndPassword } from 'firebase/auth';
import { getFunctions, connectFunctionsEmulator, httpsCallable } from 'firebase/functions';
import { getFirestore, connectFirestoreEmulator, doc, getDoc, collection, getDocs, setDoc } from 'firebase/firestore';
import { getStorage, connectStorageEmulator, ref, uploadBytes } from 'firebase/storage';
import { workbook } from '../fixtures/workbooks.mjs';
import { initializeApp as adminApp, deleteApp as deleteAdmin } from 'firebase-admin/app';
import { getFirestore as adminDb } from 'firebase-admin/firestore';
import { getAuth as adminAuth } from 'firebase-admin/auth';
const projectId='demo-evertrace-test',apps:FirebaseApp[]=[],trusted=adminApp({projectId},'r8-members'),db=adminDb(trusted),authAdmin=adminAuth(trusted);
type Result={uid:string;role:'member'|'admin';changed:boolean;adminCount:number};
function client(){const app=initializeApp({projectId,apiKey:'local-emulator-key',storageBucket:projectId+'.appspot.com'},randomUUID());apps.push(app);const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:10099',{disableWarnings:true});const functions=getFunctions(app);connectFunctionsEmulator(functions,'127.0.0.1',15001);const firestore=getFirestore(app);connectFirestoreEmulator(firestore,'127.0.0.1',18080);return {auth,firestore,profile:httpsCallable(functions,'ensureProfile'),role:httpsCallable<Record<string,unknown>,Result>(functions,'setMemberRole'),category:httpsCallable(functions,'createCategory')};}
async function member(){const c=client();await createUserWithEmailAndPassword(c.auth,randomUUID()+'@example.test','Evertrace-test-2026!');await c.profile({displayName:'R8 test member'});return c;}
type Upload={sessionId:string;packId:string;files:{id:string;stagingPath:string;mediaType:string}[]};
const uid=(c:ReturnType<typeof client>)=>c.auth.currentUser!.uid;
const request=(c:ReturnType<typeof client>,role:'member'|'admin',expectedRole=role==='member'?'admin':'member')=>({uid:uid(c),role,expectedRole,operationId:randomUUID()});
async function first(){const c=await member();const path='../../scripts/bootstrap-admin.mjs';const {bootstrapAdmin}=await import(path);await bootstrapAdmin(db,uid(c));return c;}
let priorAdmins:string[]=[],priorTeam:Record<string,unknown>|undefined;
// Role-count scenarios need a single team. Fixtures are restricted to the isolated test project and restored.
beforeEach(async()=>{if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:18080')throw new Error('Isolated emulator required');priorAdmins=(await db.collection('users').where('role','==','admin').get()).docs.map(d=>d.id);priorTeam=(await db.doc('system/team').get()).data();const b=db.batch();for(const id of priorAdmins)b.update(db.doc('users/'+id),{role:'member'});b.set(db.doc('system/team'),{adminCount:0});await b.commit();});
afterEach(async()=>{const current=await db.collection('users').where('role','==','admin').get(),b=db.batch();for(const d of current.docs)b.update(d.ref,{role:'member'});for(const id of priorAdmins)b.update(db.doc('users/'+id),{role:'admin'});if(priorTeam)b.set(db.doc('system/team'),priorTeam);else b.delete(db.doc('system/team'));await b.commit();});
afterAll(async()=>{await Promise.all(apps.map(deleteApp));await deleteAdmin(trusted);});
async function count(n:number){expect((await db.collection('users').where('role','==','admin').get()).size).toBe(n);expect((await db.doc('system/team').get()).get('adminCount')).toBe(n);}
test('anonymous and ordinary members cannot change roles or list members',async()=>{const owner=await member();for(const c of [client(),owner])await expect(c.role(request(owner,'admin'))).rejects.toMatchObject({code:c.auth.currentUser?'functions/permission-denied':'functions/unauthenticated'});await expect(getDocs(collection(owner.firestore,'users'))).rejects.toMatchObject({code:'permission-denied'});});
test('administrator lists profiles but cannot write roles or team metadata directly',async()=>{const admin=await first(),target=await member();const profiles=await getDocs(collection(admin.firestore,'users'));expect(profiles.docs.map(d=>d.id)).toContain(uid(target));expect((await getDoc(doc(admin.firestore,'users',uid(target)))).get('role')).toBe('member');await expect(setDoc(doc(admin.firestore,'users',uid(target)),{role:'admin'},{merge:true})).rejects.toMatchObject({code:'permission-denied'});await expect(setDoc(doc(admin.firestore,'system','team'),{adminCount:10})).rejects.toMatchObject({code:'permission-denied'});});
test('promote and demote update exact counts and preserve identity and content',async()=>{const admin=await first(),target=await member(),before=(await db.doc('users/'+uid(target)).get()).data()!;expect((await admin.role(request(target,'admin'))).data).toMatchObject({role:'admin',adminCount:2,changed:true});await count(2);await target.profile({role:'member'});expect((await db.doc('users/'+uid(target)).get()).get('role')).toBe('admin');expect((await admin.role(request(target,'member'))).data).toMatchObject({role:'member',adminCount:1,changed:true});await count(1);const after=(await db.doc('users/'+uid(target)).get()).data()!;for(const key of ['uid','email','displayName'])expect(after[key]).toEqual(before[key]);expect(after.createdAt.isEqual(before.createdAt)).toBe(true);});
test('the last administrator cannot demote themselves by calling the endpoint',async()=>{const admin=await first();await expect(admin.role(request(admin,'member'))).rejects.toMatchObject({code:'functions/failed-precondition',details:{code:'lastAdminRequired'}});await count(1);expect((await db.doc('users/'+uid(admin)).get()).get('role')).toBe('admin');});
test('two administrators racing to demote each other leave one administrator and reject lost authority',async()=>{const a=await first(),b=await member();await a.role(request(b,'admin'));const results=await Promise.allSettled([a.role(request(b,'member')),b.role(request(a,'member'))]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.find(r=>r.status==='rejected')).toMatchObject({reason:{code:'functions/permission-denied'}});await count(1);});
test('concurrent self demotion is protected by the shared count transaction',async()=>{const a=await first(),b=await member();await a.role(request(b,'admin'));const results=await Promise.allSettled([a.role(request(a,'member')),b.role(request(b,'member'))]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.find(r=>r.status==='rejected')).toMatchObject({reason:{code:'functions/failed-precondition',details:{code:'lastAdminRequired'}}});await count(1);});
test('retries are idempotent and an old completed request never overrides a later role change',async()=>{const admin=await first(),target=await member(),body=request(target,'admin');const both=await Promise.all([admin.role(body),admin.role(body)]);expect(both.every(r=>r.data.adminCount===2)).toBe(true);await count(2);await admin.role(request(target,'member'));await admin.role(body);await count(1);expect((await db.doc('users/'+uid(target)).get()).get('role')).toBe('member');await expect(admin.role({...body,role:'member'})).rejects.toMatchObject({code:'functions/already-exists'});});
test('stale selection and invalid roles, identifiers or missing profiles cannot write anything',async()=>{const admin=await first(),target=await member();for(const data of [{...request(target,'admin'),role:'owner'},{...request(target,'admin'),uid:'bad/path'},{uid:uid(target),role:'admin'}])await expect(admin.role(data)).rejects.toMatchObject({code:'functions/invalid-argument'});await admin.role(request(target,'admin'));await expect(admin.role(request(target,'member','member'))).rejects.toMatchObject({code:'functions/aborted',details:{code:'roleChanged'}});await expect(admin.role({...request(target,'admin'),uid:'missing-profile'})).rejects.toMatchObject({code:'functions/not-found'});await count(2);});
test('disabled caller cannot administer and a disabled target cannot be promoted',async()=>{const admin=await first(),target=await member();await authAdmin.updateUser(uid(target),{disabled:true});await expect(admin.role(request(target,'admin'))).rejects.toMatchObject({code:'functions/failed-precondition',details:{code:'memberUnavailable'}});await authAdmin.updateUser(uid(target),{disabled:false});await authAdmin.updateUser(uid(admin),{disabled:true});await expect(admin.role(request(target,'admin'))).rejects.toMatchObject({code:'functions/permission-denied'});await authAdmin.updateUser(uid(admin),{disabled:false});await count(1);});
test('demotion immediately removes list, category, foreign editing and pending save authority',async()=>{
 const admin=await first(),target=await member();await admin.role(request(target,'admin'));
 const app=apps.find(a=>getAuth(a)===admin.auth)!,targetApp=apps.find(a=>getAuth(a)===target.auth)!,functions=getFunctions(app),targetFunctions=getFunctions(targetApp),storage=getStorage(app),targetStorage=getStorage(targetApp);
 connectStorageEmulator(storage,'127.0.0.1',19199);connectStorageEmulator(targetStorage,'127.0.0.1',19199);
 const categoryId=(await admin.category({name:'R8 '+randomUUID()})).data as {id:string},bytes=await workbook(),plan={requestId:randomUUID(),title:'Synthetic R8 permission check',categoryId:categoryId.id,textContent:'Synthetic notes',filePlan:[{kind:'eeg',name:'synthetic.xlsx',size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')}]};
 const begin=httpsCallable<Record<string,unknown>,Upload>(functions,'beginUpload'),save=httpsCallable(functions,'savePack'),s=(await begin(plan)).data;
 await uploadBytes(ref(storage,s.files[0].stagingPath),bytes,{contentType:s.files[0].mediaType});await save({sessionId:s.sessionId});
 const edit={...plan,requestId:randomUUID(),packId:s.packId,expectedVersion:1,retainedFileIds:s.files.map(f=>f.id)},pending=(await httpsCallable<Record<string,unknown>,Upload>(targetFunctions,'beginUpload')(edit)).data;
 await uploadBytes(ref(targetStorage,pending.files[0].stagingPath),bytes,{contentType:pending.files[0].mediaType});await admin.role(request(target,'member'));
 await expect(target.role(request(target,'admin'))).rejects.toMatchObject({code:'functions/permission-denied'});
 await expect(getDocs(collection(target.firestore,'users'))).rejects.toMatchObject({code:'permission-denied'});
 await expect(httpsCallable(targetFunctions,'renameCategory')({categoryId:categoryId.id,name:'New'})).rejects.toMatchObject({code:'functions/permission-denied'});
 await expect(httpsCallable(targetFunctions,'beginUpload')({...edit,requestId:randomUUID()})).rejects.toMatchObject({code:'functions/permission-denied'});
 await expect(httpsCallable(targetFunctions,'savePack')({sessionId:pending.sessionId})).rejects.toMatchObject({code:'functions/permission-denied'});
 expect((await db.doc('packs/'+s.packId).get()).get('version')).toBe(1);await count(1);
});
test('stale stored count is repaired from trusted roles and cannot permit last-admin demotion',async()=>{const admin=await first(),target=await member();await db.doc('system/team').update({adminCount:99});await expect(admin.role(request(admin,'member'))).rejects.toMatchObject({code:'functions/failed-precondition',details:{code:'lastAdminRequired'}});await admin.role(request(target,'admin'));await count(2);});
test('bootstrap cannot create a second administrator when count metadata is missing',async()=>{const admin=await first(),target=await member();await db.doc('system/team').delete();const path='../../scripts/bootstrap-admin.mjs';const {bootstrapAdmin}=await import(path);await expect(bootstrapAdmin(db,uid(target))).rejects.toThrow('administrator already exists');await bootstrapAdmin(db,uid(admin));await count(1);});
