import { afterAll, expect, test } from 'vitest';
import { createHash, randomUUID } from 'node:crypto';
import { initializeApp, deleteApp, type FirebaseApp } from 'firebase/app';
import { getAuth, connectAuthEmulator, createUserWithEmailAndPassword } from 'firebase/auth';
import { getFunctions, connectFunctionsEmulator, httpsCallable } from 'firebase/functions';
import { getFirestore, connectFirestoreEmulator, collection, doc, getDoc, getDocs, query, where, setDoc, deleteDoc } from 'firebase/firestore';
import { getStorage, connectStorageEmulator, ref, uploadBytes, getBytes, updateMetadata, deleteObject } from 'firebase/storage';
import { initializeApp as adminApp, deleteApp as deleteAdmin } from 'firebase-admin/app';
import { getFirestore as adminDb, Timestamp } from 'firebase-admin/firestore';
import { getStorage as adminStorage } from 'firebase-admin/storage';
import { workbook, validRows } from '../fixtures/workbooks.mjs';
const projectId='demo-evertrace-test', bucketName=projectId+'.appspot.com', apps: FirebaseApp[]=[];
const trusted=adminApp({projectId,storageBucket:bucketName}, 'r3-packs'), db=adminDb(trusted), bucket=adminStorage(trusted).bucket();
type Plan={kind:'text'|'eeg';name:string;size:number;sha256:string};
type FilePlan=Plan & {id:string;mediaType:string;stagingPath:string;storagePath:string};
type Session={sessionId:string;packId:string;files:FilePlan[];result?:{packId:string}};
function client() {const app=initializeApp({projectId,apiKey:'local-emulator-key',storageBucket:bucketName},randomUUID());apps.push(app);const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:10099',{disableWarnings:true});const functions=getFunctions(app);connectFunctionsEmulator(functions,'127.0.0.1',15001);const firestore=getFirestore(app);connectFirestoreEmulator(firestore,'127.0.0.1',18080);const storage=getStorage(app);connectStorageEmulator(storage,'127.0.0.1',19199);return {auth,firestore,storage,profile:httpsCallable(functions,'ensureProfile'),category:httpsCallable<{name:string},{id:string}>(functions,'createCategory'),begin:httpsCallable<Record<string,unknown>,Session>(functions,'beginUpload'),save:httpsCallable<{sessionId:string},{packId:string;cleanupPending:boolean}>(functions,'savePack'),cancel:httpsCallable(functions,'cancelUpload'),cleanup:httpsCallable(functions,'cleanupUploads')};}
async function member(){const c=client();await createUserWithEmailAndPassword(c.auth,randomUUID()+'@example.test','Evertrace-test-2026!');await c.profile({});return c;}
function plan(bytes:Uint8Array,kind:'text'|'eeg',name:string):Plan{return {kind,name,size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};}
async function input(c:ReturnType<typeof client>,textContent='Synthetic notes',text?:Uint8Array,eeg?:Uint8Array){const categoryId=(await c.category({name:'R3 '+randomUUID()})).data.id;const excel=eeg??await workbook();return {body:{requestId:randomUUID(),title:'Synthetic R3 skill',categoryId,textContent,filePlan:[plan(excel,'eeg','synthetic.xlsx'),...(text?[plan(text,'text','notes.txt')]:[])]},buffers:[excel,...(text?[text]:[])]};}
async function begin(c:ReturnType<typeof client>,p:Awaited<ReturnType<typeof input>>){return (await c.begin(p.body)).data;}
async function upload(c:ReturnType<typeof client>,s:Session,buffers:Uint8Array[]){for(let i=0;i<s.files.length;i++)await uploadBytes(ref(c.storage,s.files[i].stagingPath),buffers[i],{contentType:s.files[i].mediaType});}
afterAll(async()=>{await Promise.all(apps.map(deleteApp));await deleteAdmin(trusted);});
test('anonymous and authenticated non-member cannot begin an upload',async()=>{const c=client();await expect(c.begin({})).rejects.toMatchObject({code:'functions/unauthenticated'});await createUserWithEmailAndPassword(c.auth,randomUUID()+'@example.test','Evertrace-test-2026!');const p={requestId:randomUUID(),title:'Skill',categoryId:'missing',textContent:'notes',filePlan:[plan(await workbook(),'eeg','test.xlsx')]};await expect(c.begin(p)).rejects.toMatchObject({code:'functions/permission-denied'});});
test('begin validates required fields, exact file plan, kind, paths, size and category',async()=>{const c=await member(),p=await input(c);for(const change of [{title:''},{categoryId:''},{textContent:''},{filePlan:[]},{filePlan:[{...p.body.filePlan[0],name:'bad.xls'}]},{filePlan:[{...p.body.filePlan[0],name:'../bad.xlsx'}]},{filePlan:[{...p.body.filePlan[0],size:6000000}]},{filePlan:[{...p.body.filePlan[0],sha256:'fake'}]},{filePlan:[...p.body.filePlan,...p.body.filePlan]},{filePlan:[{...p.body.filePlan[0],kind:'image'}]}])await expect(c.begin({...p.body,...change})).rejects.toMatchObject({code:'functions/invalid-argument'});await expect(c.begin({...p.body,categoryId:'missing'})).rejects.toMatchObject({code:'functions/failed-precondition'});});
test('begin is idempotent but one request key cannot mutate its manifest',async()=>{const c=await member(),p=await input(c);const results=await Promise.all([c.begin(p.body),c.begin({...p.body,ownerId:'forged'})]);expect(results[0].data).toEqual(results[1].data);await expect(c.begin({...p.body,title:'changed'})).rejects.toMatchObject({code:'functions/already-exists'});expect((await db.doc('packs/'+results[0].data.packId).get()).exists).toBe(false);});
test('staging is owner-only, create-only and bounded by a trusted accepting plan',async()=>{const a=await member(),b=await member(),p=await input(a),s=await begin(a,p),file=s.files[0];await expect(uploadBytes(ref(b.storage,file.stagingPath),p.buffers[0],{contentType:file.mediaType})).rejects.toMatchObject({code:'storage/unauthorized'});await expect(uploadBytes(ref(a.storage,file.stagingPath+'extra'),p.buffers[0])).rejects.toMatchObject({code:'storage/unauthorized'});await expect(uploadBytes(ref(a.storage,file.stagingPath),new Uint8Array([1]),{contentType:file.mediaType})).rejects.toMatchObject({code:'storage/unauthorized'});await upload(a,s,p.buffers);await expect(getBytes(ref(b.storage,file.stagingPath))).rejects.toMatchObject({code:'storage/unauthorized'});await expect(uploadBytes(ref(a.storage,file.stagingPath),p.buffers[0],{contentType:file.mediaType})).rejects.toMatchObject({code:'storage/unauthorized'});await expect(updateMetadata(ref(a.storage,file.stagingPath),{customMetadata:{injected:'yes'}})).rejects.toMatchObject({code:'storage/unauthorized'});await expect(deleteObject(ref(a.storage,file.stagingPath))).rejects.toMatchObject({code:'storage/unauthorized'});await db.doc('uploadSessions/'+s.sessionId).update({status:'validating'});await expect(getBytes(ref(a.storage,file.stagingPath))).rejects.toMatchObject({code:'storage/unauthorized'});});
test('missing files never publish; successfully uploaded files can be reused on retry',async()=>{const c=await member(),p=await input(c,'',new TextEncoder().encode('TXT only')),s=await begin(c,p);await uploadBytes(ref(c.storage,s.files[0].stagingPath),p.buffers[0],{contentType:s.files[0].mediaType});await expect(c.save({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/failed-precondition',details:{code:'uploadIncomplete'}});expect((await db.doc('packs/'+s.packId).get()).exists).toBe(false);expect((await db.doc('categories/'+p.body.categoryId).get()).get('packCount')).toBe(0);await uploadBytes(ref(c.storage,s.files[1].stagingPath),p.buffers[1],{contentType:s.files[1].mediaType});expect((await c.save({sessionId:s.sessionId})).data.packId).toBe(s.packId);});
test('successful notes-only save publishes original samples, owner, manifest and exactly one category count',async()=>{const a=await member(),b=await member(),p=await input(a),s=await begin(a,p);await upload(a,s,p.buffers);const result=await a.save({sessionId:s.sessionId});expect(result.data.packId).toBe(s.packId);const pack=await getDoc(doc(b.firestore,'packs',s.packId));expect(pack.data()).toMatchObject({title:p.body.title,textContent:p.body.textContent,ownerId:a.auth.currentUser!.uid,status:'ready',version:1,eegCount:1,textFileCount:0,fileAccess:{[s.files[0].id]:{active:true,storagePath:s.files[0].storagePath}}});expect(pack.data()?.createdAt).toBeTruthy();const files=await getDocs(query(collection(b.firestore,'packs',s.packId,'files'),where('active','==',true)));expect(files.size).toBe(1);const saved=files.docs[0].data();expect(saved).toMatchObject({active:true,sha256:p.body.filePlan[0].sha256,eegSummary:{count:3,start:0,end:7,min:-3,max:4}});const metadata=(await bucket.file(saved.storagePath).getMetadata())[0];expect(metadata.metadata?.firebaseStorageDownloadTokens).toBeFalsy();expect(Buffer.from(await getBytes(ref(b.storage,saved.storagePath)))).toEqual(Buffer.from(p.buffers[0]));expect((await db.doc('categories/'+p.body.categoryId).get()).get('packCount')).toBe(1);expect((await bucket.file(s.files[0].stagingPath).exists())[0]).toBe(false);});
test('TXT-only and both sources save while preserving original UTF-8/BOM bytes',async()=>{const c=await member();for(const notes of ['','Direct notes']){const bytes=new TextEncoder().encode('\ufeff中文 synthetic TXT'),p=await input(c,notes,bytes),s=await begin(c,p);await upload(c,s,p.buffers);await c.save({sessionId:s.sessionId});const pack=(await db.doc('packs/'+s.packId).get()).data()!;expect(pack).toMatchObject({textContent:notes,textFileCount:1});const files=await getDocs(query(collection(c.firestore,'packs',s.packId,'files'),where('active','==',true))),txt=files.docs.find(f=>f.get('kind')==='text')!;expect(Buffer.from(await getBytes(ref(c.storage,txt.get('storagePath'))))).toEqual(Buffer.from(bytes));}});
test('server rejects bypassed Excel and TXT validation with locations, no ready data',async()=>{const c=await member();for(const [text,eeg,code] of [[undefined,await workbook([validRows[0],[0,1],[2,null],[4,3]]),'emptyCell'],[new Uint8Array([255]),undefined,'textEncoding'],[new TextEncoder().encode('   '),undefined,'emptyText']] as const){const p=await input(c,'notes',text,eeg),s=await begin(c,p);await upload(c,s,p.buffers);try{await c.save({sessionId:s.sessionId});throw new Error('unexpected success');}catch(e){expect(e).toMatchObject({code:'functions/invalid-argument',details:{code:'validationFailed',issues:expect.arrayContaining([expect.objectContaining({code,...(code==='emptyCell'?{sheet:'EEG',row:3,column:'value'}:{})})])}});}expect((await db.doc('packs/'+s.packId).get()).exists).toBe(false);}});
test('hash mismatch rejects swapped bytes even when extension, MIME and size match',async()=>{const c=await member(),p=await input(c),s=await begin(c,p);const wrong=p.buffers[0].slice();wrong[100]^=1;await upload(c,s,[wrong]);await expect(c.save({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/invalid-argument',details:{code:'fileChanged'}});expect((await db.doc('packs/'+s.packId).get()).exists).toBe(false);});
test('duplicate save, including concurrent requests, never creates a second pack or count',async()=>{const c=await member(),p=await input(c),s=await begin(c,p);await upload(c,s,p.buffers);const results=await Promise.allSettled([c.save({sessionId:s.sessionId}),c.save({sessionId:s.sessionId})]);expect(results.some(r=>r.status==='fulfilled')).toBe(true);for(let i=0;i<2;i++)expect((await c.save({sessionId:s.sessionId})).data.packId).toBe(s.packId);expect((await db.doc('categories/'+p.body.categoryId).get()).get('packCount')).toBe(1);expect((await db.collection('packs').where('uploadSessionId','==',s.sessionId).get()).size).toBe(1);});
test('actor, current role, expired sessions and category migration are checked again at save',async()=>{const a=await member(),b=await member(),p=await input(a),s=await begin(a,p);await upload(a,s,p.buffers);await expect(b.save({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/permission-denied'});await db.doc('categories/'+p.body.categoryId).update({status:'migrating'});await expect(a.save({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/failed-precondition'});await db.doc('categories/'+p.body.categoryId).update({status:'active'});await db.doc('users/'+a.auth.currentUser!.uid).update({role:'revoked'});await expect(a.save({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/permission-denied'});await db.doc('users/'+a.auth.currentUser!.uid).update({role:'member'});await db.doc('uploadSessions/'+s.sessionId).update({expiresAt:Timestamp.fromMillis(Date.now()-1000)});await expect(a.save({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/failed-precondition'});expect((await db.doc('packs/'+s.packId).get()).exists).toBe(false);});
test('formal copy failure never publishes and retry retains a single consistent version',async()=>{const c=await member(),p=await input(c,'notes',new TextEncoder().encode('text')),s=await begin(c,p);await upload(c,s,p.buffers);await bucket.file(s.files[1].storagePath).save('poison',{resumable:false});await expect(c.save({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/failed-precondition'});expect((await db.doc('packs/'+s.packId).get()).exists).toBe(false);const other=await member();await expect(getBytes(ref(other.storage,s.files[0].storagePath))).rejects.toMatchObject({code:'storage/unauthorized'});await bucket.file(s.files[1].storagePath).delete();expect((await c.save({sessionId:s.sessionId})).data.packId).toBe(s.packId);expect((await db.doc('categories/'+p.body.categoryId).get()).get('packCount')).toBe(1);});
test('members can list only ready packs, cannot direct edit/delete or read internal sessions',async()=>{const c=await member(),p=await input(c),s=await begin(c,p);await upload(c,s,p.buffers);await c.save({sessionId:s.sessionId});await db.doc('packs/internal-r3').set({status:'validating',title:'Not ready'});await expect(getDoc(doc(c.firestore,'packs','internal-r3'))).rejects.toMatchObject({code:'permission-denied'});await expect(getDocs(collection(c.firestore,'packs'))).rejects.toMatchObject({code:'permission-denied'});expect((await getDocs(query(collection(c.firestore,'packs'),where('status','==','ready')))).docs.some(d=>d.id===s.packId)).toBe(true);await expect(setDoc(doc(c.firestore,'packs',s.packId),{title:'changed'},{merge:true})).rejects.toMatchObject({code:'permission-denied'});await expect(deleteDoc(doc(c.firestore,'packs',s.packId))).rejects.toMatchObject({code:'permission-denied'});await expect(getDoc(doc(c.firestore,'uploadSessions',s.sessionId))).rejects.toMatchObject({code:'permission-denied'});await expect(uploadBytes(ref(c.storage,s.files[0].storagePath),p.buffers[0])).rejects.toMatchObject({code:'storage/unauthorized'});const inactive=db.batch();inactive.update(db.doc(`packs/${s.packId}/files/${s.files[0].id}`),{active:false});inactive.update(db.doc('packs/'+s.packId),{[`fileAccess.${s.files[0].id}.active`]:false});await inactive.commit();await expect(getBytes(ref(c.storage,s.files[0].storagePath))).rejects.toMatchObject({code:'storage/unauthorized'});});
test('cancel is owner-only and idempotent, freezes paths and removes temporary files',async()=>{const a=await member(),b=await member(),p=await input(a),s=await begin(a,p);await upload(a,s,p.buffers);await expect(b.cancel({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/permission-denied'});await a.cancel({sessionId:s.sessionId});await a.cancel({sessionId:s.sessionId});expect((await bucket.file(s.files[0].stagingPath).exists())[0]).toBe(false);await expect(a.save({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/failed-precondition'});await expect(uploadBytes(ref(a.storage,s.files[0].stagingPath),p.buffers[0],{contentType:s.files[0].mediaType})).rejects.toMatchObject({code:'storage/unauthorized'});});

test('an interrupted validation lease is recoverable and a live lease prevents competing publication',async()=>{const c=await member(),p=await input(c),s=await begin(c,p);await upload(c,s,p.buffers);const session=db.doc('uploadSessions/'+s.sessionId);await session.update({status:'validating',attempt:'old',leaseUntil:Timestamp.fromMillis(Date.now()+60000)});await expect(c.save({sessionId:s.sessionId})).rejects.toMatchObject({code:'functions/aborted',details:{code:'saveBusy'}});await session.update({leaseUntil:Timestamp.fromMillis(Date.now()-1000)});expect((await c.save({sessionId:s.sessionId})).data.packId).toBe(s.packId);});
test('manual cleanup is administrator-only, removes expired uploads, and preserves committed files and retry results',async()=>{const c=await member();await expect(c.cleanup({})).rejects.toMatchObject({code:'functions/permission-denied'});const expired=await input(c),e=await begin(c,expired);await upload(c,e,expired.buffers);await db.doc('uploadSessions/'+e.sessionId).update({expiresAt:Timestamp.fromMillis(Date.now()-1000)});const ready=await input(c),r=await begin(c,ready);await upload(c,r,ready.buffers);await c.save({sessionId:r.sessionId});await db.doc('uploadSessions/'+r.sessionId).update({expiresAt:Timestamp.fromMillis(Date.now()-1000),cleanupPending:true});const fresh=await input(c),f=await begin(c,fresh);await upload(c,f,fresh.buffers);await db.doc('users/'+c.auth.currentUser!.uid).update({role:'admin'});await c.cleanup({});expect((await bucket.file(e.files[0].stagingPath).exists())[0]).toBe(false);expect((await bucket.file(f.files[0].stagingPath).exists())[0]).toBe(true);expect((await bucket.file(r.files[0].storagePath).exists())[0]).toBe(true);expect((await c.begin(ready.body)).data.result?.packId).toBe(r.packId);expect((await c.save({sessionId:r.sessionId})).data.packId).toBe(r.packId);});
test('a missing original or unpublished formal path is inaccessible to anonymous and other members',async()=>{const c=await member(),p=await input(c),s=await begin(c,p);await upload(c,s,p.buffers);await c.save({sessionId:s.sessionId});const anonymous=client();await expect(getBytes(ref(anonymous.storage,s.files[0].storagePath))).rejects.toMatchObject({code:'storage/unauthorized'});await expect(getDoc(doc(anonymous.firestore,'packs',s.packId))).rejects.toMatchObject({code:'permission-denied'});await bucket.file(s.files[0].storagePath).delete();await expect(getBytes(ref(c.storage,s.files[0].storagePath))).rejects.toMatchObject({code:'storage/unauthorized'});});
