import {afterAll,expect,test} from 'vitest';
import {randomUUID} from 'node:crypto';
import {initializeApp,deleteApp,type FirebaseApp} from 'firebase/app';
import {getAuth,connectAuthEmulator,createUserWithEmailAndPassword} from 'firebase/auth';
import {getFunctions,connectFunctionsEmulator,httpsCallable} from 'firebase/functions';
import {getFirestore,connectFirestoreEmulator,type Timestamp as ClientTimestamp} from 'firebase/firestore';
import {initializeApp as adminApp,deleteApp as deleteAdmin} from 'firebase-admin/app';
import {getFirestore as adminDb,Timestamp} from 'firebase-admin/firestore';
import {getPackPage,type PackFilters} from '../../apps/web/src/services/query-packs';
const projectId='demo-evertrace-test',apps:FirebaseApp[]=[],trusted=adminApp({projectId},'r5-query'),db=adminDb(trusted);
function client(){const app=initializeApp({projectId,apiKey:'local-emulator-key'},randomUUID());apps.push(app);const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:10099',{disableWarnings:true});const functions=getFunctions(app);connectFunctionsEmulator(functions,'127.0.0.1',15001);const firestore=getFirestore(app);connectFirestoreEmulator(firestore,'127.0.0.1',18080);return {auth,firestore,profile:httpsCallable(functions,'ensureProfile')};}
async function member(){const c=client();await createUserWithEmailAndPassword(c.auth,randomUUID()+'@example.test','Evertrace-test-2026!');await c.profile({});return c;}
type Row={id:string;title:string;titleSearch:string;ownerId:string;categoryId:string;createdAt:Timestamp;status:string};
async function fixture(){const a=await member(),b=await member(),tag='r5-'+randomUUID(),categories=[randomUUID(),randomUUID()],rows:Row[]=[];const batch=db.batch();for(const category of categories)batch.set(db.doc('categories/'+category),{name:category,status:'active',packCount:0});for(let i=0;i<37;i++){const title=tag+' '+String(i%9).padStart(2,'0'),row={id:randomUUID(),title,titleSearch:title,ownerId:i%2?a.auth.currentUser!.uid:b.auth.currentUser!.uid,categoryId:categories[i%3?0:1],createdAt:Timestamp.fromMillis(1700000000000+(i%4)*1000),status:'ready'};rows.push(row);batch.set(db.doc('packs/'+row.id),{...row,ownerName:'Synthetic query member',textContent:'Synthetic query fixture',version:1});}for(const suffix of ['😀','\uf8ff-tail','🧠','\u{10ffff}']){const title=tag+suffix,row={id:randomUUID(),title,titleSearch:title,ownerId:a.auth.currentUser!.uid,categoryId:categories[0],createdAt:Timestamp.fromMillis(1700000005000),status:'ready'};rows.push(row);batch.set(db.doc('packs/'+row.id),{...row,ownerName:'Synthetic query member',textContent:'Synthetic fixture',version:1});}batch.set(db.doc('packs/'+randomUUID()),{title:tag+' incomplete',titleSearch:tag,ownerId:a.auth.currentUser!.uid,categoryId:categories[0],status:'validating',createdAt:Timestamp.now()});await batch.commit();return {a,b,tag,categories,rows};}
async function all(c:ReturnType<typeof client>,filters:PackFilters){let cursor:Awaited<ReturnType<typeof getPackPage>>['cursor']=null;const rows:Awaited<ReturnType<typeof getPackPage>>['packs']=[];for(let i=0;i<100;i++){const page=await getPackPage(c.firestore,filters,c.auth.currentUser?.uid??'',cursor,4);rows.push(...page.packs);if(!page.more)return rows;expect(page.cursor).not.toBeNull();cursor=page.cursor;}throw new Error('Pagination did not terminate');}
afterAll(async()=>{await Promise.all(apps.map(deleteApp));await deleteAdmin(trusted);});
test('all eight prefix/category/mine combinations return exactly matching ready records in declared order',async()=>{const f=await fixture(),saved=(await db.collection('packs').where('status','==','ready').get()).docs.map(d=>({id:d.id,...d.data()} as Row));for(const prefix of ['',f.tag])for(const categoryId of ['',f.categories[0]])for(const scope of ['all','mine'] as const){const filters={prefix,categoryId,scope},actual=await all(f.a,filters),expected=saved.filter(p=>(!prefix||p.titleSearch.startsWith(prefix))&&(!categoryId||p.categoryId===categoryId)&&(scope!=='mine'||p.ownerId===f.a.auth.currentUser!.uid)).sort((a,b)=>prefix?Buffer.compare(Buffer.from(a.titleSearch),Buffer.from(b.titleSearch))||Buffer.compare(Buffer.from(a.id),Buffer.from(b.id)):b.createdAt.toMillis()-a.createdAt.toMillis()||Buffer.compare(Buffer.from(b.id),Buffer.from(a.id)));expect(actual.map(p=>p.id)).toEqual(expected.map(p=>p.id));expect(new Set(actual.map(p=>p.id)).size).toBe(actual.length);}});
test('normalized fullwidth/case/Chinese prefix matching never performs contains search and includes emoji suffixes',async()=>{const f=await fixture(),titles=['木工基础','木工进阶','做木工','ＦＯＣＵＳ Basics','focus review','Focus😀','Focus\uf8ff-tail','Focus\u{10ffff}'];const batch=db.batch();for(const title of titles)batch.set(db.doc('packs/'+randomUUID()),{title,titleSearch:title.normalize('NFKC').toLowerCase(),categoryId:f.categories[1],ownerId:f.a.auth.currentUser!.uid,ownerName:'Synthetic',createdAt:Timestamp.now(),status:'ready'});await batch.commit();expect((await all(f.a,{prefix:'  木工  ',categoryId:f.categories[1],scope:'all'})).map(p=>p.title).sort()).toEqual(['木工基础','木工进阶']);expect((await all(f.a,{prefix:' ＦＯＣＵＳ ',categoryId:f.categories[1],scope:'mine'})).map(p=>p.title).sort()).toEqual(titles.slice(3).sort());expect((await all(f.a,{prefix:f.tag,categoryId:f.categories[0],scope:'all'})).map(p=>p.id).sort()).toEqual(f.rows.filter(p=>p.categoryId===f.categories[0]).map(p=>p.id).sort());});
test('exact page boundary hides more and identical timestamps/title keys do not skip items',async()=>{const f=await fixture(),ids=f.rows.filter(p=>p.ownerId===f.b.auth.currentUser!.uid).map(p=>p.id);const page=await getPackPage(f.b.firestore,{prefix:f.tag,categoryId:'',scope:'mine'},f.b.auth.currentUser!.uid,null,ids.length);expect(page.packs).toHaveLength(ids.length);expect(page.more).toBe(false);expect((await all(f.b,{prefix:f.tag,categoryId:'',scope:'mine'})).map(p=>p.id).sort()).toEqual(ids.sort());});
test('cursor cannot be reused after filters or account change and mine cannot silently fall back to all',async()=>{const f=await fixture(),filters={prefix:f.tag,categoryId:'',scope:'all' as const},page=await getPackPage(f.a.firestore,filters,f.a.auth.currentUser!.uid,null,4);await expect(getPackPage(f.a.firestore,{...filters,scope:'mine'},f.a.auth.currentUser!.uid,page.cursor,4)).rejects.toThrow('queryCursor');await expect(getPackPage(f.b.firestore,filters,f.b.auth.currentUser!.uid,page.cursor,4)).rejects.toThrow('queryCursor');await expect(getPackPage(f.a.firestore,{...filters,scope:'mine'},'')).rejects.toThrow('queryInvalid');});
test('empty results and invalid inputs are explicit; unauthenticated and revoked reads are rejected',async()=>{const f=await fixture();expect(await getPackPage(f.a.firestore,{prefix:'no-match-'+randomUUID(),categoryId:'',scope:'all'},f.a.auth.currentUser!.uid)).toMatchObject({packs:[],more:false,cursor:null});for(const filters of [{prefix:'x'.repeat(161),categoryId:'',scope:'all' as const},{prefix:'ok',categoryId:'../bad',scope:'all' as const}])await expect(getPackPage(f.a.firestore,filters,f.a.auth.currentUser!.uid)).rejects.toThrow('queryInvalid');await expect(getPackPage(f.a.firestore,{prefix:'ﷺ'.repeat(160),categoryId:'',scope:'all'},f.a.auth.currentUser!.uid)).rejects.toThrow('queryInvalid');for(const size of [0,101,1.5])await expect(getPackPage(f.a.firestore,{prefix:'',categoryId:'',scope:'all'},f.a.auth.currentUser!.uid,null,size)).rejects.toThrow('queryInvalid');const anonymous=client();await expect(getPackPage(anonymous.firestore,{prefix:'',categoryId:'',scope:'all'},'')).rejects.toMatchObject({code:'permission-denied'});await db.doc('users/'+f.a.auth.currentUser!.uid).update({role:'revoked'});await expect(getPackPage(f.a.firestore,{prefix:f.tag,categoryId:'',scope:'all'},f.a.auth.currentUser!.uid)).rejects.toMatchObject({code:'permission-denied'});});
// A runtime type check ensures timestamps stay official SDK values, not invented display data.
test('listed timestamps preserve official SDK values',async()=>{const f=await fixture(),page=await getPackPage(f.a.firestore,{prefix:f.tag,categoryId:'',scope:'all'},f.a.auth.currentUser!.uid);expect((page.packs[0].createdAt as ClientTimestamp).toDate()).toBeInstanceOf(Date);});

test('emoji prefix is valid and a maximum Unicode trailing codepoint has correct upper bounds',async()=>{const f=await fixture();for(const suffix of ['😀','\u{10ffff}']){const rows=await all(f.a,{prefix:f.tag+suffix,categoryId:f.categories[0],scope:'mine'});expect(rows.map(p=>p.title)).toEqual([f.tag+suffix]);}});
