import {copyFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('..',import.meta.url)), mode=process.argv[2];
let failed=false;
if(mode.startsWith('s4')&&mode!=='s4-e2e'){const result=spawnSync(process.execPath,[path.join(root,'node_modules/vitest/vitest.mjs'),'run','--config',path.join(root,'vitest.spark-s4.config.ts')],{cwd:root,env:process.env,stdio:'inherit'});failed ||= result.status!==0;}
if(mode.startsWith('s3')&&mode!=='s3-e2e'){const result=spawnSync(process.execPath,[path.join(root,'node_modules/vitest/vitest.mjs'),'run','--config',path.join(root,'vitest.spark-s3.config.ts')],{cwd:root,env:process.env,stdio:'inherit'});failed ||= result.status!==0;}
if(mode.startsWith('s2')&&mode!=='s2-e2e'){const result=spawnSync(process.execPath,[path.join(root,'node_modules/vitest/vitest.mjs'),'run','--config',path.join(root,'vitest.spark-s2.config.ts')],{cwd:root,env:process.env,stdio:'inherit'});failed ||= result.status!==0;}
if(!mode.startsWith('s2')&&!mode.startsWith('s3')&&!mode.startsWith('s4')&&!mode.startsWith('s5')&&!['e2e','transitions'].includes(mode)){const result=spawnSync(process.execPath,[path.join(root,'node_modules/vitest/vitest.mjs'),'run','--config',path.join(root,'vitest.spark-s1.config.ts')],{cwd:root,env:process.env,stdio:'inherit'}); failed ||= result.status!==0;}
if(['s4-regression','s5-regression'].includes(mode))for(const stage of ['s1','s2','s3',...(mode==='s5-regression'?['s4']:[])]){const result=spawnSync(process.execPath,[path.join(root,'node_modules/vitest/vitest.mjs'),'run','--config',path.join(root,'vitest.spark-'+stage+'.config.ts')],{cwd:root,env:process.env,stdio:'inherit'});failed ||= result.status!==0;copyFileSync(path.join(root,'outputs',stage.toUpperCase(),'integration-results.json'),path.join(root,'outputs',mode==='s5-regression'?'S5':'S4',stage+'-regression-results.json'));}
if(['verify','e2e','red','transitions','s2-e2e','s2','s3-e2e','s3','s4-e2e','s4','s5-e2e','s5-built-e2e'].includes(mode)){const result=spawnSync(process.execPath,[path.join(root,'node_modules/@playwright/test/cli.js'),'test','--config',path.join(root,'playwright.spark.config.ts'),...(mode==='transitions'?['tests/e2e-spark/account-context.spec.ts','tests/e2e-spark/account-loading.spec.ts']:process.env.SPARK_S4_WATCH_RED==='1'?['tests/e2e-spark/s4-management.spec.ts','--grep','already viewing']:process.env.SPARK_S4_RED==='1'?['tests/e2e-spark/s4-management.spec.ts','tests/e2e-spark/s4-members.spec.ts']:[])],{cwd:root,env:{...process.env,SPARK_BUILT_TEST:mode==='s5-built-e2e'?'1':'0'},stdio:'inherit'});failed ||= result.status!==0;}
process.exitCode=failed?1:0;
