import { readFileSync } from 'node:fs';
import { beforeAll, beforeEach, afterAll, it, expect } from 'vitest';
import { initializeTestEnvironment, type RulesTestEnvironment, type RulesTestContext } from '@firebase/rules-unit-testing';
import { collection, doc, getDocs, getDoc, setDoc, writeBatch, Timestamp, type Firestore } from 'firebase/firestore';
import { seedS1 } from '../spark-s1/fixtures';
import { packBundle, addBundle } from '../spark-s2/fixtures';
import { beginSparkPackDelete, beginSparkCategoryDelete, renameSparkCategory, resumeSparkOperation } from '../../apps/web/src/services/spark-management';
import { createSparkCategory } from '../../apps/web/src/services/spark-account';
let env: RulesTestEnvironment;
const dbOf=(c:RulesTestContext)=>(c.firestore() as unknown as {_delegate:Firestore})._delegate;
const client=(uid:string)=>dbOf(env.authenticatedContext(uid,{email:uid+'@example.test'}));
const trusted=(action:(db:Firestore)=>Promise<void>)=>env.withSecurityRulesDisabled(c=>action(dbOf(c)));
beforeAll(async()=>{if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:28090')throw Error('Isolated S4 only');env=await initializeTestEnvironment({projectId:'demo-evertrace-spark-test',firestore:{host:'127.0.0.1',port:28090,rules:readFileSync('firebase/spark.rules','utf8')}});});
beforeEach(async()=>{await env.clearFirestore();await trusted(async db=>{await seedS1(db,2);const b=writeBatch(db);for(const id of ['source','target']){b.set(doc(db,'categories',id),{name:id,status:'active',createdBy:'member',createdAt:Timestamp.fromMillis(1)});b.set(doc(db,'categoryStats',id),{packCount:0,revision:0,packId:'',operationId:'',kind:'init',updatedAt:Timestamp.fromMillis(1)});b.set(doc(db,'categoryKeys',id),{categoryId:id});}await b.commit();});});
afterAll(async()=>{await env?.clearFirestore();await env?.cleanup();});
async function fixture(count=12,ownerId='member') {const bundle=packBundle(count,64,{ownerId,ownerName:'Spark '+ownerId,categoryId:'source'});await trusted(async db=>{const b=writeBatch(db);addBundle(b,db,bundle);const ledger=await getDoc(doc(db,'categoryStats','source'));b.update(doc(db,'categoryStats','source'),{packCount:ledger.get('packCount')+1});await b.commit();});return bundle;}
async function state(id:string){let data:unknown;await trusted(async db=>{data={root:(await getDoc(doc(db,'packs',id))).data(),files:(await getDocs(collection(db,'packs',id,'files'))).docs.map(d=>[d.id,d.data()]),groups:(await getDocs(collection(db,'packs',id,'groups'))).docs.map(d=>[d.id,d.data()])};});return data;}
async function count(id='source'){let n:number=0;await trusted(async db=>{n=(await getDoc(doc(db,'categoryStats',id))).get('packCount');});return n;}
it('author starts deletion, immediately revokes viewer bytes and completes all twelve originals and groups',async()=>{const f=await fixture();const op=await beginSparkPackDelete(client('member'),'member',f.id,1,f.id);expect(op).toMatchObject({id:'pack-'+f.id,status:'pending',ownerId:'member'});await expect(getDoc(doc(client('viewer'),'packs',f.id,'files','0'))).rejects.toMatchObject({code:'permission-denied'});expect(await count()).toBe(1);expect(await resumeSparkOperation(client('member'),'member',op.id)).toMatchObject({status:'done'});expect(await state(f.id)).toEqual({root:undefined,files:[],groups:[]});expect(await count()).toBe(0);});
it('administrator deletes another author while foreign member cannot start or recover that deletion',async()=>{const f=await fixture();const before=await state(f.id);await expect(beginSparkPackDelete(client('viewer'),'viewer',f.id,1,f.id)).rejects.toMatchObject({code:'forbidden'});expect(await state(f.id)).toEqual(before);const op=await beginSparkPackDelete(client('admin'),'admin',f.id,1,f.id);await expect(resumeSparkOperation(client('viewer'),'viewer',op.id)).rejects.toMatchObject({code:'forbidden'});await resumeSparkOperation(client('admin2'),'admin2',op.id);expect(await count()).toBe(0);});
it('wrong confirmation or stale version never marks the saved pack deleting',async()=>{const f=await fixture();const before=await state(f.id);await expect(beginSparkPackDelete(client('member'),'member',f.id,1,'different')).rejects.toMatchObject({code:'confirmation'});await expect(beginSparkPackDelete(client('member'),'member',f.id,2,f.id)).rejects.toMatchObject({code:'versionConflict'});expect(await state(f.id)).toEqual(before);});
it('interruption after group zero leaves pending cleanup; refreshed owner resumes precisely without double counting',async()=>{const f=await fixture();const op=await beginSparkPackDelete(client('member'),'member',f.id,1,f.id);await expect(resumeSparkOperation(client('member'),'member',op.id,p=>{if(p.phase==='group-0')throw Error('Synthetic closed tab');})).rejects.toThrow('Synthetic closed tab');const saved=await state(f.id) as {files:unknown[];groups:unknown[]};expect(saved.files).toHaveLength(6);expect(saved.groups).toHaveLength(1);expect(await count()).toBe(1);await resumeSparkOperation(client('member'),'member',op.id);await resumeSparkOperation(client('member'),'member',op.id);expect(await count()).toBe(0);});
it('simultaneous begin and resume requests commit one tombstone and one counted deletion',async()=>{const f=await fixture();const [a,b]=await Promise.all([beginSparkPackDelete(client('member'),'member',f.id,1,f.id),beginSparkPackDelete(client('member'),'member',f.id,1,f.id)]);expect(a.id).toBe(b.id);const done=await Promise.all([resumeSparkOperation(client('member'),'member',a.id),resumeSparkOperation(client('admin'),'admin',b.id)]);expect(done.every(x=>x.status==='done')).toBe(true);expect(await count()).toBe(0);});
it('completed deletion replay confirms its receipt without restoring the pack or original bytes',async()=>{const f=await fixture(3);const op=await beginSparkPackDelete(client('member'),'member',f.id,1,f.id);await resumeSparkOperation(client('member'),'member',op.id);expect((await beginSparkPackDelete(client('member'),'member',f.id,1,f.id)).status).toBe('done');expect(await state(f.id)).toEqual({root:undefined,files:[],groups:[]});});
it('renaming preserves category ID, protects concurrent unique names and permits old name reuse',async()=>{const f=await fixture(3);await renameSparkCategory(client('admin'),'admin','source','Renamed Source','source');expect((await getDoc(doc(client('member'),'packs',f.id))).get('categoryId')).toBe('source');await expect(renameSparkCategory(client('admin'),'admin','source','target','Renamed Source')).rejects.toMatchObject({code:'categoryExists'});const reused=await createSparkCategory(client('member'),'member','source');expect(reused.id).not.toBe('source');expect(reused.created).toBe(true);expect((await createSparkCategory(client('member'),'member','RENAMED SOURCE')).id).toBe('source');});
it('member rename is forbidden and stale expected name preserves current category',async()=>{await expect(renameSparkCategory(client('member'),'member','source','bad','source')).rejects.toMatchObject({code:'forbidden'});await renameSparkCategory(client('admin'),'admin','source','first','source');await expect(renameSparkCategory(client('admin'),'admin','source','second','source')).rejects.toMatchObject({code:'categoryChanged'});});
it('a category with existing packs requires a different active target',async()=>{await fixture(3);await expect(beginSparkCategoryDelete(client('admin'),'admin','source','','source')).rejects.toMatchObject({code:'targetRequired'});await expect(beginSparkCategoryDelete(client('admin'),'admin','source','source','source')).rejects.toMatchObject({code:'categoryUnavailable'});expect((await getDoc(doc(client('member'),'categories','source'))).get('status')).toBe('active');});
it('locking and migration preserve all original byte documents, owner, version and creation time',async()=>{const a=await fixture(),b=await fixture(3),beforeA=await state(a.id) as {root:Record<string,unknown>;files:unknown[];groups:unknown[]},beforeB=await state(b.id) as {files:unknown[]};const op=await beginSparkCategoryDelete(client('admin'),'admin','source','target','source');expect((await getDoc(doc(client('member'),'categories','source'))).get('status')).toBe('migrating');expect((await getDoc(doc(client('member'),'categories','target'))).get('status')).toBe('locked');const done=await resumeSparkOperation(client('admin2'),'admin2',op.id);expect(done).toMatchObject({status:'done',moved:2});expect(await count('target')).toBe(2);const after=await state(a.id) as typeof beforeA;expect(after.files).toEqual(beforeA.files);expect(after.groups).toEqual(beforeA.groups);expect(after.root).toMatchObject({categoryId:'target',version:1,ownerId:beforeA.root.ownerId,createdAt:beforeA.root.createdAt});expect((await state(b.id) as typeof beforeB).files).toEqual(beforeB.files);expect((await getDoc(doc(client('member'),'categories','source'))).exists()).toBe(false);});
it('interrupted migration keeps both locks and remaining original files, then resumes with another administrator',async()=>{const a=await fixture(3),b=await fixture(3);const op=await beginSparkCategoryDelete(client('admin'),'admin','source','target','source');await expect(resumeSparkOperation(client('admin'),'admin',op.id,p=>{if(p.phase==='moving')throw Error('Synthetic network interruption');})).rejects.toThrow('Synthetic network interruption');expect(await count('source')).toBe(1);expect(await count('target')).toBe(1);await resumeSparkOperation(client('admin2'),'admin2',op.id);expect(await count('target')).toBe(2);for(const f of [a,b])expect((await state(f.id) as {files:unknown[]}).files).toHaveLength(3);});
it('a preexisting pending pack deletion can finish under classification locks without deadlocking count',async()=>{const f=await fixture(3);const deletion=await beginSparkPackDelete(client('member'),'member',f.id,1,f.id);const migration=await beginSparkCategoryDelete(client('admin'),'admin','source','target','source');await resumeSparkOperation(client('admin'),'admin',migration.id);expect(await count('target')).toBe(0);expect((await getDoc(doc(client('admin'),'sparkOperations',deletion.id))).get('status')).toBe('done');});
it('deleting an empty category needs no target and releases the name for a fresh ID',async()=>{const op=await beginSparkCategoryDelete(client('admin'),'admin','source','','source');expect((await resumeSparkOperation(client('admin'),'admin',op.id)).status).toBe('done');const result=await createSparkCategory(client('member'),'member','source');expect(result.created).toBe(true);expect(result.id).not.toBe('source');});
it('missing trusted counter baseline blocks category deletion rather than trusting a client count',async()=>{await trusted(db=>setDoc(doc(db,'categories','uninitialized'),{name:'uninitialized',status:'active',createdBy:'member',createdAt:Timestamp.fromMillis(1)}));await expect(beginSparkCategoryDelete(client('admin'),'admin','uninitialized','','uninitialized')).rejects.toMatchObject({code:'baselineRequired'});});
it('administrator losing role before resume cannot continue a category migration',async()=>{await fixture(3);const op=await beginSparkCategoryDelete(client('admin'),'admin','source','target','source');await trusted(db=>setDoc(doc(db,'users','admin'),{uid:'admin',email:'admin@example.test',displayName:'Spark admin',role:'member'}));await expect(resumeSparkOperation(client('admin'),'admin',op.id)).rejects.toMatchObject({code:'forbidden'});expect(await count()).toBe(1);await resumeSparkOperation(client('admin2'),'admin2',op.id);});
