import { readFileSync } from 'node:fs';
import { beforeAll,beforeEach,afterAll,it,expect } from 'vitest';
import { initializeTestEnvironment,type RulesTestEnvironment } from '@firebase/rules-unit-testing';
import { initializeApp,deleteApp,type App } from 'firebase-admin/app';
import { getFirestore,type Firestore } from 'firebase-admin/firestore';
import { initializeSparkSchema } from '../../scripts/initialize-spark-schema.mjs';
let env:RulesTestEnvironment,app:App,db:Firestore;
beforeAll(async()=>{if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:28090')throw Error('Isolated S4 only');env=await initializeTestEnvironment({projectId:'demo-evertrace-spark-test',firestore:{host:'127.0.0.1',port:28090,rules:readFileSync('firebase/spark.rules','utf8')}});app=initializeApp({projectId:'demo-evertrace-spark-test'},'S4-baseline');db=getFirestore(app);});
beforeEach(async()=>{await env.clearFirestore();await db.doc('categories/source').set({name:'Source',status:'active',createdBy:'member',createdAt:'synthetic-preserved'});await db.doc('packs/original').set({categoryId:'source',status:'ready',version:7,textContent:'Keep exact original root'});});
afterAll(async()=>{await env?.clearFirestore();await env?.cleanup();if(app)await deleteApp(app);});
async function all(){return Object.fromEntries(await Promise.all(['categories','packs','categoryStats','categoryKeys','sparkOperations'].map(async id=>[id,(await db.collection(id).get()).docs.map(d=>[d.id,d.data()])])));}
it('trusted initializer counts existing roots and only adds baseline and unique name keys',async()=>{const before=await all();expect(await initializeSparkSchema(db)).toEqual({categories:1,packs:1,createdStats:1,createdKeys:1});const after=await all();expect(after.categories).toEqual(before.categories);expect(after.packs).toEqual(before.packs);expect(after.categoryStats).toEqual([['source',expect.objectContaining({packCount:1,revision:0,packId:'',operationId:'',kind:'init'})]]);expect(after.categoryKeys).toEqual([['source',{categoryId:'source'}]]);});
it('repeated preparation preserves initialized revisions rather than resetting an active ledger',async()=>{await initializeSparkSchema(db);await db.doc('categoryStats/source').update({revision:9,packId:'original',operationId:'original-op',kind:'movePack'});const before=await all();expect(await initializeSparkSchema(db)).toEqual({categories:1,packs:1,createdStats:0,createdKeys:0});expect(await all()).toEqual(before);});
it('duplicate active names are refused without partial baseline writes',async()=>{await db.doc('categories/second').set({name:'SOURCE',status:'active'});const before=await all();await expect(initializeSparkSchema(db)).rejects.toThrow('unique');expect(await all()).toEqual(before);});
it('orphan references require investigation and never become a false zero count',async()=>{await db.doc('packs/orphan').set({categoryId:'missing',status:'ready'});const before=await all();await expect(initializeSparkSchema(db)).rejects.toThrow('reference');expect(await all()).toEqual(before);});
it('a pending cleanup or migration blocks preparation while users must finish it first',async()=>{await db.doc('sparkOperations/pending').set({status:'pending'});const before=await all();await expect(initializeSparkSchema(db)).rejects.toThrow('pending');expect(await all()).toEqual(before);});
it('an inconsistent initialized ledger is refused instead of overwritten',async()=>{await db.doc('categoryStats/source').set({packCount:0,revision:7});const before=await all();await expect(initializeSparkSchema(db)).rejects.toThrow('inconsistent');expect(await all()).toEqual(before);});
it('a conflicting key reservation is refused instead of redirecting an existing category',async()=>{await db.doc('categoryKeys/source').set({categoryId:'other'});const before=await all();await expect(initializeSparkSchema(db)).rejects.toThrow('inconsistent');expect(await all()).toEqual(before);});
