import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import {existsSync,mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
const fixture=`VITE_DATA_BACKEND=spark\nVITE_USE_EMULATORS=false\nVITE_FIREBASE_PROJECT_ID=evertrace-spark-release-test\nVITE_FIREBASE_API_KEY=synthetic-public-key\nVITE_FIREBASE_AUTH_DOMAIN=evertrace-spark-release-test.firebaseapp.com\nVITE_FIREBASE_APP_ID=1:123:web:synthetic\n`;
async function config(){const path='../../scripts/spark-release-config.mjs';return import(path);}
describe('Spark release preflight',()=>{
 it('requires Spark, cloud mode and an exact real deployment project; Storage and Functions are unnecessary',async()=>{const {sparkCloudSettings}=await config();expect(sparkCloudSettings(fixture,'evertrace-spark-release-test')).toMatchObject({projectId:'evertrace-spark-release-test',env:{VITE_DATA_BACKEND:'spark',VITE_USE_EMULATORS:'false'}});});
 it.each(['VITE_DATA_BACKEND=spark','VITE_USE_EMULATORS=false','VITE_FIREBASE_API_KEY=synthetic-public-key','VITE_FIREBASE_AUTH_DOMAIN=evertrace-spark-release-test.firebaseapp.com','VITE_FIREBASE_APP_ID=1:123:web:synthetic'])('refuses missing required setting %s before publishing',async(line)=>{const {sparkCloudSettings}=await config();expect(()=>sparkCloudSettings(fixture.replace(line,''),'evertrace-spark-release-test')).toThrow();});
 it('refuses local/demo/legacy modes and mismatched targets',async()=>{const {sparkCloudSettings}=await config();for(const [text,id] of [[fixture,'other-project'],[fixture.replace('spark\n','legacy\n'),'evertrace-spark-release-test'],[fixture.replace('false','true'),'evertrace-spark-release-test'],[fixture.replaceAll('evertrace-spark-release-test','demo-evertrace-spark'),'demo-evertrace-spark']])expect(()=>sparkCloudSettings(text,id)).toThrow();});
 it('forwards only required public Web settings, never unrelated secrets or stale emulator ports',async()=>{const {sparkCloudSettings}=await config();const settings=sparkCloudSettings(fixture+'PRIVATE_KEY=never-forward\nVITE_AUTH_EMULATOR_PORT=9099\nVITE_FIREBASE_STORAGE_BUCKET=old-bucket\nFUNCTIONS_REGION=asia-east1\n','evertrace-spark-release-test');expect(Object.keys(settings.env).sort()).toEqual(['VITE_DATA_BACKEND','VITE_FIREBASE_API_KEY','VITE_FIREBASE_APP_ID','VITE_FIREBASE_AUTH_DOMAIN','VITE_FIREBASE_PROJECT_ID','VITE_USE_EMULATORS']);});
 it('pins the deployment config and service allowlist',async()=>{const {sparkDeployArgs}=await config();expect(sparkDeployArgs('evertrace-spark-release-test')).toEqual(['deploy','--project','evertrace-spark-release-test','--config','firebase.spark.cloud.json','--only','firestore:rules,firestore:indexes,hosting']);expect(()=>sparkDeployArgs('demo-evertrace-spark')).toThrow();});
});
it('Hosting has SPA refresh, current Spark rules/indexes and no paid service sections',()=>{const file='firebase.spark.cloud.json',cfg=existsSync(file)?JSON.parse(readFileSync(file,'utf8')):{};expect(cfg).toMatchObject({firestore:{rules:'firebase/spark.rules',indexes:'firebase/spark.indexes.json'},hosting:{public:'apps/web/dist-spark',rewrites:[{source:'**',destination:'/index.html'}]}});expect(Object.keys(cfg).sort()).toEqual(['firestore','hosting']);});
let directory:string;
beforeAll(()=>{directory=mkdtempSync(join(tmpdir(),'spark-production-'));const env=Object.fromEntries(fixture.trim().split('\n').map(line=>line.split('=')));execFileSync(process.execPath,[resolve('node_modules/vite/bin/vite.js'),'build','--mode','spark-cloud','--manifest','--outDir',directory],{cwd:resolve('apps/web'),env:{...process.env,...env,NODE_ENV:'production'},stdio:'pipe'});},30000);
afterAll(()=>{if(directory)rmSync(directory,{recursive:true,force:true});});
it('production output contains no legacy route chunks, Storage or callable modules',()=>{const manifest=JSON.parse(readFileSync(join(directory,'.vite/manifest.json'),'utf8'));for(const legacy of ['src/pages/CreatePackPage.tsx','src/pages/PacksPage.tsx','src/pages/PackDetailPage.tsx','src/pages/CategoriesPage.tsx','src/pages/MembersPage.tsx'])expect(manifest[legacy]).toBeUndefined();const auditPath=join(directory,'spark-build-audit.json');expect(existsSync(auditPath)).toBe(true);const audit=JSON.parse(readFileSync(auditPath,'utf8'));expect(audit.forbiddenModules).toEqual([]);expect(audit.mode).toBe('spark-cloud');expect(audit.emulators).toBe(false);expect(audit.backend).toBe('spark');expect(audit.modules.some((id:string)=>id.includes('@firebase/firestore'))).toBe(true);expect(audit.modules.some((id:string)=>id.includes('@firebase/auth'))).toBe(true);});
it('homepage stays under 500 KiB and leaves material workflows lazy',()=>{const manifest=JSON.parse(readFileSync(join(directory,'.vite/manifest.json'),'utf8'));const visited=new Set<string>();const visit=(key:string)=>{if(visited.has(key))return;visited.add(key);for(const dep of manifest[key].imports??[])visit(dep);};const entry=Object.keys(manifest).find(k=>manifest[k].isEntry)!;visit(entry);expect([...visited].reduce((n,k)=>n+readFileSync(join(directory,manifest[k].file)).length,0)).toBeLessThanOrEqual(500*1024);expect(manifest[entry].dynamicImports.length).toBeGreaterThanOrEqual(4);});
it('the same Spark-only route assembly is available for full isolated emulator regression',()=>{const dir=mkdtempSync(join(tmpdir(),'spark-entry-regression-'));try{execFileSync(process.execPath,[resolve('node_modules/vite/bin/vite.js'),'build','--mode','spark-test','--outDir',dir],{cwd:resolve('apps/web'),env:{...process.env,NODE_ENV:'production',VITE_DATA_BACKEND:'spark',VITE_USE_EMULATORS:'true',VITE_FIREBASE_PROJECT_ID:'demo-evertrace-spark-test',VITE_AUTH_EMULATOR_PORT:'29099',VITE_FIRESTORE_EMULATOR_PORT:'28090'},stdio:'pipe'});const file=join(dir,'spark-build-audit.json');expect(existsSync(file)).toBe(true);expect(JSON.parse(readFileSync(file,'utf8'))).toMatchObject({backend:'spark',mode:'spark-test',emulators:true,forbiddenModules:[]});}finally{rmSync(dir,{recursive:true,force:true});}});
it('cloud release refuses an Auth domain containing a URL, local host or credentials',async()=>{const {sparkCloudSettings}=await config();for(const domain of ['http://localhost:5175','127.0.0.1','https://app.example.com/path','user:secret@app.example.com'])expect(()=>sparkCloudSettings(fixture.replace('evertrace-spark-release-test.firebaseapp.com',domain),'evertrace-spark-release-test')).toThrow();});
it('the emulator-only built regression entry refuses real cloud settings',()=>{const dir=mkdtempSync(join(tmpdir(),'spark-test-guard-'));try{const env=Object.fromEntries(fixture.trim().split('\n').map(line=>line.split('=')));expect(()=>execFileSync(process.execPath,[resolve('node_modules/vite/bin/vite.js'),'build','--mode','spark-test','--outDir',dir],{cwd:resolve('apps/web'),env:{...process.env,...env,NODE_ENV:'production'},stdio:'pipe'})).toThrow();}finally{rmSync(dir,{recursive:true,force:true});}});
