import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { collection, onSnapshot } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { useTranslation } from 'react-i18next';
import { db, functions } from '../app/legacy-firebase';
import { AccountLayout } from '../components/AccountLayout';
import { MemberBar } from '../components/MemberBar';
import { ConfirmationDialog, PendingOperations, managementError, type ManagementResult } from '../components/ManagementControls';
type Category={id:string;name:string;status:string;packCount:number;incomingOperation?:string};
export function CategoriesPage(){
 const {t}=useTranslation(),[categories,setCategories]=useState<Category[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false),[retry,setRetry]=useState(0),[newName,setNewName]=useState(''),[adding,setAdding]=useState(false),[addError,setAddError]=useState('');
 const [selected,setSelected]=useState<Category|null>(null),[action,setAction]=useState<'rename'|'delete'>('rename'),[name,setName]=useState(''),[target,setTarget]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const operation=useRef(''),inFlight=useRef(false),alive=useRef(true),addBusy=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{setLoading(true);setLoadError(false);return onSnapshot(collection(db,'categories'),saved=>{setCategories(saved.docs.map(d=>({id:d.id,...d.data()} as Category)).sort((a,b)=>a.name.localeCompare(b.name)));setLoading(false);},()=>{setLoadError(true);setLoading(false);});},[retry]);
 function open(category:Category,next:'rename'|'delete'){setSelected(category);setAction(next);setName(category.name);setTarget('');setConfirmed(false);setError('');setNotice('');operation.current=crypto.randomUUID();}
 async function add(event:FormEvent){event.preventDefault();if(addBusy.current)return;addBusy.current=true;setAdding(true);setAddError('');try{await httpsCallable(functions,'createCategory')({name:newName});if(alive.current)setNewName('');}catch(e){if(alive.current)setAddError(managementError(e));}finally{addBusy.current=false;if(alive.current)setAdding(false);}}
 async function submit(){if(!selected||inFlight.current||action==='delete'&&(!confirmed||selected.packCount>0&&!target))return;inFlight.current=true;setBusy(true);setError('');try{if(action==='rename')await httpsCallable(functions,'renameCategory')({categoryId:selected.id,name,expectedName:selected.name});else{const result=await httpsCallable<Record<string,unknown>,ManagementResult>(functions,'deleteCategory')({sourceId:selected.id,targetId:target||undefined,confirmation:selected.id,operationId:operation.current});if(alive.current)setNotice(result.data.status==='done'?'management.categoryDeleted':'management.pending');}if(alive.current)setSelected(null);}catch(e){if(alive.current)setError(managementError(e));}finally{inFlight.current=false;if(alive.current)setBusy(false);}}
 return <AccountLayout><MemberBar/><h1>{t('management.categoriesTitle')}</h1><p>{t('management.categoriesHint')}</p><PendingOperations/><form className="category-create" onSubmit={event=>void add(event)}><label htmlFor="admin-new-category">{t('form.newCategory')}</label><div><input id="admin-new-category" value={newName} maxLength={60} disabled={adding} onChange={event=>setNewName(event.target.value)}/><button className="button" disabled={adding||!newName.trim()}>{t(adding?'account.working':'form.addCategory')}</button></div>{addError&&<p role="alert">{t(addError)}</p>}</form>
 {loading&&<p role="status">{t('form.categoriesLoading')}</p>}{loadError&&<div role="alert"><p>{t('form.categoriesError')}</p><button className="button" onClick={()=>setRetry(n=>n+1)}>{t('account.retry')}</button></div>}{!loading&&!loadError&&!categories.length&&<p>{t('form.noCategories')}</p>}{notice&&<p role="status">{t(notice)}</p>}
 <div className="category-list">{categories.map(category=><article key={category.id}><h2>{category.name}</h2><p>{t('management.packCount',{count:category.packCount??0})}</p>{(category.status!=='active'||category.incomingOperation)&&<p>{t('management.categoryLocked')}</p>}<div className="account-actions"><button className="button" disabled={category.status!=='active'||Boolean(category.incomingOperation)} onClick={()=>open(category,'rename')}>{t('management.rename')}</button><button className="button button-danger" disabled={category.status!=='active'||Boolean(category.incomingOperation)} onClick={()=>open(category,'delete')}>{t('management.deleteCategory')}</button></div></article>)}</div>
 {selected&&<ConfirmationDialog title={t(action==='rename'?'management.renameCategory':'management.deleteCategory')} busy={busy} onClose={()=>setSelected(null)}><p className="management-target">{selected.name}</p><fieldset disabled={busy}>{action==='rename'?<><label htmlFor="category-name">{t('management.categoryName')}</label><input id="category-name" value={name} maxLength={60} onChange={event=>setName(event.target.value)}/></>:<><p className="management-warning">{t('management.categoryWarning')}</p>{selected.packCount>0&&<p>{t('management.moveHint',{count:selected.packCount})}</p>}<label htmlFor="migration-target">{t('management.moveTo')}</label><select id="migration-target" value={target} onChange={event=>setTarget(event.target.value)}><option value="">{t(selected.packCount>0?'management.chooseTarget':'management.noTargetNeeded')}</option>{categories.filter(c=>c.id!==selected.id&&c.status==='active'&&!c.incomingOperation).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><label className="management-confirm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>{t('management.categoryUnderstand')}</label></>}{error&&<p role="alert">{t(error)}</p>}{busy&&<p role="status">{t('account.working')}</p>}<div className="account-actions"><button className="button" onClick={()=>setSelected(null)}>{t('management.cancel')}</button><button className={'button '+(action==='delete'?'button-danger':'button-dark')} disabled={action==='rename'?!name.trim():!confirmed||selected.packCount>0&&!target} onClick={()=>void submit()}>{t(action==='rename'?'management.saveName':'management.deleteCategory')}</button></div></fieldset></ConfirmationDialog>}
 <Link className="pack-back" to="/packs">{t('browseTitle')} ↗</Link></AccountLayout>;
}
