import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { collection, doc, getDoc, getDocs, onSnapshot, query, where } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { FirebaseError } from 'firebase/app';
import { PREVIEW_LIMITS, ATTACHMENT_LIMITS, checkImageHeader, validatePackInput, validateText, type EegResult, type Issue, type FileKind, type StoredFile } from '@evertrace/shared';
import { db, functions } from '../app/firebase';
import { useAuth } from '../app/AuthProvider';
import { AccountLayout } from '../components/AccountLayout';
import { MemberBar } from '../components/MemberBar';
import { EegPreview } from '../components/EegPreview';
import { IssueList } from '../components/IssueList';
import { StoredMaterial } from './PackDetailPage';
import { saveMaterials, type SaveAttempt } from '../services/save-materials';
type Category={id:string;name:string};
type Material={key:string;kind:FileKind;file:File;busy:boolean;issues:Issue[];eeg?:EegResult};
function LocalImage({file}:{file:File}){const [url,setUrl]=useState('');useEffect(()=>{const value=URL.createObjectURL(file);setUrl(value);return()=>URL.revokeObjectURL(value);},[file]);return url?<img className="pack-image" src={url} alt={file.name}/>:null;}
export function CreatePackPage({edit=false}:{edit?:boolean}){
  const {t}=useTranslation(),navigate=useNavigate(),{id}=useParams(),access=useAuth();
  const [loadStatus,setLoadStatus]=useState(edit?'loading':'ready'),[version,setVersion]=useState(0),[reload,setReload]=useState(0),[retained,setRetained]=useState<StoredFile[]>([]);
  const [title,setTitle]=useState(''),[notes,setNotes]=useState(''),[categoryId,setCategoryId]=useState(''),[newCategory,setNewCategory]=useState('');
  const [categories,setCategories]=useState<Category[]>([]),[categoryStatus,setCategoryStatus]=useState<'loading'|'ready'|'error'>('loading'),[categoryRetry,setCategoryRetry]=useState(0),[adding,setAdding]=useState(false),[categoryError,setCategoryError]=useState(''),[categoryNotice,setCategoryNotice]=useState('');
  const [materials,setMaterials]=useState<Material[]>([]),[formIssues,setFormIssues]=useState<Issue[]>([]),[checked,setChecked]=useState(false),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(''),[progress,setProgress]=useState<{phase:string;file?:string;percent?:number}|null>(null);
  const alive=useRef(true),saveBusy=useRef(false),saveController=useRef<AbortController|null>(null),saveAttempt=useRef<SaveAttempt|null>(null),workers=useRef(new Map<string,Worker>());
  const inputs=useRef<Partial<Record<FileKind,HTMLInputElement|null>>>({});
  const changed=()=>{setChecked(false);setFormIssues([]);setSaveError('');};
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;saveController.current?.abort();for(const w of workers.current.values())w.terminate();workers.current.clear();};},[]);
  useEffect(()=>onSnapshot(query(collection(db,'categories'),where('status','==','active')),snapshot=>{setCategories(snapshot.docs.map(d=>({id:d.id,name:String(d.get('name'))})).sort((a,b)=>a.name.localeCompare(b.name)));setCategoryStatus('ready');setChecked(false);},()=>setCategoryStatus('error')),[categoryRetry]);
  useEffect(()=>{if(!edit)return;let active=true;setLoadStatus('loading');setMaterials([]);setRetained([]);saveAttempt.current=null;setSaveError('');setFormIssues([]);setChecked(false);
    void getDoc(doc(db,'packs',id!)).then(async pack=>{if(!active)return;if(!pack.exists()){setLoadStatus('missing');return;}if(pack.get('ownerId')!==access.user?.uid&&access.profile?.role!=='admin'){setLoadStatus('denied');return;}const files=await getDocs(query(collection(db,'packs',id!,'files'),where('active','==',true))),latest=await getDoc(doc(db,'packs',id!));if(!active)return;if(latest.get('version')!==pack.get('version'))throw new Error('changed');setTitle(pack.get('title'));setNotes(pack.get('textContent'));setCategoryId(pack.get('categoryId'));setVersion(pack.get('version'));setRetained(files.docs.map(d=>({id:d.id,...d.data()} as StoredFile)));setLoadStatus('ready');}).catch(()=>{if(active)setLoadStatus('error');});return()=>{active=false;};
  },[edit,id,reload,access.user?.uid,access.profile?.role]);
  async function addCategory(){if(adding)return;setCategoryError('');setCategoryNotice('');setAdding(true);try{const result=await httpsCallable<{name:string},{id:string;name:string;created:boolean}>(functions,'createCategory')({name:newCategory});setCategories(previous=>previous.some(x=>x.id===result.data.id)?previous:[...previous,{id:result.data.id,name:result.data.name}]);setCategoryId(result.data.id);setNewCategory('');setCategoryNotice(result.data.created?'form.categoryAdded':'form.categoryExists');changed();}catch(error){setCategoryError(error instanceof FirebaseError&&error.code==='functions/invalid-argument'?'validation.categoryInvalid':'form.categoryError');}finally{setAdding(false);}}
  async function checkFile(material:Material){const {file,kind,key}=material;let issues:Issue[]=[],eeg:EegResult|undefined;
    try{const max=kind==='eeg'?PREVIEW_LIMITS.excelBytes:kind==='text'?PREVIEW_LIMITS.textBytes:ATTACHMENT_LIMITS.imageBytes;if(file.size>max)issues=[{code:kind==='eeg'?'fileSize':kind==='text'?'textSize':'imageSize',file:file.name}];else if(kind==='eeg'&&!/\.xlsx$/i.test(file.name))issues=[{code:'fileType',file:file.name}];else{const bytes=new Uint8Array(await file.arrayBuffer());if(!alive.current)return;if(kind==='text')issues=validateText(bytes,file.name).issues;else if(kind==='image'){issues=checkImageHeader(bytes,file.name);if(!issues.length){try{const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>ATTACHMENT_LIMITS.imagePixels)issues=[{code:'imageInvalid',file:file.name}];bitmap.close();}catch{issues=[{code:'imageInvalid',file:file.name}];}}}else{eeg=await new Promise<EegResult>(resolve=>{const w=new Worker(new URL('../workers/eeg.worker.ts',import.meta.url),{type:'module'});workers.current.set(key,w);const finish=(result:EegResult)=>{clearTimeout(timer);w.terminate();workers.current.delete(key);resolve(result);};const timer=setTimeout(()=>finish({ok:false,issues:[{code:'parseTimeout',file:file.name}]}),PREVIEW_LIMITS.parseMs);w.onmessage=(event:MessageEvent<EegResult>)=>finish(event.data);w.onerror=()=>finish({ok:false,issues:[{code:'fileRead',file:file.name}]});w.postMessage({bytes,name:file.name},[bytes.buffer]);});issues=eeg.issues;}}}catch{issues=[{code:'fileRead',file:file.name}];}
    if(alive.current)setMaterials(previous=>previous.map(m=>m.key===key?{...m,busy:false,issues,eeg}:m));
  }
  function choose(kind:FileKind,files:File[],replace?:string){changed();const added=files.map(file=>({key:crypto.randomUUID(),kind,file,busy:true,issues:[]}));if(replace){setRetained(previous=>previous.filter(f=>f.id!==replace));setMaterials(previous=>[...previous,...added]);}else setMaterials(previous=>[...previous.filter(m=>m.kind!==kind),...added]);for(const m of added)void checkFile(m);}
  function remove(key:string){changed();workers.current.get(key)?.terminate();workers.current.delete(key);setMaterials(previous=>previous.filter(m=>m.key!==key));}
  function currentIssues(){const valid=materials.filter(m=>!m.busy&&!m.issues.length),category=categories.some(c=>c.id===categoryId)?categoryId:'';const issues=validatePackInput({title,categoryId:category,text:notes,textFileValid:retained.some(f=>f.kind==='text')||valid.some(f=>f.kind==='text'),eegValid:retained.some(f=>f.kind==='eeg')||valid.some(f=>f.kind==='eeg')});issues.push(...materials.flatMap(m=>m.busy?[{code:'checking',file:m.file.name}]:m.issues));if(retained.length+materials.length>ATTACHMENT_LIMITS.count||[...retained,...materials.map(m=>({size:m.file.size}))].reduce((n,f)=>n+f.size,0)>ATTACHMENT_LIMITS.totalBytes)issues.push({code:'attachmentLimit'});return issues;}
  function check(event:FormEvent){event.preventDefault();const issues=currentIssues();setFormIssues(issues);setChecked(!issues.length);}
  const busy=materials.some(m=>m.busy);
  async function save(){if(saveBusy.current||busy)return;const issues=currentIssues();setFormIssues(issues);setSaveError('');if(issues.length)return;saveBusy.current=true;setSaving(true);const controller=new AbortController();saveController.current=controller;try{const result=await saveMaterials({title,categoryId,textContent:notes,attachments:materials.map(m=>({file:m.file,kind:m.kind})),...(edit?{packId:id!,expectedVersion:version,retainedFileIds:retained.map(f=>f.id)}:{})},saveAttempt,state=>{if(alive.current)setProgress(state);},controller.signal);if(alive.current)navigate('/packs/'+result.packId);}catch(error){if(!alive.current)return;const detail=error instanceof FirebaseError?(error as FirebaseError&{details?:{code?:string;issues?:Issue[]}}).details:undefined;if(detail?.code==='sessionExpired')saveAttempt.current=null;if(detail?.issues)setFormIssues(detail.issues);setSaveError(error instanceof Error&&error.message==='uploadFailed'?'packs.uploadError':detail?.code==='versionConflict'?'packs.versionConflict':error instanceof FirebaseError&&error.code==='functions/permission-denied'?'packs.editDenied':detail?.code==='saveBusy'?'packs.saveBusy':detail?.code==='categoryUnavailable'?'packs.categoryBusy':detail?.code==='sessionExpired'?'packs.sessionExpired':detail?.code==='fileChanged'?'packs.fileChanged':'packs.saveError');}finally{saveBusy.current=false;if(alive.current){setSaving(false);setProgress(null);}}}
  function group(kind:FileKind){const selected=materials.filter(m=>m.kind===kind),label=kind==='text'?'form.textFile':kind==='eeg'?'form.eegFile':'form.images',inputId='pack-'+(kind==='eeg'?'eeg':kind==='text'?'text':'images');return <><label htmlFor={inputId}>{t(label)}</label><div className="file-picker"><span className="picker-action">{t('form.chooseFile')}</span><span className="picker-name">{selected.length?selected.map(m=>m.file.name).join(', '):t('form.noFile')}</span><input id={inputId} ref={el=>{inputs.current[kind]=el;}} type="file" multiple accept={kind==='text'?'.txt':kind==='eeg'?'.xlsx':'.jpg,.jpeg,.png,.webp'} onChange={event=>choose(kind,Array.from(event.target.files??[]))}/></div><p className="field-note">{t('form.multipleHint')}</p>{selected.map(m=><div className="attachment-card" key={m.key}><h3>{m.file.name}</h3>{m.busy&&<p role="status">{t(kind==='text'?'form.checkingText':kind==='eeg'?'form.checkingEeg':'form.checkingImage')}</p>}<IssueList issues={m.issues}/>{!m.busy&&!m.issues.length&&(kind==='text'?<p className="file-valid">{t('form.textValid')} · {m.file.name}</p>:kind==='image'?<LocalImage file={m.file}/>:m.eeg&&<EegPreview result={m.eeg}/>)}<button className="file-remove" type="button" onClick={()=>{remove(m.key);if(selected.length===1&&inputs.current[kind])inputs.current[kind]!.value='';}}>{selected.length===1&&kind!=='image'?t(kind==='text'?'form.removeText':'form.removeEeg'):t('form.removeAttachment',{name:m.file.name})}</button></div>)}</>;}
  return <AccountLayout><MemberBar/>{loadStatus==='loading'?<p role="status">{t('packs.loading')}</p>:loadStatus==='denied'?<><h1>{t('packs.editDenied')}</h1><Link to={'/packs/'+id}>{t('packs.backDetail')}</Link></>:loadStatus==='missing'?<h1>{t('packs.notFound')}</h1>:loadStatus==='error'?<div role="alert"><h1>{t('packs.detailError')}</h1><button className="button" onClick={()=>setReload(n=>n+1)}>{t('account.retry')}</button></div>:<><h1>{t(edit?'packs.edit':'createTitle')}</h1><p className="pack-intro">{t(edit?'packs.editIntro':'form.intro')}</p><div className="template-notice"><p>{t('form.templateNotice')}</p><p>{t('form.limits',{excel:PREVIEW_LIMITS.excelBytes/1024/1024,rows:PREVIEW_LIMITS.rows.toLocaleString(),text:PREVIEW_LIMITS.textBytes/1024/1024,chars:PREVIEW_LIMITS.textChars.toLocaleString()})}</p><p>{t('form.attachmentLimits',{count:ATTACHMENT_LIMITS.count,total:ATTACHMENT_LIMITS.totalBytes/1024/1024,image:ATTACHMENT_LIMITS.imageBytes/1024/1024})}</p></div>
  <form className="pack-form" onSubmit={check}><fieldset className="pack-fields" disabled={saving}>
  <section className="pack-section"><h2>{t('form.identity')}</h2><label htmlFor="pack-title">{t('form.title')}</label><input id="pack-title" value={title} maxLength={PREVIEW_LIMITS.titleChars} onChange={event=>{setTitle(event.target.value);changed();}}/><label htmlFor="pack-category">{t('form.category')}</label><select id="pack-category" disabled={categoryStatus!=='ready'} value={categoryId} onChange={event=>{setCategoryId(event.target.value);changed();}}><option value="">{t(categoryStatus==='loading'?'form.categoriesLoading':'form.chooseCategory')}</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{categoryStatus==='ready'&&!categories.length&&<p className="field-note">{t('form.noCategories')}</p>}{categoryStatus==='error'&&<div role="alert"><p>{t('form.categoriesError')}</p><button type="button" className="button" onClick={()=>{setCategoryStatus('loading');setCategoryRetry(n=>n+1);}}>{t('form.retryCategories')}</button></div>}<div className="new-category"><label htmlFor="new-category">{t('form.newCategory')}</label><div><input id="new-category" maxLength={PREVIEW_LIMITS.categoryChars} value={newCategory} onChange={event=>{setNewCategory(event.target.value);setCategoryError('');setCategoryNotice('');}}/><button type="button" className="button" disabled={adding||categoryStatus!=='ready'} onClick={()=>void addCategory()}>{t(adding?'account.working':'form.addCategory')}</button></div><p className="field-note">{t('form.sharedCategory')}</p>{categoryError&&<p role="alert">{t(categoryError)}</p>}{categoryNotice&&<p aria-live="polite">{t(categoryNotice)}</p>}</div></section>
  {edit&&retained.length>0&&<section className="pack-section"><h2>{t('packs.existingFiles')}</h2>{retained.map(file=><div className="attachment-card" key={file.id}><StoredMaterial file={file}/><div className="account-actions"><button className="file-remove" type="button" onClick={()=>{setRetained(previous=>previous.filter(f=>f.id!==file.id));changed();}}>{t('form.removeAttachment',{name:file.originalName})}</button><label className="replace-picker">{t('form.replaceAttachment',{name:file.originalName})}<input aria-label={t('form.replaceAttachment',{name:file.originalName})} type="file" accept={file.kind==='eeg'?'.xlsx':file.kind==='text'?'.txt':'.jpg,.jpeg,.png,.webp'} onChange={event=>{const replacement=event.target.files?.[0];if(replacement)choose(file.kind,[replacement],file.id);}}/></label></div></div>)}</section>}
  <section className="pack-section"><h2>{t('form.textSection')}</h2><label htmlFor="pack-notes">{t('form.notes')}</label><textarea id="pack-notes" rows={7} value={notes} maxLength={PREVIEW_LIMITS.textChars} onChange={event=>{setNotes(event.target.value);changed();}}/><p className="field-note">{t('form.textHint')}</p><div className="sample-links"><a href="/samples/synthetic-notes.txt" download>{t('form.downloadTextExample')}</a></div>{group('text')}</section>
  <section className="pack-section"><h2>{t('form.eegSection')}</h2><p className="field-note">{t('form.eegHint')}</p><div className="sample-links"><a href="/samples/synthetic-eeg-valid.xlsx" download>{t('form.downloadExample')}</a><a href="/samples/synthetic-eeg-empty-value.xlsx" download>{t('form.downloadInvalid')}</a></div>{group('eeg')}</section>
  <section className="pack-section"><h2>{t('form.imageSection')}</h2><p className="field-note">{t('form.imageHint')}</p><div className="sample-links"><a href="/samples/synthetic-image.png" download>{t('form.downloadImageExample')}</a></div>{group('image')}</section>
  <div className="pack-review"><IssueList issues={formIssues}/>{saveError&&<p role="alert">{t(saveError)}</p>}{saveError==='packs.versionConflict'&&<><p>{t('packs.reloadHint')}</p><button className="button" type="button" onClick={()=>setReload(n=>n+1)}>{t('packs.reloadLatest')}</button></>}{progress&&<p role="status">{t(`packs.${progress.phase}`)}{progress.file&&` · ${progress.file} · ${progress.percent}%`}</p>}{checked&&<p role="status">{t('form.passed')}</p>}<div className="account-actions"><button className="button button-dark" type="submit" disabled={busy}>{t('form.check')}</button><button className="button" type="button" disabled={busy||categoryStatus!=='ready'} onClick={()=>void save()}>{t(edit?'packs.saveChanges':'form.save')}</button></div><p>{t('form.notSaved')}</p></div>
  </fieldset></form></>}<Link className="pack-back" to={edit?'/packs/'+id:'/packs'}>{t(edit?'packs.backDetail':'browseTitle')} <span aria-hidden="true">↗</span></Link></AccountLayout>;
}
