import {expect,test} from 'vitest';
import {createHash} from 'node:crypto';
import {zipSync,unzipSync,strFromU8} from 'fflate';
import type {StoredFile} from '@evertrace/shared';
import {assemblePackExport,safeDownloadName,type ExportPack,type ExportDependencies} from '../../apps/web/src/services/export-pack';
const digest=async(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
function fixture(){const bytes=new TextEncoder().encode('original'),pack:ExportPack={id:'pack-1',title:'../CON / 技能',category:'分类',ownerName:'Owner',ownerId:'owner',textContent:'原文\n',createdAt:'2026-10-05T00:00:00Z',version:3,status:'ready'},files:StoredFile[]=['one','two'].map((id,i)=>({id,kind:'eeg',originalName:i?'../same.xlsx':'same.xlsx',storagePath:'packs/pack-1/'+id,mediaType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),generation:'1',active:true}));let reads=0,renders=0,zips=0;const deps:ExportDependencies={readVersion:async()=>({version:3,status:'ready'}),readFile:async()=>{reads++;return bytes;},digest,parseEeg:async()=>({ok:true,issues:[],points:[{time:0,value:-1},{time:7,value:2}],summary:{start:0,end:7,min:-1,max:2,count:2,sheet:'EEG'}}),renderPng:async()=>{renders++;return new Uint8Array([137,80,78,71]);},zip:async entries=>{zips++;return zipSync(entries);}};return {pack,files,bytes,deps,counters:()=>({reads,renders,zips})};}
test('archive keeps originals, collision-free paths, original-language notes and full waveform manifests',async()=>{const f=fixture(),result=await assemblePackExport(f.pack,f.files,'zh',f.deps,new AbortController().signal,()=>{}),entries=unzipSync(result.bytes),manifest=JSON.parse(strFromU8(entries['manifest.json']));expect(result.name).not.toMatch(/[/\\]/);expect(Object.keys(entries)).toHaveLength(7);expect(strFromU8(entries['text/content.txt'])).toBe(f.pack.textContent);expect(strFromU8(entries['README.md'])).toContain('脑电原始值');expect(manifest.version).toBe(3);expect(manifest.files.map((x:{path:string})=>x.path)).toHaveLength(2);expect(new Set(manifest.files.map((x:{path:string})=>x.path)).size).toBe(2);for(const file of manifest.files){expect(entries[file.path]).toEqual(f.bytes);expect(file.sha256).toBe(await digest(f.bytes));expect(file.path).not.toContain('..');}expect(manifest.waveforms).toHaveLength(2);expect(manifest.waveforms[0]).toMatchObject({start:0,end:7,sampleCount:2,width:2400,height:1000});});
test('names remove traversal, reserved device names, controls and trailing unsafe punctuation',()=>{for(const name of ['../bad\\name:?.xlsx','CON','AUX.txt','NUL.','a\u0000b.txt','...']){const clean=safeDownloadName(name);expect(clean).not.toMatch(/[/\\:<>"|?*]/);expect(Array.from(clean).some(c=>c.charCodeAt(0)<32)).toBe(false);expect(clean).not.toMatch(/^(CON|AUX|NUL)(\.|$)/i);expect(clean).not.toMatch(/[ .]$/);}expect(safeDownloadName('中文.xlsx')).toBe('中文.xlsx');});
test('missing bytes, wrong size or hash and PNG failure stop before ZIP creation',async()=>{for(const scenario of ['missing','size','hash','png','parse']){const f=fixture();if(scenario==='missing')f.deps.readFile=async()=>{throw new Error('missing');};if(scenario==='size')f.deps.readFile=async()=>new Uint8Array([1]);if(scenario==='hash')f.deps.digest=async()=> 'wrong';if(scenario==='png')f.deps.renderPng=async()=>{throw new Error('PNG failed');};if(scenario==='parse')f.deps.parseEeg=async()=>({ok:false,issues:[{code:'eegCorrupt'}]});await expect(assemblePackExport(f.pack,f.files,'en',f.deps,new AbortController().signal,()=>{})).rejects.toThrow();expect(f.counters().zips).toBe(0);}});
test('version changes at start, during rendering or during ZIP never return an archive',async()=>{for(const stage of ['before','render','zip']){const f=fixture();let changed=stage==='before';f.deps.readVersion=async()=>({version:changed?4:3,status:'ready'});const render=f.deps.renderPng,zip=f.deps.zip;if(stage==='render')f.deps.renderPng=async(...args)=>{changed=true;return render(...args);};if(stage==='zip')f.deps.zip=async(...args)=>{changed=true;return zip(...args);};await expect(assemblePackExport(f.pack,f.files,'en',f.deps,new AbortController().signal,()=>{})).rejects.toThrow('exportChanged');if(stage==='before')expect(f.counters().reads).toBe(0);}});
test('deletion, cancellation, inactive or duplicate files and over-budget manifests are rejected',async()=>{for(const mode of ['deleted','cancelled','inactive','duplicate','budget']){const f=fixture(),abort=new AbortController();if(mode==='deleted')f.deps.readVersion=async()=>null;if(mode==='cancelled')abort.abort();if(mode==='inactive')f.files[0].active=false;if(mode==='duplicate')f.files[1].id=f.files[0].id;if(mode==='budget')f.files[0].size=31*1024*1024;await expect(assemblePackExport(f.pack,f.files,'en',f.deps,abort.signal,()=>{})).rejects.toThrow();expect(f.counters().zips).toBe(0);}});

test('cancelling a pending original read rejects promptly without waiting for the network',async()=>{const f=fixture(),abort=new AbortController();f.deps.readFile=()=>new Promise(()=>{});const result=assemblePackExport(f.pack,f.files,'en',f.deps,abort.signal,()=>{});setTimeout(()=>abort.abort(new Error('cancelled')),0);await expect(result).rejects.toThrow('cancelled');expect(f.counters().zips).toBe(0);},500);

test('long Chinese titles and archive names stay within UTF-8 filename limits and retain extensions',async()=>{const f=fixture();f.pack.title='脑'.repeat(160);f.pack.id='p'.repeat(100);for(const file of f.files)file.originalName='文'.repeat(140)+'.xlsx';const result=await assemblePackExport(f.pack,f.files,'en',f.deps,new AbortController().signal,()=>{}),entries=unzipSync(result.bytes);expect(new TextEncoder().encode(result.name).length).toBeLessThanOrEqual(255);for(const name of Object.keys(entries)){const leaf=name.split('/').at(-1)!;expect(new TextEncoder().encode(leaf).length).toBeLessThanOrEqual(255);}expect(Object.keys(entries).filter(name=>name.startsWith('eeg/')).every(name=>name.endsWith('.xlsx'))).toBe(true);expect(safeDownloadName('a'.repeat(155)+'.xlsx')).toBe('a'.repeat(155)+'.xlsx');});

test.each(['en','zh'])('confirmed unitless EEG format is recorded consistently in %s export metadata and instructions',async language=>{const f=fixture(),result=await assemblePackExport(f.pack,f.files,language,f.deps,new AbortController().signal,()=>{}),entries=unzipSync(result.bytes),manifest=JSON.parse(strFromU8(entries['manifest.json']));for(const waveform of manifest.waveforms)expect(waveform.valueUnit).toBe('unitless device raw value');expect(strFromU8(entries['README.md'])).toContain(language==='zh'?'无物理单位':'without a physical unit');});
