import { readFileSync } from 'node:fs';
import { afterAll, beforeAll, beforeEach, expect, it } from 'vitest';
import { initializeTestEnvironment, type RulesTestContext, type RulesTestEnvironment } from '@firebase/rules-unit-testing';
import { doc, Timestamp, writeBatch, type Firestore } from 'firebase/firestore';
import { normalizeTitleSearch } from '@evertrace/shared';
import { seedS1 } from '../spark-s1/fixtures';
import { listSparkPackPage, SPARK_PAGE_SIZE, type SparkListFilters, type SparkListCursor, type SparkPack } from '../../apps/web/src/services/spark-materials';
let env: RulesTestEnvironment;
const modular = (context: RulesTestContext) => (context.firestore() as unknown as { _delegate: Firestore })._delegate;
const client = (uid: string) => modular(env.authenticatedContext(uid, { email: `${uid}@example.test` }));
const trusted = (action: (db: Firestore) => Promise<void>) => env.withSecurityRulesDisabled(context => action(modular(context)));
const rows: SparkPack[] = [];
beforeAll(async () => { if (process.env.FIRESTORE_EMULATOR_HOST !== '127.0.0.1:28090') throw new Error('S3 query tests require isolated Firestore.'); env = await initializeTestEnvironment({ projectId: 'demo-evertrace-spark-test', firestore: { host: '127.0.0.1', port: 28090, rules: readFileSync('firebase/spark.rules', 'utf8') } }); });
beforeEach(async () => { rows.length = 0; await env.clearFirestore(); await trusted(db => seedS1(db)); });
afterAll(async () => { await env?.clearFirestore(); await env?.cleanup(); });
function row(i: number, title = 'Spark Search ' + String(i % 8).padStart(2, '0'), categoryId = i % 3 ? 'focus training' : '中文分类'): SparkPack {
  return { id: 's3-query-' + String(i).padStart(3, '0'), title, titleSearch: normalizeTitleSearch(title), textContent: 'Synthetic query metadata fixture.', ownerId: i % 2 ? 'member' : 'viewer', ownerName: 'Synthetic member', categoryId, version: 1, status: 'ready', totalBytes: 100, textFileCount: 0, imageCount: 0, eegCount: 1, submissionHash: 'a'.repeat(64), createdAt: Timestamp.fromMillis(1700000000000 + (i % 4) * 1000), updatedAt: Timestamp.fromMillis(1700000000000 + (i % 4) * 1000) };
}
async function seed(count = 37, titles?: string[]) {
  await trusted(async db => { const batch = writeBatch(db); for (let i = 0; i < count; i++) { const value = row(i, titles?.[i]); rows.push(value); const { id, ...data } = value; batch.set(doc(db, 'packs', id), data); } batch.set(doc(db, 'packs', 's3-hidden'), { ...row(999), title: 'Spark Search hidden', status: 'validating' }); await batch.commit(); });
}
async function all(filters: SparkListFilters, uid = 'member') {
  const items: SparkPack[] = []; let cursor: SparkListCursor | null = null;
  for (let page = 0; page < 10; page++) { const saved = await listSparkPackPage(client(uid), uid, filters, cursor); expect(saved.items.length).toBeLessThanOrEqual(12); items.push(...saved.items); cursor = saved.nextCursor; if (!cursor) return items; } throw new Error('Query did not finish.');
}
const lexical = (a: string, b: string) => Buffer.compare(Buffer.from(a), Buffer.from(b));
it('default pages have twelve metadata rows and stable timestamp/ID ordering without repeats or omissions', async () => { await seed(); expect(SPARK_PAGE_SIZE).toBe(12); const first = await listSparkPackPage(client('member'), 'member'); expect(first.items).toHaveLength(12); expect(first.nextCursor).not.toBeNull(); const actual = await all({}), expected = [...rows].sort((a, b) => b.createdAt.toMillis() - a.createdAt.toMillis() || lexical(b.id, a.id)); expect(actual.map(value => value.id)).toEqual(expected.map(value => value.id)); expect(new Set(actual.map(value => value.id)).size).toBe(rows.length); });
it('all eight title/category/mine combinations return exactly the matching ready rows in their declared order', async () => { await seed(); for (const prefix of ['', 'spark search 0']) for (const categoryId of ['', '中文分类']) for (const scope of ['all', 'mine'] as const) { const actual = await all({ prefix, categoryId, scope }), expected = rows.filter(value => (!prefix || value.titleSearch.startsWith(prefix)) && (!categoryId || value.categoryId === categoryId) && (scope === 'all' || value.ownerId === 'member')).sort((a, b) => prefix ? lexical(a.titleSearch, b.titleSearch) || lexical(a.id, b.id) : b.createdAt.toMillis() - a.createdAt.toMillis() || lexical(b.id, a.id)); expect(actual.map(value => value.id)).toEqual(expected.map(value => value.id)); } });
it('normalized fullwidth and mixed-case prefixes match only startsWith, including supplementary Unicode suffixes', async () => { const titles = ['ＦＯＣＵＳ Basics', 'Focus review', 'focus😀', 'Focus\uf8ff-tail', 'Focus\u{10ffff}', 'Before focus', '木工基础', '木工进阶', '做木工']; await seed(titles.length, titles); expect((await all({ prefix: ' ＦＯＣＵＳ ' })).map(value => value.title).sort()).toEqual(titles.slice(0, 5).sort()); expect((await all({ prefix: ' 木工 ' })).map(value => value.title).sort()).toEqual(['木工基础', '木工进阶']); });
it('an exactly full final page does not advertise another empty page', async () => { await seed(12); const page = await listSparkPackPage(client('member'), 'member'); expect(page.items).toHaveLength(12); expect(page.nextCursor).toBeNull(); });
it('an empty filter result is valid and has no next cursor', async () => { await seed(); const page = await listSparkPackPage(client('member'), 'member', { prefix: 'No matching title', categoryId: '中文分类', scope: 'mine' }); expect(page).toMatchObject({ items: [], nextCursor: null }); });
it('a cursor cannot be reused after any filter or current identity changes', async () => { await seed(); const first = await listSparkPackPage(client('member'), 'member', {}); expect(first.nextCursor).not.toBeNull(); for (const filters of [{ prefix: 'spark' }, { categoryId: '中文分类' }, { scope: 'mine' as const }]) await expect(listSparkPackPage(client('member'), 'member', filters, first.nextCursor)).rejects.toMatchObject({ code: 'queryCursor' }); await expect(listSparkPackPage(client('viewer'), 'viewer', {}, first.nextCursor)).rejects.toMatchObject({ code: 'queryCursor' }); });
it('invalid query inputs fail clearly before issuing a misleading result', async () => { for (const filters of [{ prefix: '\u0000' }, { prefix: 'x'.repeat(161) }, { prefix: '\ud800' }, { categoryId: 'a/b' }, { categoryId: 'x'.repeat(61) }, { scope: 'unknown' as 'mine' }]) await expect(listSparkPackPage(client('member'), 'member', filters)).rejects.toMatchObject({ code: 'queryInvalid' }); await expect(listSparkPackPage(client('member'), '', { scope: 'mine' })).rejects.toMatchObject({ code: 'queryInvalid' }); });
it('anonymous readers and authenticated identities without member profiles cannot query saved packs', async () => { await seed(); await expect(listSparkPackPage(modular(env.unauthenticatedContext()), '', {})).rejects.toMatchObject({ code: 'permission-denied' }); await expect(listSparkPackPage(client('unknown'), 'unknown', {})).rejects.toMatchObject({ code: 'permission-denied' }); });
it('a newly inserted leading record does not duplicate records on an existing cursor walk', async () => { await seed(25); const first = await listSparkPackPage(client('member'), 'member'); expect(first.nextCursor).not.toBeNull(); await trusted(async db => { const batch = writeBatch(db), { id, ...data } = { ...row(50), id: 's3-new-leading', createdAt: Timestamp.fromMillis(1900000000000) }; batch.set(doc(db, 'packs', id), data); await batch.commit(); }); const rest: SparkPack[] = []; let cursor = first.nextCursor; while (cursor) { const page = await listSparkPackPage(client('member'), 'member', {}, cursor); rest.push(...page.items); cursor = page.nextCursor; } expect(new Set([...first.items, ...rest].map(value => value.id)).size).toBe(25); expect(rest.some(value => value.id === 's3-new-leading')).toBe(false); });
